'use strict';
let weaponRange=false;
const smartStates=new Map(),harpoonTethers=[],clusterShells=[];
function smartCandidate(actor){let best=null,distance=601;for(const target of [p,...enemies]){if(target===actor||!aliveActor(target))continue;const d=Math.hypot(target.x-actor.x,target.y-actor.y),desired=Math.atan2(target.x-actor.x,-(target.y-actor.y)),diff=Math.atan2(Math.sin(desired-actor.angle),Math.cos(desired-actor.angle));if(!weatherCanSee(actor,target)||d>600||d>=distance||Math.abs(diff)>Math.PI/9||smokeObscures(actor.x,actor.y,target.x,target.y))continue;const obstruction=urbanSweep(actor.x,actor.y,target.x,target.y);if(obstruction)continue;best=target;distance=d}return best}
function stepAdvancedWeapons(dt){
 for(const actor of [p,...enemies]){if(!aliveActor(actor)||actorLoadout(actor).left!=='smart'){smartStates.delete(actor);continue}let s=smartStates.get(actor);if(!s){s={target:null,progress:0,ready:false,x:0,y:0,vx:0,vy:0};smartStates.set(actor,s)}const target=smartCandidate(actor);if(s.target!==target){Object.assign(s,{target,progress:0,ready:false,vx:0,vy:0,x:target?.x||0,y:target?.y||0})}if(target){const previous=s.ready;s.vx=(target.x-s.x)/dt;s.vy=(target.y-s.y)/dt;s.x=target.x;s.y=target.y;s.progress=Math.min(.4,s.progress+dt);s.ready=s.progress>=.4;if(s.ready&&!previous&&actor===p)lockBeep(1250,.08)}}
 for(let i=harpoonTethers.length-1;i>=0;i--){const t=harpoonTethers[i];t.age+=dt;const blocked=urbanSweep(t.owner.x,t.owner.y,t.target.x,t.target.y);if(t.age>2.5||!aliveActor(t.owner)||!aliveActor(t.target)||t.target.generation!==t.generation||blocked||Math.hypot(t.owner.x-t.target.x,t.owner.y-t.target.y)>900){Sound.stopLoop(t.key);harpoonTethers.splice(i,1);continue}const d=Math.hypot(t.owner.x-t.target.x,t.owner.y-t.target.y);if(d>230)urbanMove(t.target,t.target.x+(t.owner.x-t.target.x)/d*65*dt,t.target.y+(t.owner.y-t.target.y)/d*65*dt);Sound.loop('harpoon-reel',t.key,t.target.x,t.target.y,.4)}
 for(let i=clusterShells.length-1;i>=0;i--){const s=clusterShells[i];s.age+=dt;if(s.age>=s.flight){splitCluster(s);clusterShells.splice(i,1)}}
}
function attachHarpoon(round,hit){const key='harpoon-'+(++shotSerial);harpoonTethers.push({owner:round.owner,target:hit.target,generation:hit.target.generation,age:0,key});}
function launchCluster(owner,point,stats){if(weaponRange&&rangeState?.running)rangeState.shotsFired++;const candidate=[p,...enemies].filter(a=>a!==owner&&aliveActor(a)).map(a=>({a,d:Math.hypot(a.x-owner.x,a.y-owner.y),diff:Math.atan2(Math.sin(Math.atan2(a.x-owner.x,-(a.y-owner.y))-owner.angle),Math.cos(Math.atan2(a.x-owner.x,-(a.y-owner.y))-owner.angle))})).filter(v=>v.d<=1100&&Math.abs(v.diff)<.65&&!urbanSweep(owner.x,owner.y,v.a.x,v.a.y)).sort((a,b)=>a.d-b.d)[0]?.a;const distance=candidate?Math.hypot(candidate.x-point.x,candidate.y-point.y):780,travel=Math.max(180,Math.min(650,distance*.55));clusterShells.push({owner,target:candidate,targetLife:candidate?.generation,x:point.x,y:point.y,ex:point.x+Math.sin(owner.angle)*travel,ey:point.y-Math.cos(owner.angle)*travel,age:0,flight:1.35,stats});Sound.play('fire-mortar',point.x,point.y,.95,1,true);smokePuff(point.x,point.y,24,1.4);flashes.push({x:point.x,y:point.y,r:12,life:.1,total:.1,color:'#ffd38b',muzzle:true,lightRadius:140});}
function splitCluster(s){Sound.play('cluster-split',s.ex,s.ey,.65,1,true);puff(s.ex,s.ey,'#ffe6a6',18,100,2,.4);for(let k=0;k<7;k++){queueClusterChild(s,k)}}
function queueClusterChild(s,k){withShooter(s.owner,()=>queueLaunch(k*.055,()=>{const a=s.owner.angle+k*Math.PI*2/7;if(weaponRange&&rangeState?.running)rangeState.shotsFired++;rounds.push({owner:s.owner,x:s.ex,y:s.ey,px:s.ex,py:s.ey,a,id:'cluster-child',stats:{...s.stats,damage:s.stats.damage/7},target:s.target,targetLife:s.targetLife,speed:520,life:4.5,age:0,trail:0,travel:0,fan:k%2?.8:-.8,soundKey:'cluster-flight-'+(++shotSerial)});Sound.play('fire-cluster-child',s.ex,s.ey,.22,.95+k*.02,true)}))}
function clearAdvancedWeapons(){for(const t of harpoonTethers)Sound.stopLoop(t.key);harpoonTethers.length=0;clusterShells.length=0;smartStates.clear()}
function drawAdvancedWeapons(c){for(const t of harpoonTethers){const prev=activeShooter;activeShooter=t.owner;const point=mountPorts('harpoon',85)[0];activeShooter=prev;c.save();c.strokeStyle='#080b0d';c.lineWidth=4;c.beginPath();c.moveTo(point.x,point.y);c.quadraticCurveTo((point.x+t.target.x)/2,(point.y+t.target.y)/2+12,t.target.x,t.target.y);c.stroke();c.strokeStyle='#a4b2b8';c.lineWidth=1.4;c.stroke();c.restore()}
 for(const s of clusterShells){const u=Math.min(1,s.age/s.flight),x=s.x+(s.ex-s.x)*u,y=s.y+(s.ey-s.y)*u,lift=Math.sin(u*Math.PI)*190;c.save();c.fillStyle='#0006';c.beginPath();c.ellipse(x,y,14,9,0,0,7);c.fill();c.translate(x+lift*.18,y-lift);c.rotate(s.owner.angle);c.scale(1+Math.sin(u*Math.PI)*.9,1+Math.sin(u*Math.PI)*.9);c.fillStyle='#bcc4ad';c.fillRect(-5,-12,10,24);c.fillStyle='#d7b147';c.fillRect(-5,-4,10,3);c.restore();softSmoke(c,x+lift*.18,y-lift+14,13,.18)}
 const s=smartStates.get(p);if(s?.target){const a=s.target;c.save();c.strokeStyle=s.ready?'#ff4545':'#ffcd69';c.lineWidth=3;for(const [sx,sy]of [[-1,-1],[1,-1],[-1,1],[1,1]]){c.beginPath();c.moveTo(a.x+sx*140,a.y+sy*100);c.lineTo(a.x+sx*140,a.y+sy*140);c.lineTo(a.x+sx*100,a.y+sy*140);c.stroke()}c.restore()}}
