'use strict';
const ARENA_VARIANTS={desert:{label:'Desert',ground:'arena-desert',dark:.10},flooded:{label:'Flooded',ground:'arena-flooded',dark:.24},night:{label:'Dark nighttime',ground:'arena-flooded',dark:.76},rotating:{label:'Rotating centre',ground:'arena-desert',dark:.32},snow:{label:'Snow',ground:'arena-snow',dark:.08},conveyors:{label:'Conveyor belts',ground:'arena-desert',dark:.42}};
let arenaKind='night',terrainAngle=0,terrainClock=0,winnerPending=null;
try{const saved=localStorage.getItem('iron-pit-arena');if(ARENA_VARIANTS[saved])arenaKind=saved}catch(e){}
function resetTerrain(){terrainAngle=0;terrainClock=0;winnerPending=null;layoutCanvas=null;Sound.stopLoop('arena-machinery')}
function terrainBelts(){return[{x:365,y:0,w:500,h:ARENA.height,vx:0,vy:-65},{x:0,y:620,w:ARENA.width,h:500,vx:65,vy:0},{x:1075,y:1120,w:675,h:500,vx:-65,vy:0}]}
function stepTerrain(dt){terrainClock+=dt;if(arenaMode!=='solo'||[p,...enemies].filter(aliveActor).length<2){Sound.stopLoop('arena-machinery');return}if(arenaKind==='rotating'){const delta=.065*dt,old=terrainAngle;terrainAngle+=delta;for(const a of [p,...enemies]){if(!aliveActor(a)||Math.hypot(a.x-ARENA.width/2,a.y-ARENA.height/2)>500)continue;const dx=a.x-ARENA.width/2,dy=a.y-ARENA.height/2;a.x=ARENA.width/2+dx*Math.cos(delta)-dy*Math.sin(delta);a.y=ARENA.height/2+dx*Math.sin(delta)+dy*Math.cos(delta);a.heading+=delta;a.angle+=delta}if(Math.floor(old/.025)!==Math.floor(terrainAngle/.025)){navigation=null;for(const a of enemies)a.repath=0}Sound.loop('engine-tracks','arena-machinery',p.x,p.y,.12,.7)}else if(arenaKind==='conveyors'){for(const a of [p,...enemies]){if(!aliveActor(a))continue;const belt=terrainBelts().filter(b=>a.x>=b.x&&a.x<=b.x+b.w&&a.y>=b.y&&a.y<=b.y+b.h).at(-1);if(belt)urbanMove(a,a.x+belt.vx*dt,a.y+belt.vy*dt)}Sound.loop('engine-tracks','arena-machinery',p.x,p.y,.12,.8)}}
function drawTerrain(c){if(arenaMode!=='solo')return;if(arenaKind==='rotating'){c.save();c.translate(ARENA.width/2,ARENA.height/2);c.rotate(terrainAngle);c.drawImage(images['arena-platform'],-510,-510,1020,1020);c.restore()}if(arenaKind==='conveyors')for(const b of terrainBelts()){c.save();c.beginPath();c.rect(b.x,b.y,b.w,b.h);c.clip();const vertical=b.vy!==0;c.fillStyle='#161d23';c.fillRect(b.x,b.y,b.w,b.h);c.strokeStyle='#53636b';c.lineWidth=4;const spacing=38,offset=((vertical?b.vy:b.vx)*terrainClock)%spacing;for(let z=-spacing;z<(vertical?b.h:b.w)+spacing;z+=spacing){c.save();if(!vertical){c.translate(b.x+z+offset,b.y);c.rotate(Math.PI/2);c.drawImage(conveyorTread(),0,-spacing,b.h,spacing)}else c.drawImage(conveyorTread(),b.x,b.y+z+offset,b.w,spacing);c.restore();c.beginPath();if(vertical){c.moveTo(b.x,b.y+z+offset);c.lineTo(b.x+b.w,b.y+z+offset)}else{c.moveTo(b.x+z+offset,b.y);c.lineTo(b.x+z+offset,b.y+b.h)}c.stroke()}c.fillStyle='#777756';for(let z=180;z<(vertical?b.h:b.w);z+=420){const x=vertical?b.x+b.w/2:b.x+z,y=vertical?b.y+z:b.y+b.h/2;c.save();c.translate(x,y);c.rotate(vertical?(b.vy<0?0:Math.PI):(b.vx>0?Math.PI/2:-Math.PI/2));c.beginPath();c.moveTo(-28,15);c.lineTo(0,-15);c.lineTo(28,15);c.lineTo(28,31);c.lineTo(0,1);c.lineTo(-28,31);c.closePath();c.fill();c.restore()}c.restore();c.strokeStyle='#9c9157';c.lineWidth=8;c.strokeRect(b.x+4,b.y+4,b.w-8,b.h-8)}if(arenaKind==='flooded'){c.save();c.strokeStyle='rgba(175,214,226,.13)';c.lineWidth=2;for(const a of [p,...enemies])if(aliveActor(a)){for(let i=0;i<3;i++){const age=(terrainClock+i*.6)%1.8;c.globalAlpha=1-age/1.8;c.beginPath();c.ellipse(a.x,a.y,55+age*60,35+age*35,0,0,Math.PI*2);c.stroke()}}c.restore()}}
function queueWinnerAnnouncement(actor){winnerPending={age:0,name:actor.human?'winner-p'+(actor.duelIndex+1):actor===p?'winner-you':'winner-breaker'}}
function stepWinnerAnnouncement(dt){if(!winnerPending||!inArena||document.hidden)return;winnerPending.age+=dt;if(winnerPending.age>=1.5){stadiumSound(winnerPending.name,1.3);crowdDuck=Math.max(crowdDuck,5);winnerPending=null}}
function setupArenaMenu(){const menu=document.getElementById('arenaChoice');menu.value=arenaKind;menu.onchange=()=>{if(ARENA_VARIANTS[menu.value]){arenaKind=menu.value;try{localStorage.setItem('iron-pit-arena',arenaKind)}catch(e){}}};}

let conveyorTreadCanvas=null;
function conveyorTread(){if(conveyorTreadCanvas)return conveyorTreadCanvas;const cv=document.createElement('canvas');cv.width=500;cv.height=38;const c=cv.getContext('2d');c.drawImage(images['arena-desert'],120,120,500,38,0,0,500,38);const g=c.createLinearGradient(0,0,0,38);g.addColorStop(0,'rgba(120,130,134,.92)');g.addColorStop(.13,'rgba(55,66,71,.85)');g.addColorStop(.8,'rgba(35,43,49,.90)');g.addColorStop(1,'rgba(5,9,13,.95)');c.fillStyle=g;c.fillRect(0,0,500,38);for(let i=0;i<180;i++){const x=(i*73.127)%500,y=(i*17.531)%38;c.fillStyle=i%3?'#aab4b21b':'#050b0f50';c.fillRect(x,y,1+i%9,1)}for(const x of [10,490]){c.fillStyle='#0b1118';c.beginPath();c.arc(x,19,5,0,7);c.fill();c.fillStyle='#8c9698';c.beginPath();c.arc(x-1,18,2.5,0,7);c.fill()}conveyorTreadCanvas=cv;return cv}
