'use strict';
const Sound={context:null,buffers:{},voices:[],muted:false,last:{},loading:null,motionLoops:{},motionNodes:new Set(),turretSession:null,turretTail:null,bipedNodes:{},effectLoops:{},
 async unlock(){try{if(!this.context){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=this.context=new A();this.master=c.createGain();this.master.gain.value=.7;const limiter=c.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=12;limiter.ratio.value=6;limiter.attack.value=.003;limiter.release.value=.18;this.master.connect(limiter);limiter.connect(c.destination);this.dry=c.createGain();this.dry.gain.value=.88;this.dry.connect(this.master);this.loading=Promise.all(SOUND_FILES.map(async name=>{try{const r=await fetch('audio/'+name+'.wav');if(!r.ok)throw Error(name);this.buffers[name]=await c.decodeAudioData(await r.arrayBuffer())}catch(e){console.warn('Audio unavailable:',name)}}))}await this.context.resume()}catch(e){console.warn('Sound unavailable',e)}},
 play(name,x,y,gain=1,rate=null,force=false,offset=0){const c=this.context;if(this.muted||!c||c.state!=='running'||!this.buffers[name]||offset>=this.buffers[name].duration)return;const time=c.currentTime;if(!force&&time-(this.last[name]??-10)<(name.startsWith('hit-')?.045:name==='shield'?.065:.04))return;this.last[name]=time;while(this.voices.length>=48){const old=this.voices.shift();try{old.stop()}catch(e){}}const s=c.createBufferSource();s.buffer=this.buffers[name];s.playbackRate.value=rate??(.97+Math.random()*.06);const g=c.createGain();const dist=typeof p!=='undefined'?Math.hypot(x-p.x,y-p.y):0;g.gain.value=gain/(1+dist/650);s.connect(g);let end=g;if(c.createStereoPanner){const pan=c.createStereoPanner();pan.pan.value=Math.max(-.7,Math.min(.7,(x-p.x)/500));g.connect(pan);end=pan}end.connect(this.dry);this.voices.push(s);s.onended=()=>{this.voices=this.voices.filter(v=>v!==s);s.disconnect();g.disconnect();if(end!==g)end.disconnect()};s.start(0,Math.max(0,offset))},
 loop(name,key,x,y,level=.55,rate=1){const c=this.context;if(this.muted||document.hidden||!c||c.state!=='running'||!this.buffers[name])return;let n=this.effectLoops[key];if(n&&n.name!==name){this.stopLoop(key);n=null}if(!n){const source=c.createBufferSource(),gain=c.createGain();source.buffer=this.buffers[name];source.loop=true;source.playbackRate.value=rate;source.connect(gain);let pan=null;if(c.createStereoPanner){pan=c.createStereoPanner();gain.connect(pan);pan.connect(this.dry)}else gain.connect(this.dry);gain.gain.value=0;source.start();n=this.effectLoops[key]={source,gain,pan,name};source.onended=()=>{source.disconnect();gain.disconnect();pan?.disconnect()}}const dist=Math.hypot(x-p.x,y-p.y);n.gain.gain.setTargetAtTime(level/(1+dist/500),c.currentTime,.035);if(n.pan)n.pan.pan.setTargetAtTime(Math.max(-.7,Math.min(.7,(x-p.x)/500)),c.currentTime,.035)},
 stopLoop(key){const n=this.effectLoops[key];if(!n)return;delete this.effectLoops[key];const c=this.context;n.gain.gain.setTargetAtTime(0,c.currentTime,.018);try{n.source.stop(c.currentTime+.08)}catch(e){}},
 stopEffects(){for(const key of Object.keys(this.effectLoops))this.stopLoop(key)},
 stopAll(){this.stopMotion();this.stopEffects();for(const s of this.voices){try{s.stop()}catch(e){}}this.voices=[]},
 motion(drive=0,traverse=0){if(document.hidden)return;const c=this.context;if(!c||c.state!=='running')return;const value=this.muted?0:Math.max(0,Math.min(1,drive));let loop=this.motionLoops.engine;if(!loop&&value>0&&this.buffers['engine-tracks']){const source=c.createBufferSource(),gain=c.createGain();source.buffer=this.buffers['engine-tracks'];source.loop=true;gain.gain.value=0;source.connect(gain);gain.connect(this.dry);source.start();loop=this.motionLoops.engine={source,gain,target:-1,rate:-1}}if(loop){const target=value*.40,rate=.90+.10*value;if(Math.abs(target-loop.target)>.002){loop.gain.gain.cancelScheduledValues(c.currentTime);loop.gain.gain.setTargetAtTime(target,c.currentTime,value>0?.08:.10);loop.target=target}if(Math.abs(rate-loop.rate)>.005){loop.source.playbackRate.setTargetAtTime(rate,c.currentTime,.12);loop.rate=rate}}this.turretMotion(!this.muted&&traverse>.08)},
 motionNode(name,when,loop=false){const c=this.context,source=c.createBufferSource(),gain=c.createGain();source.buffer=this.buffers[name];source.loop=loop;gain.gain.setValueAtTime(0,when);gain.gain.linearRampToValueAtTime(.55,when+.025);source.connect(gain);gain.connect(this.dry);const node={source,gain};this.motionNodes.add(node);source.onended=()=>{source.disconnect();gain.disconnect();this.motionNodes.delete(node);if(this.turretTail===node)this.turretTail=null};source.start(when);return node},
 fadeMotionNode(node){if(!node)return;const c=this.context;node.gain.gain.cancelScheduledValues(c.currentTime);node.gain.gain.setTargetAtTime(0,c.currentTime,.012);try{node.source.stop(c.currentTime+.05)}catch(e){}},
 turretMotion(moving){const c=this.context;if(moving){if(this.turretSession||!['turret-start','turret-loop','turret-stop'].every(n=>this.buffers[n]))return;this.fadeMotionNode(this.turretTail);this.turretTail=null;const start=this.motionNode('turret-start',c.currentTime),loop=this.motionNode('turret-loop',c.currentTime+Math.max(.025,this.buffers['turret-start'].duration-.025),true);this.turretSession={start,loop}}else if(this.turretSession){this.fadeMotionNode(this.turretSession.start);this.fadeMotionNode(this.turretSession.loop);this.turretSession=null;this.turretTail=this.motionNode('turret-stop',c.currentTime)}},
 bipedSwing(side,moving,progress=0){const c=this.context;if(!c||c.state!=='running'||this.muted||document.hidden)return;let node=this.bipedNodes[side];if(!moving){this.fadeMotionNode(node);delete this.bipedNodes[side];return}if(!node&&this.buffers['biped-hydraulic']){node=this.motionNode('biped-hydraulic',c.currentTime,true);this.bipedNodes[side]=node}if(node){node.source.playbackRate.setTargetAtTime(.85+.3*progress,c.currentTime,.025);node.gain.gain.setTargetAtTime(.24+.12*progress,c.currentTime,.025)}},
 bipedLand(side){this.bipedSwing(side,false);const c=this.context;if(!c||c.state!=='running'||this.muted||document.hidden||!this.buffers['biped-step'])return;const node=this.motionNode('biped-step',c.currentTime);node.source.playbackRate.value=.98+Math.random()*.04;node.gain.gain.cancelScheduledValues(c.currentTime);node.gain.gain.setValueAtTime(.85,c.currentTime)},
 stopMotion(){for(const loop of Object.values(this.motionLoops)){try{loop.source.stop()}catch(e){}loop.source.disconnect();loop.gain.disconnect()}this.motionLoops={};for(const node of this.motionNodes){try{node.source.stop()}catch(e){}node.source.disconnect();node.gain.disconnect()}this.motionNodes.clear();this.bipedNodes={};this.turretSession=null;this.turretTail=null},
 toggle(){this.muted=!this.muted;if(this.muted)this.stopAll();if(this.master)this.master.gain.value=this.muted?0:.7;document.getElementById('mute').textContent=this.muted?'SOUND OFF':'SOUND ON'}
};
const SOUND_IDS=['machine-gun','rotary','siege','tri-salvo','railgun','flak','plasma','pulse','beam','flame','arc','emp','swarm','hunter','barrage','mines','smoke','mortar'];
const SOUND_FILES=[...SOUND_IDS.map(n=>'fire-'+n),...SOUND_IDS.map(n=>'hit-'+n),'shield','biped-step','biped-hydraulic','engine-tracks','turret-start','turret-loop','turret-stop','swarm-scream','plasma-charge','beam-start','beam-stop','flame-start','mine-flight','mine-arm','mech-explosion','nuke-explosion','eject-siren','eject-jet','debris-0','debris-1','debris-2','urban-collapse'];
document.addEventListener('pointerdown',()=>Sound.unlock(),{passive:true});document.addEventListener('keydown',()=>Sound.unlock());

document.addEventListener('visibilitychange',()=>{if(document.hidden)Sound.stopAll();else if(typeof p!=='undefined'&&p.ejecting&&!p.dead&&p.ejecting.age<3)Sound.play('eject-siren',p.x,p.y,.85,1,true,p.ejecting.age)});
