'use strict';
const Sound={context:null,buffers:{},voices:[],muted:false,last:{},loading:null,
 async unlock(){try{if(!this.context){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=this.context=new A();this.master=c.createGain();this.master.gain.value=.7;const limiter=c.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=12;limiter.ratio.value=6;limiter.attack.value=.003;limiter.release.value=.18;this.master.connect(limiter);limiter.connect(c.destination);this.dry=c.createGain();this.dry.gain.value=.88;this.dry.connect(this.master);this.loading=Promise.all(SOUND_FILES.map(async name=>{try{const r=await fetch('audio/'+name+'.wav');if(!r.ok)throw Error(name);this.buffers[name]=await c.decodeAudioData(await r.arrayBuffer())}catch(e){console.warn('Audio unavailable:',name)}}))}await this.context.resume()}catch(e){console.warn('Sound unavailable',e)}},
 play(name,x,y,gain=1){const c=this.context;if(this.muted||!c||c.state!=='running'||!this.buffers[name])return;const time=c.currentTime;if(time-(this.last[name]??-10)<(name.startsWith('hit-')?.045:name==='shield'?.065:.04))return;this.last[name]=time;while(this.voices.length>=24){const old=this.voices.shift();try{old.stop()}catch(e){}}const s=c.createBufferSource();s.buffer=this.buffers[name];s.playbackRate.value=.97+Math.random()*.06;const g=c.createGain();const dist=typeof p!=='undefined'?Math.hypot(x-p.x,y-p.y):0;g.gain.value=gain/(1+dist/650);s.connect(g);let end=g;if(c.createStereoPanner){const pan=c.createStereoPanner();pan.pan.value=Math.max(-.7,Math.min(.7,(x-p.x)/500));g.connect(pan);end=pan}end.connect(this.dry);this.voices.push(s);s.onended=()=>{this.voices=this.voices.filter(v=>v!==s);s.disconnect();g.disconnect();if(end!==g)end.disconnect()};s.start()},
 toggle(){this.muted=!this.muted;if(this.master)this.master.gain.value=this.muted?0:.7;document.getElementById('mute').textContent=this.muted?'SOUND OFF':'SOUND ON'}
};
const SOUND_IDS=['machine-gun','rotary','siege','tri-salvo','railgun','flak','plasma','pulse','beam','flame','arc','emp','swarm','hunter','barrage','mines','smoke','mortar'];
const SOUND_FILES=[...SOUND_IDS.map(n=>'fire-'+n),...SOUND_IDS.map(n=>'hit-'+n),'shield'];
document.addEventListener('pointerdown',()=>Sound.unlock(),{passive:true});document.addEventListener('keydown',()=>Sound.unlock());
