'use strict';
// Standard build: raw damage budgets, before armour and component allocation.
const BALANCE={
 'machine-gun':{damage:9,penetration:.05},rotary:{damage:15,penetration:.1},siege:{damage:97.5,penetration:.35,blast:55},'tri-salvo':{damage:45,blast:65},railgun:{damage:200,penetration:.9},flak:{damage:18,penetration:.1},plasma:{damage:100,penetration:.4},pulse:{damage:10,penetration:.15},beam:{damage:120,continuous:true,penetration:.35},flame:{damage:120,continuous:true,penetration:.1,burn:30},arc:{damage:80,continuous:true,penetration:.4,slow:.65,duration:.8},emp:{damage:40,penetration:1,slow:.25,duration:1.8},swarm:{damage:36,blast:40},hunter:{damage:90,blast:85},barrage:{damage:56,blast:60},mortar:{damage:110,blast:65},mines:{damage:66,blast:80},smoke:{damage:0}
};
const SUSTAINED_DPS={'machine-gun':65,rotary:75,pulse:70,beam:60,flame:75,arc:50,siege:48.75,railgun:60,plasma:65,'tri-salvo':45,flak:60,emp:5,swarm:36,hunter:40,barrage:40,mines:33,smoke:0,mortar:220/7};
let modifications={primary:'standard',secondary:'standard',support:'standard'};
try{const saved=JSON.parse(localStorage.getItem('iron-pit-modifications'));for(const slot in modifications)if(['standard','power','rapid','penetrator','blast'].includes(saved?.[slot]))modifications[slot]=saved[slot]}catch(e){}
function weaponStats(id,mod='standard'){const b={...BALANCE[id],damage:BALANCE[id]?.damage||0,penetration:BALANCE[id]?.penetration||0,rate:GUNS[id]?.rate||1};if(mod==='power'){b.damage*=1.25;b.rate*=1.15}if(mod==='rapid'){b.rate*=.8;b.damage*=.88}if(mod==='penetrator'){b.penetration=Math.min(1,b.penetration+.4);b.damage*=.9}if(mod==='blast'){b.blast*=1.35;b.damage*=.9}return b}
function shotStats(id,offset){return weaponStats(id,modifications[offset===0?'support':offset<0?'primary':'secondary'])}
function refreshMods(){for(const [slot,key]of [['primary','left'],['secondary','right'],['support','rear']]){const id=build[key],b=BALANCE[id],select=document.getElementById(slot+'Mod');const options=[['standard','Standard']];if(id){if(b.damage>0)options.push(['power','Power: +25% damage, slower reload']);if(!b.continuous)options.push(['rapid','Rapid: faster reload, −12% damage']);if(b.damage>0)options.push(['penetrator','Armour piercing: less damage, more penetration']);if(b.blast)options.push(['blast','Wide blast: +35% radius, −10% damage'])}select.innerHTML=options.map(([v,n])=>`<option value="${v}">${n}</option>`).join('');if(!options.some(v=>v[0]===modifications[slot]))modifications[slot]='standard';select.value=modifications[slot];select.disabled=!id;select.onchange=()=>{modifications[slot]=select.value;try{localStorage.setItem('iron-pit-modifications',JSON.stringify(modifications))}catch(e){}showStats()}}showStats()}
function showStats(){const rows=[];for(const[slot,key]of [['primary','left'],['secondary','right'],['support','rear']]){const id=build[key];if(!id)continue;const b=weaponStats(id,modifications[slot]),count=id==='mines'?5:id==='flak'?5:GUNS[id].cycle?1:GUNS[id].ports.length;rows.push(`${SLOT_LABELS[slot]}: ${Math.round(b.damage*(b.continuous?1:count))}${b.continuous?' damage/sec':' damage/volley'} · ${b.continuous?'heat limited':b.rate.toFixed(2)+'s reload'}${id==='flame'?' + 30/sec burn':''}`)}document.getElementById('weaponStats').textContent=rows.join(' | ')+' · Standard sustained DPS targets include cooling. Armour and hit location affect actual damage.'}
function drawLocalLights(c){c.save();c.globalCompositeOperation='screen';for(const f of flashes){if(f.ring)continue;const life=f.life/f.total,r=f.muzzle?(f.lightRadius||100)*1.8:(f.lightRadius||f.r*3),alpha=life*(f.muzzle?.68:.42);glow(c,f.x,f.y,r,f.color,alpha)}for(const e of particles)if(e.kind==='fire')glow(c,e.x,e.y,Math.min(90,e.size*4),'#ff8b31',.08*e.life/e.max);for(const l of lines)if(!l.arc){glow(c,l.x,l.y,75,l.color,.08*l.life/l.total);glow(c,l.ex,l.ey,55,l.color,.13*l.life/l.total)}c.restore()}
