'use strict';
// Standard build: damage progression calibrated against the 700-hull weapon range.
const BALANCE={
 smart:{damage:7.7,penetration:.08},harpoon:{damage:25,penetration:.3,slow:.55,duration:2.5},'cluster-child':{damage:35,penetration:.15,blast:45},
 'machine-gun':{damage:7.4,penetration:.05},rotary:{damage:11.6,penetration:.1},siege:{damage:105,penetration:.35,blast:55},'tri-salvo':{damage:44,blast:65},railgun:{damage:180,penetration:.9},flak:{damage:19,penetration:.1},plasma:{damage:75,penetration:.4},pulse:{damage:9,penetration:.15},beam:{damage:190,continuous:true,penetration:.35},flame:{damage:112,continuous:true,penetration:.1,burn:30},arc:{damage:112,continuous:true,penetration:.4,slow:.65,duration:.8},emp:{damage:40,penetration:1,slow:.25,duration:1.8},swarm:{damage:51,blast:40},hunter:{damage:78,blast:85},barrage:{damage:72,blast:60},mortar:{damage:450,penetration:.15,blast:45},mines:{damage:66,blast:80},smoke:{damage:0}
};
let modifications={primary:'standard',secondary:'standard',support:'standard'};
try{const saved=JSON.parse(localStorage.getItem('iron-pit-modifications'));for(const slot in modifications)if(['standard','power','rapid','penetrator','blast'].includes(saved?.[slot]))modifications[slot]=saved[slot]}catch(e){}
function weaponStats(id,mod='standard'){const b={...BALANCE[id],damage:BALANCE[id]?.damage||0,penetration:BALANCE[id]?.penetration||0,rate:GUNS[id]?.rate||1};if(mod==='power'){b.damage*=1.25;b.rate*=1.15}if(mod==='rapid'){b.rate*=.8;b.damage*=.88}if(mod==='penetrator'){b.penetration=Math.min(1,b.penetration+.4);b.damage*=.9}if(mod==='blast'){b.blast*=1.35;b.damage*=.9}return b}
function shotStats(id,offset){return weaponStats(id,modifications[offset===0?'support':offset<0?'primary':'secondary'])}
function refreshMods(){for(const [slot,key]of [['primary','left'],['secondary','right'],['support','rear']]){const id=build[key],b=BALANCE[id],select=document.getElementById(slot+'Mod');const options=[['standard','Standard']];if(id){if(b.damage>0)options.push(['power','Power: +25% damage, slower reload']);if(!b.continuous)options.push(['rapid','Rapid: faster reload, −12% damage']);if(b.damage>0)options.push(['penetrator','Armour piercing: less damage, more penetration']);if(b.blast)options.push(['blast','Wide blast: +35% radius, −10% damage'])}select.innerHTML=options.map(([v,n])=>`<option value="${v}">${n}</option>`).join('');if(!options.some(v=>v[0]===modifications[slot]))modifications[slot]='standard';select.value=modifications[slot];select.disabled=!id;select.onchange=()=>{modifications[slot]=select.value;try{localStorage.setItem('iron-pit-modifications',JSON.stringify(modifications))}catch(e){}showStats()}}showStats()}
function showStats(){const rows=[];for(const[slot,key]of [['primary','left'],['secondary','right'],['support','rear']]){const id=build[key];if(!id)continue;const b=weaponStats(id,modifications[slot]),count=id==='mines'?5:id==='flak'?5:GUNS[id].cycle?1:GUNS[id].ports.length;rows.push(`${SLOT_LABELS[slot]}: ${Math.round(b.damage*(b.continuous?1:count))}${b.continuous?' damage/sec':' damage/volley'} · ${b.continuous?'heat limited':b.rate.toFixed(2)+'s reload'}${id==='flame'?' + 30/sec burn':''}`)}document.getElementById('weaponStats').textContent=rows.join(' | ')+' · Reloads, cooling, range and armour affect actual damage. EMP and Harpoon are utility weapons.'}
function drawLocalLights(c){c.save();c.globalCompositeOperation='screen';for(const f of flashes){if(f.ring)continue;const life=f.life/f.total,r=f.muzzle?(f.lightRadius||100)*1.8:(f.lightRadius||f.r*3),alpha=life*(f.muzzle?.68:.42);glow(c,f.x,f.y,r,f.color,alpha)}for(const e of particles)if(e.kind==='fire')glow(c,e.x,e.y,Math.min(90,e.size*4),'#ff8b31',.08*e.life/e.max);for(const l of lines)if(!l.arc){glow(c,l.x,l.y,75,l.color,.08*l.life/l.total);glow(c,l.ex,l.ey,55,l.color,.13*l.life/l.total)}c.restore()}
