'use strict';
const BIPED_ASSETS=['biped-thigh','biped-shin','biped-knee','biped-foot'];
const BIPED_SPEED=70,BIPED_TURN=Math.PI/4,BIPED_STRIDE=75;
const bipedRig={feet:[],clock:0,active:false};
function rotatePoint(x,y,a){return{x:x*Math.cos(a)-y*Math.sin(a),y:x*Math.sin(a)+y*Math.cos(a)}}
function resetBiped(){bipedRig.clock=0;bipedRig.active=false;bipedRig.feet=[-1,1].map(side=>{const v=rotatePoint(side*60,57,p.heading);return{side,x:p.x+.85*v.x,y:p.y+.85*v.y,a:p.heading,cycle:-1,lift:0,moving:false}})}
function stepBiped(dt,distance,turning){if(!bipedRig.feet.length)resetBiped();const moving=distance>.001||turning>.002;bipedRig.active=moving;if(!moving){for(const f of bipedRig.feet){f.moving=false;f.cycle=-1;f.lift=0}return}bipedRig.clock+=distance/BIPED_STRIDE+(!distance?turning/(Math.PI/4)*dt/1.1:0);for(const f of bipedRig.feet){const clock=bipedRig.clock+(f.side===1?.5:0),cycle=Math.floor(clock),phase=clock-cycle;if(phase<.28){if(f.cycle!==cycle){f.cycle=cycle;f.fx=f.x;f.fy=f.y;f.fa=f.a;f.startPhase=phase;const v=rotatePoint(f.side*60,distance>0?23:47,p.heading);const ahead=distance>0?BIPED_STRIDE*(.28-phase):0;f.tx=p.x+.85*v.x+Math.sin(p.heading)*ahead;f.ty=p.y+.85*v.y-Math.cos(p.heading)*ahead;f.ta=p.heading}const t=Math.max(0,Math.min(1,(phase-f.startPhase)/(.28-f.startPhase))),e=t*t*(3-2*t);f.x=f.fx+(f.tx-f.fx)*e;f.y=f.fy+(f.ty-f.fy)*e;const diff=Math.atan2(Math.sin(f.ta-f.fa),Math.cos(f.ta-f.fa));f.a=f.fa+diff*e;f.lift=Math.sin(Math.PI*t);f.moving=true}else{if(f.moving){f.x=f.tx;f.y=f.ty;f.a=f.ta}f.moving=false;f.lift=0}}}
function bipedSegment(c,id,a,b,width,colour){const dx=b.x-a.x,dy=b.y-a.y;c.save();c.translate((a.x+b.x)/2,(a.y+b.y)/2);c.rotate(Math.atan2(dx,-dy));sprite(c,id,0,0,width,Math.hypot(dx,dy)+8,false,colour);c.restore()}
function drawBiped(c,heading,rig,colour){const feet=rig?.feet.length?rig.feet.map(f=>({...f,x:(f.x-p.x)/.85,y:(f.y-p.y)/.85})): [-1,1].map(side=>({...rotatePoint(side*60,57,heading),side,a:heading,lift:0}));for(const f of feet){const hip=rotatePoint(f.side*35,0,heading),dx=f.x-hip.x,dy=f.y-hip.y,raw=Math.hypot(dx,dy),d=Math.max(9,Math.min(101,raw)),ux=dx/(raw||1),uy=dy/(raw||1),along=(45*45-57*57+d*d)/(2*d),height=Math.sqrt(Math.max(0,45*45-along*along)),out=rotatePoint(f.side,0,heading),sign=(-uy*out.x+ux*out.y)>0?1:-1,knee={x:hip.x+ux*along-uy*height*sign,y:hip.y+uy*along+ux*height*sign};c.save();c.fillStyle='#0007';c.beginPath();c.ellipse(f.x+3,f.y+4,24,18,f.a,0,Math.PI*2);c.fill();c.restore();bipedSegment(c,'biped-thigh',hip,knee,32,colour);bipedSegment(c,'biped-shin',knee,f,29,colour);for(const joint of [hip,knee]){c.save();c.translate(joint.x,joint.y);c.rotate(heading);sprite(c,'biped-knee',0,0,31,31,false,colour);c.restore()}c.save();c.translate(f.x,f.y);c.rotate(f.a);const size=1+.07*f.lift;sprite(c,'biped-foot',0,0,47*size,43*size,false,colour);c.restore()}}
