'use strict';
const BIPED_ASSETS=['biped-thigh','biped-shin','biped-knee','biped-foot'];
const BIPED_SPEED=160,BIPED_TURN=Math.PI/2,BIPED_STRIDE=210;
const bipedRig={feet:[],clock:0,active:false};
function rotatePoint(x,y,a){return{x:x*Math.cos(a)-y*Math.sin(a),y:x*Math.sin(a)+y*Math.cos(a)}}
// Feet use the forward gait in chassis space, so steering cannot pull them away.
function resetBiped(){bipedRig.clock=0;bipedRig.active=false;bipedRig.feet=[-1,1].map(side=>({side,localY:57,a:p.heading,cycle:-1,lift:0,moving:false}));placeBipedFeet()}
function placeBipedFeet(){for(const f of bipedRig.feet){const v=rotatePoint(f.side*60,f.localY,p.heading);f.x=p.x+.85*v.x;f.y=p.y+.85*v.y;f.a=p.heading}}
function moveBiped(dt,mx,my){const throttle=Math.min(1,Math.hypot(mx,my));if(throttle<=.08)return;const desired=Math.atan2(mx,-my),delta=Math.atan2(Math.sin(desired-p.heading),Math.cos(desired-p.heading)),turn=Math.max(-BIPED_TURN*throttle*dt,Math.min(BIPED_TURN*throttle*dt,delta)),heading=p.heading+turn,mid=p.heading+turn/2,travel=BIPED_SPEED*throttle*dt;const oldX=p.x,oldY=p.y;urbanMove(p,p.x+Math.sin(mid)*travel,p.y-Math.cos(mid)*travel);if(Math.hypot(p.x-oldX,p.y-oldY)>.001)p.heading=heading}
function stepBiped(dt,distance){if(!bipedRig.feet.length)resetBiped();const moving=distance>.001;bipedRig.active=moving;if(!moving){for(const f of bipedRig.feet){Sound.bipedSwing(f.side,false);f.moving=false;f.cycle=-1;f.lift=0}placeBipedFeet();return}bipedRig.clock+=distance/BIPED_STRIDE;for(const f of bipedRig.feet){const clock=bipedRig.clock+(f.side===1?.5:0),cycle=Math.floor(clock),phase=clock-cycle;if(phase<.28){if(f.cycle!==cycle){f.cycle=cycle;f.fromY=f.localY;f.startPhase=phase}const t=Math.max(0,Math.min(1,(phase-f.startPhase)/(.28-f.startPhase))),ease=t*t*(3-2*t);f.localY=f.fromY+(-85-f.fromY)*ease;f.lift=Math.sin(Math.PI*t);f.moving=true;Sound.bipedSwing(f.side,true,t)}else{if(f.moving)Sound.bipedLand(f.side);f.localY=-85+(phase-.28)*BIPED_STRIDE/.85;f.moving=false;f.lift=0}}placeBipedFeet()}
function bipedSegment(c,id,a,b,width,colour){const dx=b.x-a.x,dy=b.y-a.y;c.save();c.translate((a.x+b.x)/2,(a.y+b.y)/2);c.rotate(Math.atan2(dx,-dy));sprite(c,id,0,0,width,Math.hypot(dx,dy)+8,false,colour);c.restore()}
function drawBiped(c,heading,rig,colour){const feet=rig?.feet.length?rig.feet.map(f=>({...f,x:(f.x-p.x)/.85,y:(f.y-p.y)/.85})): [-1,1].map(side=>({...rotatePoint(side*60,57,heading),side,a:heading,lift:0}));for(const f of feet){const hip=rotatePoint(f.side*35,0,heading),dx=f.x-hip.x,dy=f.y-hip.y,raw=Math.hypot(dx,dy),d=Math.max(9,Math.min(101,raw)),ux=dx/(raw||1),uy=dy/(raw||1),along=(45*45-57*57+d*d)/(2*d),height=Math.sqrt(Math.max(0,45*45-along*along)),out=rotatePoint(f.side,0,heading),sign=(-uy*out.x+ux*out.y)>0?1:-1,knee={x:hip.x+ux*along-uy*height*sign,y:hip.y+uy*along+ux*height*sign};c.save();c.fillStyle='#0007';c.beginPath();c.ellipse(f.x+3,f.y+4,24,18,f.a,0,Math.PI*2);c.fill();c.restore();bipedSegment(c,'biped-thigh',hip,knee,32,colour);bipedSegment(c,'biped-shin',knee,f,29,colour);for(const joint of [hip,knee]){c.save();c.translate(joint.x,joint.y);c.rotate(heading);sprite(c,'biped-knee',0,0,31,31,false,colour);c.restore()}c.save();c.translate(f.x,f.y);c.rotate(f.a);const size=1+.07*f.lift;sprite(c,'biped-foot',0,0,47*size,43*size,false,colour);c.restore()}}
