'use strict';
// HTML-owned option lists rotate with Player Two; iPadOS never opens a native popup.
const buildPickers=[];
for(const id of ['colour','chassis','turret','left','right','rear','primaryMod','secondaryMod','supportMod']){const select=document.getElementById(id),button=document.createElement('button'),list=document.createElement('div');select.hidden=true;button.type='button';button.className='build-picker';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls',id+'-choices');list.id=id+'-choices';list.className='build-choices';list.hidden=true;list.setAttribute('role','group');const label=select.parentElement.firstChild?.textContent?.trim()||id;button.setAttribute('aria-label',label);list.setAttribute('aria-label',label+' choices');select.parentElement.appendChild(button);select.parentElement.appendChild(list);const picker={select,button,list};buildPickers.push(picker);button.onclick=e=>{e.preventDefault();for(const other of buildPickers)if(other!==picker){other.list.hidden=true;other.button.setAttribute('aria-expanded','false')}const open=list.hidden;syncPicker(picker,true);list.hidden=!open;button.setAttribute('aria-expanded',String(open))}}
function syncPicker(picker,choices=false){const {select,button,list}=picker;button.disabled=select.disabled;button.textContent=select.options[select.selectedIndex]?.textContent||'Choose…';if(!choices)return;list.replaceChildren();for(const option of Array.from(select.options)){const item=document.createElement('button');item.type='button';item.disabled=option.disabled;item.textContent=(option.value===select.value?'✓ ':'')+option.textContent;item.setAttribute('aria-pressed',String(option.value===select.value));item.onclick=e=>{e.preventDefault();if(option.disabled)return;select.value=option.value;list.hidden=true;button.setAttribute('aria-expanded','false');select.onchange?.();syncBuildPickers();button.focus()};list.appendChild(item)}}
function closeBuildPickers(){for(const picker of buildPickers){picker.list.hidden=true;picker.button.setAttribute('aria-expanded','false')}}
function syncBuildPickers(){for(const picker of buildPickers)syncPicker(picker,!picker.list.hidden)}
const originalBuildUpdate=update;update=function(){originalBuildUpdate();syncBuildPickers()};
document.getElementById('testLoadouts').onchange=e=>{testLoadouts=e.target.checked;try{localStorage.setItem('iron-pit-test-loadouts',String(testLoadouts))}catch(e){}updateProgressDisplay();update()};
updateProgressDisplay();syncBuildPickers();
