'use strict';
// Rookie League is independent of Quick Battle wins and the testing unlock toggle.
const ROOKIE_SAVE='iron-pit-rookie-v1';
const STORY_CAST={jim:{name:'Jim',role:'ROOKIE PILOT'},dave:{name:'Dave',role:'CHIEF MECHANIC'},rivet:{name:'Rivet',role:'SPONSORED RIVAL'},skitter:{name:'Skitter',role:'LIGHT BIPED PILOT'},bastion:{name:'Bastion',role:'HEAVY TANK PILOT'}};
const rookieLoadout=(chassis,left,right,rear,colour='red')=>({chassis,turret:'turret',left,right,rear,colour});
const ROOKIE_MATCHES=[
 {title:'First Blood',round:'QUALIFIER',arena:'desert',opponent:'Rivet',reward:'rotary',rewardText:'Championship entry · Rotary autocannon',brief:'Qualify for the championship. Keep moving between her rocket salvos.',bots:[{name:'RIVET',loadout:rookieLoadout('chassis','machine-gun','tri-salvo',''),ai:{reaction:1.05,burst:.65,turn:.7,standOff:620}}],lines:[['dave','Armour’s patched. Reactor’s stable. Escape pod works. Ideally, we only test the first two.'],['jim','Who am I fighting?'],['dave','Rivet. Sponsored team, Assault tank, plenty of confidence. Watch her rockets—move while she reloads.'],['rivet','Dave built that? Brave of you to sit in it.'],['dave','Right. Now you have to win.']],win:[['rivet','Enjoy that one, Jim. Next time, I’m bringing a better answer.'],['dave','Bring whatever you like. Just leave us the salvage.']]},
 {title:'Catch Me If You Can',round:'ROOKIE ROUND 1',arena:'snow',opponent:'Skitter',reward:'flak',rewardText:'Flak cannon',brief:'Cut off Skitter’s routes. Her mines make chasing dangerous.',bots:[{name:'SKITTER',loadout:rookieLoadout('biped-light','rotary','','mines'),ai:{reaction:.65,burst:.75,turn:.9,standOff:420,reposition:1.2}}],lines:[['dave','Don’t chase her around the arena. Cut her off—and watch what she leaves behind.'],['skitter','Try to keep up, Jim.']],win:[['skitter','Okay, you’re quicker than you look.'],['dave','Flak cannon unlocked. Something for the next big problem.']]},
 {title:'Heavy Metal',round:'ROOKIE ROUND 2',arena:'night',opponent:'Bastion',reward:'swarm',rewardText:'Swarm missiles',brief:'Use cover and flanking routes. Trading hits favours Bastion.',bots:[{name:'BASTION',loadout:rookieLoadout('tank-heavy','rotary','flak',''),ai:{reaction:.7,burst:1.05,turn:.85,standOff:620}}],lines:[['dave','Don’t trade shots with him. Use the forcefields, get around his turret, and move before he lines you up.'],['bastion','That little mech of yours looks expensive to repair.']],win:[['bastion','Not bad, rookie.'],['dave','Swarm missiles. Now you can make them work for their cover.']]},
 {title:'Three’s a Crowd',round:'ROOKIE SEMI-FINAL',arena:'conveyors',opponent:'Skitter + Bastion',reward:'pulse',rewardText:'Pulse lasers',brief:'Three mechs, all against all. Use the conveyor belts to reposition.',bots:[{name:'SKITTER',loadout:rookieLoadout('biped-light','rotary','','mines'),ai:{reaction:.6,burst:.75,turn:1,standOff:420,reposition:1.2}},{name:'BASTION',loadout:rookieLoadout('tank-heavy','rotary','flak',''),ai:{reaction:.65,burst:1.05,turn:.9,standOff:620}}],lines:[['dave','Let those two wear each other down, but don’t expect them to ignore you. And watch the belts.']],win:[['dave','Finals. And pulse lasers. I could get used to this.']]},
 {title:'The Rematch',round:'ROOKIE FINAL',arena:'desert',opponent:'Rivet',reward:'smart',rewardText:'Smart gun · Sponsorship · Rookie Champion',brief:'Rivet returns upgraded. Sandstorms obscure the whole stadium.',bots:[{name:'RIVET',loadout:rookieLoadout('chassis','rotary','flak','swarm'),ai:{reaction:.45,burst:1.05,turn:1,standOff:620}}],lines:[['rivet','You’ve beaten fast. You’ve beaten heavy. Now let’s see if you can beat me twice.'],['dave','She’s upgraded. So have you. When the sand rolls in, watch for headlights and muzzle flashes.']],win:[['rivet','All right, Jim. You earned it. See you in the next league.'],['dave','A sponsor? Finally. Someone else can pay for your explosions.']]}
];
function readRookieSave(){try{const v=JSON.parse(localStorage.getItem(ROOKIE_SAVE));return{completed:Math.max(0,Math.min(5,Math.floor(Number(v?.completed)||0))),build:v?.build||null,announced:Array.isArray(v?.announced)?v.announced:[],pending:Array.isArray(v?.pending)?v.pending:[],repairs:Number(v?.repairs)||0}}catch(e){return{completed:0,build:null}}}
let rookieProgress=readRookieSave(),campaignActive=false,campaignMission=0,campaignOutcome=null,campaignQuickBuild=null,campaignQuickArena=null;
const campaignBots=BOT_ACTORS.map(a=>({name:a.name,loadout:a.loadout,ai:a.ai}));
function saveRookie(){try{localStorage.setItem(ROOKIE_SAVE,JSON.stringify(rookieProgress))}catch(e){node('storySaveStatus').textContent='Saving unavailable on this device. Keep this session open.'}}
function campaignUnlocked(id){return !id||['machine-gun','tri-salvo','mines',...ROOKIE_MATCHES.slice(0,rookieProgress.completed).map(m=>m.reward)].includes(id)}
const campaignAvailability=weaponAvailable;
weaponAvailable=function(id,profile){return campaignActive?campaignUnlocked(id):campaignAvailability(id,profile)};
function storyScreen(){let el=node('storyScreen');if(el)return el;el=document.createElement('main');el.id='storyScreen';el.hidden=true;el.innerHTML='<header><div><small>IRON PIT / CHAMPIONSHIP</small><h1>ROOKIE LEAGUE</h1></div><button id="storyExit">BACK</button></header><div id="storyBody"></div><p id="storySaveStatus" role="status"></p>';document.body.appendChild(el);node('storyExit').onclick=exitCampaign;return el}
function hideGameMenus(){node('splash').hidden=true;node('startScreen').hidden=true;node('builder').style.display='none';node('arena').style.display='none';inArena=false;lockBattlePage(false);closeWorkshopWeapons();Sound.startMusic()}
function enterCampaign(){if(duelActive)leaveDuel();if(!campaignActive){campaignQuickBuild={build:{...build},mods:{...modifications}};campaignQuickArena=arenaKind}campaignActive=true;selectedMode='story';buildTurn=-1;campaignMission=Math.min(rookieProgress.completed,4);showRookieLadder()}
function exitCampaign(){Sound.stopAll();cancelDeployment();stopFiring();stopRepair();clearCombatFx();campaignActive=false;campaignOutcome=null;storyScreen().hidden=true;for(let i=0;i<BOT_ACTORS.length;i++)Object.assign(BOT_ACTORS[i],campaignBots[i]);if(campaignQuickBuild){build={...campaignQuickBuild.build};modifications={...campaignQuickBuild.mods};arenaKind=campaignQuickArena;campaignQuickBuild=null}selectedMode=null;saveWorkshopBuild();showLevelSelect();update()}
function showRookieLadder(){hideGameMenus();storyScreen().hidden=false;const body=node('storyBody');body.replaceChildren();const intro=document.createElement('div');intro.className='league-intro';intro.innerHTML='<img src="assets/story-jim.jpg" alt="Jim, your pilot"><div><small>JIM / CHAMPIONSHIP CAMPAIGN</small><h2></h2><p></p></div>';intro.querySelector('h2').textContent=rookieProgress.completed===5?'ROOKIE CHAMPION':'CLIMB TO THE FINAL';intro.querySelector('p').textContent=rookieProgress.completed===5?'Sponsorship secured. Replay any Rookie match. The Contender League is next.':'Start at the bottom. Win each match to climb the ladder and unlock new weapons.';body.appendChild(intro);const ladder=document.createElement('div');ladder.className='rookie-ladder';
 // DOM and visual order are both final → qualifier, so progress climbs upwards.
 for(let i=4;i>=0;i--){const m=ROOKIE_MATCHES[i],done=i<rookieProgress.completed,available=i<=rookieProgress.completed,b=document.createElement('button');b.className='league-match'+(i===rookieProgress.completed?' league-current':'');b.disabled=!available;b.dataset.mission=i;b.innerHTML='<span class="league-state"></span><div><small></small><strong></strong><p></p></div><span class="league-reward"></span>';b.querySelector('.league-state').textContent=done?'✓':available?'▶':'🔒';b.querySelector('small').textContent=m.round+' / '+ARENA_VARIANTS[m.arena].label;b.querySelector('strong').textContent=m.title.toUpperCase();b.querySelector('p').textContent=m.opponent;b.querySelector('.league-reward').textContent=m.rewardText;b.onclick=()=>{campaignMission=i;showStoryDialogue(m.lines,()=>prepareCampaignWorkshop(),m)};ladder.appendChild(b)}body.appendChild(ladder);node('storySaveStatus').textContent='PROGRESS SAVED ON THIS DEVICE · '+rookieProgress.completed+' / 5 VICTORIES';}
function showStoryDialogue(lines,done,mission=ROOKIE_MATCHES[campaignMission]){hideGameMenus();storyScreen().hidden=false;const body=node('storyBody');body.innerHTML='<div class="story-dialogue"><img id="storyPortrait" alt=""><div class="story-dialogue-copy"><small id="storyRole"></small><h2 id="storyName"></h2><p id="storyLine"></p><small id="storyPage"></small></div></div><div class="mission-brief"><small id="missionRound"></small><h2 id="missionTitle"></h2><p id="missionBrief"></p></div><div class="story-actions"><button id="storySkip">SKIP</button><button id="storyNext" class="primary">CONTINUE</button></div>';let page=0;const show=()=>{const [who,line]=lines[page],cast=STORY_CAST[who];node('storyPortrait').src='assets/story-'+who+'.jpg';node('storyPortrait').alt=cast.name;node('storyRole').textContent=cast.role;node('storyName').textContent=cast.name.toUpperCase();node('storyLine').textContent=line;node('storyPage').textContent=(page+1)+' / '+lines.length;node('storyNext').textContent=page===lines.length-1?'CONTINUE':'NEXT';};node('missionRound').textContent=mission.round+' / '+ARENA_VARIANTS[mission.arena].label;node('missionTitle').textContent=mission.title.toUpperCase();node('missionBrief').textContent=mission.brief;node('storySkip').onclick=done;node('storyNext').onclick=()=>{if(++page>=lines.length)done();else show()};show();}
function prepareCampaignWorkshop(){const m=ROOKIE_MATCHES[campaignMission];storyScreen().hidden=true;arenaKind=m.arena;setArenaMode('solo');selectedOpponents=m.bots.length;buildTurn=-1;selectedMode='story';node('builder').classList.remove('opposite-builder');const saved=rookieProgress.build;build={...rookieLoadout('tank-light','machine-gun','tri-salvo','mines','green'),...(saved||{})};if(!CHASSIS_IDS.includes(build.chassis)||campaignMission===0&&!['tank-light','biped-light'].includes(build.chassis))build.chassis='tank-light';build.colour=['green','red'].includes(build.colour)?build.colour:'green';build.turret='turret';for(const key of ['left','right','rear'])if(!campaignUnlocked(build[key])||!workshopSlots[key].ids.includes(build[key]))build[key]='';modifications={primary:'standard',secondary:'standard',support:'standard'};for(const key in build)if(node(key))node(key).value=build[key];node('builder').style.display='flex';node('buildVersion').textContent='ROOKIE LEAGUE · v45';node('buildBack').textContent='BACK TO LEAGUE';campaignOutcome=null;update();}
const campaignWorkshopRefresh=refreshWorkshop;
refreshWorkshop=function(){campaignWorkshopRefresh();if(!campaignActive)return;node('workshopMode').textContent='JIM / '+ROOKIE_MATCHES[campaignMission].round;node('deploy').textContent='DEPLOY · '+ROOKIE_MATCHES[campaignMission].title.toUpperCase();document.querySelectorAll('[data-chassis]').forEach(b=>{b.disabled=campaignMission===0&&!['tank-light','biped-light'].includes(b.dataset.chassis)});};
const campaignWeaponsOpen=openWorkshopWeapons;
openWorkshopWeapons=function(key){campaignWeaponsOpen(key);if(campaignActive)for(const card of node('weaponCarousel').children)if(card.disabled)card.querySelector('small').textContent='CAMPAIGN REWARD · LOCKED'};
const campaignBack=node('buildBack').onclick;
node('buildBack').onclick=()=>{if(campaignActive)showRookieLadder();else campaignBack()};
const campaignDeploy=node('deploy').onclick;
node('deploy').onclick=()=>{if(campaignActive){if(!ready)return;const m=ROOKIE_MATCHES[campaignMission];refreshWeaponAccess();if(campaignMission===0&&!['tank-light','biped-light'].includes(build.chassis))build.chassis='tank-light';rookieProgress.build={...build};saveRookie();arenaKind=m.arena;setArenaMode('solo');selectedOpponents=m.bots.length;for(let i=0;i<m.bots.length;i++){const b=m.bots[i];Object.assign(BOT_ACTORS[i],{name:b.name,loadout:{...b.loadout},ai:{...b.ai}})}campaignOutcome=null;}campaignDeploy()};
const campaignInitialise=initialiseProgressMatch;
initialiseProgressMatch=function(duel){campaignInitialise(duel);if(campaignActive){matchProgress.test=true;matchProgress.campaign=campaignMission;for(const a of enemies)a.reaction=a.ai?.reaction??.6;}};
const campaignFinish=finishBattle;
finishBattle=function(winner){const existed=!!battleResult;campaignFinish(winner);if(existed||!campaignActive||matchProgress?.campaign===undefined)return;const mission=matchProgress.campaign,won=winner===p,first=won&&mission===rookieProgress.completed;campaignOutcome={won,first,mission};if(first){rookieProgress.completed=Math.min(5,mission+1);saveRookie();}};
const campaignPanel=updateBattlePanel;
updateBattlePanel=function(){campaignPanel();if(campaignActive&&battleResult){node('return').textContent=campaignOutcome?.won?'CONTINUE':'WORKSHOP';if(campaignOutcome?.won)node('rematch').hidden=true;}};
const campaignReturn=node('return').onclick;
node('return').onclick=()=>{if(!campaignActive)return campaignReturn();if(!battleResult||battleResult.age<3||!currentPanel().classList.contains('panel-off'))return;cancelDeployment();stopFiring();Sound.stopAll();if(campaignOutcome?.won){const m=ROOKIE_MATCHES[campaignOutcome.mission];showStoryDialogue(m.win,showRookieLadder,{...m,brief:campaignOutcome.first?'UNLOCKED: '+m.rewardText:'MATCH WON · REPLAY COMPLETE'});}else showStoryDialogue([['dave','Pilot intact. Mech… less so. Let’s change the loadout and try again.']],prepareCampaignWorkshop);};
// Mission terminal: large real arena preview, carousel choices, explicit readiness.
const championshipButton=document.createElement('button');championshipButton.id='championshipStart';championshipButton.textContent='CHAMPIONSHIP · JIM’S STORY';championshipButton.onclick=enterCampaign;node('startScreen').insertBefore(championshipButton,node('startScreen').querySelector('h2'));
const splashCampaign=championshipButton.cloneNode(false);splashCampaign.id='splashCampaign';splashCampaign.textContent='CHAMPIONSHIP';splashCampaign.onclick=enterCampaign;node('splash').insertBefore(splashCampaign,node('splashStart'));node('splashStart').textContent='QUICK BATTLE';
const arenaHero=document.createElement('div');arenaHero.id='arenaHero';arenaHero.innerHTML='<button id="arenaPrevious" aria-label="Previous arena">◀</button><canvas id="arenaHeroCanvas" width="440" height="390"></canvas><div><small>ARENA / LIVE PREVIEW</small><h2 id="arenaHeroName">SELECT ARENA</h2><p id="arenaHeroDescription">Choose a stadium below.</p></div><button id="arenaNext" aria-label="Next arena">▶</button>';node('arenaCarousel').before(arenaHero);
const modes={'1':'DUEL / 1 VS 1','2':'THREE-MECH FREE FOR ALL','3':'FOUR-MECH FREE FOR ALL',duel:'TWO PLAYERS / SHARED IPAD',test:'WEAPON TEST ARENA'};
const modeButtons=Array.from(document.querySelectorAll('.mode-carousel [data-mode]'));for(const b of modeButtons)b.querySelector('span').textContent=modes[b.dataset.mode];
node('modeConfirm').textContent='CONFIRM → WORKSHOP';
function refreshArenaHero(){const chosen=selectedArena||Object.keys(ARENA_VARIANTS)[0],v=ARENA_VARIANTS[chosen];node('arenaHeroName').textContent=v.label.toUpperCase();node('arenaHeroDescription').textContent=v.description;if(ready){const source=document.querySelector('[data-arena="'+chosen+'"] canvas'),c=node('arenaHeroCanvas').getContext('2d');c.clearRect(0,0,440,390);c.drawImage(source,0,0,440,390)}node('levelStatus').textContent=selectedMode&&selectedArena?modes[selectedMode]+' / '+v.label.toUpperCase():'SELECT YOUR COMBAT MODE AND STADIUM'}
const campaignLevelRefresh=refreshLevelChoice;
refreshLevelChoice=function(){campaignLevelRefresh();refreshArenaHero();};
for(const[btn,dir]of [['arenaPrevious',-1],['arenaNext',1]])node(btn).onclick=()=>{const ids=Object.keys(ARENA_VARIANTS),i=ids.indexOf(selectedArena||ids[0]);selectedArena=ids[(i+dir+ids.length)%ids.length];refreshLevelChoice()};
const campaignLevelCards=drawLevelCards;
drawLevelCards=function(){campaignLevelCards();if(node('arenaHeroCanvas'))refreshArenaHero()};
// Keep paint selection coloured on the carousel, schematic green on assembly.
const paintRow=node('paintCycle').parentElement;paintRow.classList.add('paint-scheme-row');paintRow.firstChild.textContent='PAINT SCHEME';node('chassisCarousel').after(paintRow);
const campaignWorkshopUpdate=update;
update=function(){campaignWorkshopUpdate();const colour=build.colour==='red'?'#ab3c31':'#526c51';node('paintCycle').style.setProperty('--paint-swatch',colour);if(!campaignActive){document.querySelectorAll('[data-chassis]').forEach(b=>b.disabled=false);node('buildBack').textContent='BACK TO MISSION SELECT';}else node('loadoutReadout').textContent='ROOKIE LEAGUE · CAMPAIGN EQUIPMENT';};
storyScreen();refreshLevelChoice();update();
