'use strict';
const TURRET_LIGHTS=[[37,-61],[60,-36],[64,-11],[57,14]];
function drawTurretLamp(c,side,j,colour,strength){const [xx,y]=TURRET_LIGHTS[j],x=side*xx;c.shadowBlur=0;c.fillStyle='#111a1e';c.fillRect(x-3,y-5,6,10);c.fillStyle='#5c6869';c.fillRect(x-2.5,y-4.5,5,9);c.globalAlpha=strength;c.fillStyle=colour;c.shadowColor=colour;c.shadowBlur=9*strength;c.fillRect(x-1.5,y-3.5,3,7);c.globalAlpha=1}
const SLOT_LABELS={primary:'SLOT 1',secondary:'SLOT 2',support:'SLOT 3'};
let repairState=null,repairUses=2;
function resetRepair(){repairState=null;repairUses=2;updateDiagnostics()}
function beginRepair(){if(deployment||repairState||p.dead||p.ejecting||p.hp>=700||!repairUses)return;repairUses--;repairState={age:0,generation:p.generation};stopFiring();cancelPlayerLaunches();for(const id of ['primary','secondary','support'])$(id).disabled=true;updateDiagnostics()}
function stopRepair(){repairState=null;for(const id of ['primary','secondary','support'])$(id).disabled=!!deployment||p.dead;updateDiagnostics()}
function stepRepair(dt){if(!repairState)return;if(p.dead||p.ejecting||repairState.generation!==p.generation){stopRepair();return}const used=Math.min(dt,5-repairState.age);repairState.age+=used;p.hp=Math.min(700,p.hp+used*30);p.parts.hull=p.hp;if(repairState.age>=5)stopRepair()}
function updateDiagnostics(){const hp=Math.ceil(p.hp);$('hullReadout').textContent='HULL '+hp+' / 700';$('hullFill').style.width=p.hp/7+'%';$('repair').textContent=repairState?'REPAIR\n'+Math.round(repairState.age/5*100)+'%':'REPAIR\n'+repairUses+' LEFT';$('repair').disabled=!!deployment||!!repairState||!repairUses||p.dead||!!p.ejecting||p.hp>=700;$('componentReadout').textContent='MECH HEALTH '+Math.round(p.hp/7)+'%';currentPanel()?.classList.toggle('repairing',!!repairState);currentPanel()?.classList.toggle('self-destruct',!!p.ejecting&&!p.dead)}
function drawCockpitLights(c,actor,loadout){if(typeof inArena!=='undefined'&&!inArena)actor={hp:700};const eject=actor===p&&p.ejecting,repair=actor===p&&repairState,boot=actor===p&&deployment;if(boot)return drawDeploymentCockpit(c);const colour=eject?'#ff3024':repair?'#ffe047':loadout.colour==='red'?'#ffab42':'#45e7ef';const clock=eject?eject.age:repair?repair.age:0,intensity=eject?(Math.sin(clock*(12+clock*18))>0?1:.1):repair?.35+.65*(.5+.5*Math.sin(clock*6)):1;c.save();if(repair){c.globalAlpha=.3*intensity;c.fillStyle=colour;c.shadowColor=colour;c.shadowBlur=12;c.fillRect(-16,-28,32,58);c.globalAlpha=1}const pairs=Math.ceil(Math.max(0,actor.hp)/175),chase=Math.floor(clock*10)%8;for(let side=0;side<2;side++)for(let j=0;j<4;j++){const index=side?7-j:j;let on=eject||repair||j>=4-pairs,strength=eject?intensity:repair?(index===chase?1:.12):1;drawTurretLamp(c,side?1:-1,j,on?colour:'#354247',on?strength:1)}c.restore()}
document.getElementById('repair').onclick=beginRepair;
