'use strict';
const smokeClouds=[],wrecks=[],blastEvents=[],podFlights=[];let fxClock=0;const fragmentCache=new Map(),trackMotion={player:[0,0],enemy:[0,0]};
let trailSmokeImage=null;function softSmoke(c,x,y,r,alpha=.3){if(!trailSmokeImage){const cv=document.createElement('canvas');cv.width=cv.height=80;const cc=cv.getContext('2d'),g=cc.createRadialGradient(36,34,2,40,40,39);g.addColorStop(0,'#b8bfbaaa');g.addColorStop(.4,'#88939088');g.addColorStop(.75,'#65757335');g.addColorStop(1,'#52636100');cc.fillStyle=g;cc.fillRect(0,0,80,80);trailSmokeImage=cv}c.save();c.globalAlpha*=alpha;c.drawImage(trailSmokeImage,x-r,y-r,r*2,r*2);c.restore()}
function addSmokeCloud(x,y){smokeClouds.push({x,y,age:0,life:11,seed:Math.random()*20});if(smokeClouds.length>8)smokeClouds.shift()}
function smokeObscures(x,y,ex,ey){const dx=ex-x,dy=ey-y,d=dx*dx+dy*dy;return smokeClouds.some(s=>{if(s.age<.3||s.age>8.5)return false;const t=Math.max(0,Math.min(1,((s.x-x)*dx+(s.y-y)*dy)/(d||1)));return Math.hypot(x+t*dx-s.x,y+t*dy-s.y)<95+Math.min(160,s.age*18)})}
function drawSmokeClouds(c){if(!smokeClouds.length)return;smokeTexture(fxClock+4,true);for(const s of smokeClouds){const fade=Math.min(1,s.age/.35)*Math.min(1,(s.life-s.age)/4),size=380+s.age*32;c.save();c.translate(s.x+s.age*6,s.y-s.age*3);c.rotate(s.seed);c.globalAlpha=fade*.8;c.drawImage(smokeGreyCanvas,-size/2,-size*.45,size,size*.9);c.restore()}}

function drawBatonMine(c,m){const u=Math.min(1,m.age/m.flight),lift=m.armed>0?Math.sin(u*Math.PI)*16:0;c.save();c.translate(m.x+lift*.6,m.y+lift*.6);c.rotate(m.angle);c.fillStyle='#0006';c.beginPath();c.roundRect(-11,-4,22,8,3);c.fill();c.restore();c.save();c.translate(m.x,m.y);c.rotate(m.angle);c.scale(1+lift/100,1+lift/100);const g=c.createLinearGradient(0,-4,0,4);g.addColorStop(0,'#a6a694');g.addColorStop(.3,'#536357');g.addColorStop(.7,'#29352f');g.addColorStop(1,'#727c6a');c.fillStyle=g;c.beginPath();c.roundRect(-11,-4,22,8,3);c.fill();c.strokeStyle='#bab8a1';c.lineWidth=.8;c.stroke();c.fillStyle='#252d28';c.fillRect(-8,-4,2,8);c.fillRect(6,-4,2,8);c.fillStyle=m.armed>0?'#aab184':m.armFlash>0?'#e5ff90':'#ff583c';c.fillRect(-1.2,-1.5,2.4,3);if(m.armFlash>0)glow(c,0,0,18,'#dcff79',.5);c.restore()}
function stepTrackMotion(key,distance,turn){const phase=trackMotion[key]||(trackMotion[key]=[0,0]);phase[0]+=distance-turn*65;phase[1]+=distance+turn*65}
function drawTrackedChassis(c,id,colour,key){const profile=chassisProfile(id);id=profile.asset;sprite(c,id,0,30,profile.width,profile.height,false,colour);const im=colouredSprite(id,colour),phase=trackMotion[key];if(!im||!phase)return;const pods=profile.grade==='assault'?[[-73,70],[43,70]]:[[-66,180]];for(let side=0;side<2;side++)for(const[y0,height]of pods){const x=side===0?-profile.width*.46:profile.width*.33,width=profile.width*.13;c.save();c.beginPath();c.roundRect(x,y0,width,height,5);c.clip();const shift=((phase[side]%17)+17)%17;for(let y=y0-17+shift;y<y0+height;y+=17)c.drawImage(im,im.width*(side===0?.09:.79),im.height*.1,im.width*.12,im.height*.075,x,y,width,17);c.restore()}}
function croppedFragment(id,colour,w,h,clip){const key=[id,colour,w,h,JSON.stringify(clip)].join(':');if(fragmentCache.has(key))return fragmentCache.get(key);const cv=document.createElement('canvas');cv.width=Math.ceil(w);cv.height=Math.ceil(h);const ctx=cv.getContext('2d');if(clip){ctx.beginPath();clip.forEach(([u,v],i)=>i?ctx.lineTo(u*w,v*h):ctx.moveTo(u*w,v*h));ctx.closePath();ctx.clip()}ctx.drawImage(colouredSprite(id,colour),0,0,w,h);fragmentCache.set(key,cv);return cv}
function mechFragments(loadout,heading,angle){const pieces=[];function add(id,x,y,w,h,a,clip=null,flip=false){if(!id)return;const rotated=rotatePoint(x,y,a),worldAngle=a;pieces.push({image:croppedFragment(id,loadout.colour,w,h,clip),x:rotated.x*.85,y:rotated.y*.85,w:w*.85,h:h*.85,angle:worldAngle,flip,dir:Math.atan2(rotated.y,rotated.x)+(Math.random()-.5)*.6,dist:75+Math.random()*90,spin:(Math.random()-.5)*7,land:[.6,.98,1.42,1.85,2.35,2.85][pieces.length%6],landed:false})}
 if(isBiped(loadout)){for(const side of [-1,1]){add('biped-thigh',side*49,16,32,48,heading);add('biped-shin',side*62,47,29,55,heading);add('biped-foot',side*60,76,47,43,heading);add('biped-knee',side*61,29,31,31,heading)}}else{for(const clip of [[[0,0],[.3,0],[.3,1],[0,1]],[[.7,0],[1,0],[1,1],[.7,1]],[[.3,0],[.7,0],[.7,1],[.3,1]]])add(chassisProfile(loadout).asset,0,30,chassisProfile(loadout).width,chassisProfile(loadout).height,heading,clip)}
 for(const clip of [[[0,0],[.37,0],[.4,1],[0,1]],[[.37,0],[.64,0],[.61,1],[.4,1]],[[.64,0],[1,0],[1,1],[.61,1]]])add(loadout.turret,0,-12,151,184,angle,clip);for(const[slot,id]of [['primary',loadout.left],['secondary',loadout.right],['support',loadout.rear]]){const m=weaponMount(slot,id);add(id,m.x,m.y,m.w,m.h,angle,null,m.flip)}return pieces}
function destroyMech(x,y,heading,angle,loadout){crowdDestroyReaction();wrecks.push({x,y,age:0,life:16,pieces:mechFragments(loadout,heading,angle)});blastEvents.push({x,y,age:0,nuke:false});Sound.play('mech-explosion',x,y,1.2,1,true);addMark(x,y,80);if(wrecks.length>5)wrecks.shift()}
function damagePlayer(amount){if(p.dead||p.ejecting)return;if(p.shield>0){p.energy=Math.max(0,p.energy-amount*.2);if(p.energy===0)p.shield=0;return}p.hp=Math.max(0,p.hp-amount);if(p.parts)p.parts.hull=p.hp;if(amount>0&&p.hp>0)crowdHitReaction();if(p.hp<=0){p.dead=true;stopFiring();cancelPlayerLaunches();destroyMech(p.x,p.y,p.heading,p.angle,build)}}
function beginEject(){if(deployment||p.dead||p.ejecting)return;stopRepair();p.ejecting={age:0,x:p.x,y:p.y,heading:p.heading,angle:p.angle,detonated:false};p.shield=0;input.move={x:0,y:0};stopFiring();cancelPlayerLaunches();podFlights.push({x:p.x,y:p.y,a:p.angle,age:0,colour:build.colour});Sound.play('eject-jet',p.x,p.y,1,1,true);Sound.play('eject-siren',p.x,p.y,.85,1,true)}
function detonateEject(){const e=p.ejecting;if(!e||e.detonated)return;e.detonated=true;crowdDestroyReaction();urbanNuke(e.x,e.y);p.dead=true;blastEvents.push({x:e.x,y:e.y,age:0,nuke:true});Sound.play('nuke-explosion',e.x,e.y,1.3,1,true);addMark(e.x,e.y,140);for(const t of targets)if(Math.hypot(t.x-e.x,t.y-e.y)<480)t.shield=false;for(const actor of enemies)if(actor.alive){const d=Math.hypot(actor.x-e.x,actor.y-e.y);if(d<480)enemyHit('emp',{damage:1800*(1-d/480),penetration:1},1,true,'hull',actor)}}
function stepCombatFx(dt){fxClock+=dt;for(const a of [smokeClouds,wrecks,blastEvents,podFlights])for(let i=a.length-1;i>=0;i--){a[i].age+=dt;const life=a===blastEvents?9:a===podFlights?1.6:a[i].life;if(a[i].age>life)a.splice(i,1)}for(const w of wrecks)for(let i=0;i<w.pieces.length;i++){const f=w.pieces[i];if(!f.landed&&w.age>=f.land){f.landed=true;Sound.play('debris-'+i%3,w.x+f.x+Math.cos(f.dir)*f.dist,w.y+f.y+Math.sin(f.dir)*f.dist,.35,1+(i%5-2)*.06,true)}}for(const actor of [p,...enemies])if((actor===p||actor.human)&&actor.ejecting&&!actor.dead){actor.ejecting.age+=dt;if(actor.ejecting.age>=3.12){if(actor.human)withDuelPlayer(actor.duelIndex,detonateEject);else detonateEject()}}}
function clearCombatFx(){for(const r of rounds)if(r.soundKey)Sound.stopLoop(r.soundKey);for(const m of mines)if(m.soundKey)Sound.stopLoop(m.soundKey);smokeClouds.length=0;wrecks.length=0;blastEvents.length=0;podFlights.length=0;cancelLaunches();clearAdvancedWeapons();rounds.length=0;mines.length=0;particles.length=0;lines.length=0;flashes.length=0;marks.length=0;p.ejecting=null;p.dead=false;p.hp=700;p.generation++}
function drawCockpitBay(c){const age=p.ejecting.age;if(age>=3.03)return;c.save();c.translate(0,-2);let g=c.createLinearGradient(-29,-48,30,48);g.addColorStop(0,'#b7b2a2');g.addColorStop(.25,'#535b5b');g.addColorStop(.6,'#c4ba9f');g.addColorStop(1,'#484d48');c.fillStyle=g;c.beginPath();c.moveTo(-20,-48);c.lineTo(20,-48);c.lineTo(30,-24);c.lineTo(28,26);c.lineTo(16,48);c.lineTo(-16,48);c.lineTo(-28,26);c.lineTo(-30,-24);c.closePath();c.fill();g=c.createLinearGradient(-22,0,22,0);g.addColorStop(0,'#151e24');g.addColorStop(.4,'#455157');g.addColorStop(1,'#111b21');c.fillStyle=g;c.beginPath();c.roundRect(-22,-41,44,82,10);c.fill();for(let y=-32;y<35;y+=8){c.strokeStyle='#839294';c.lineWidth=1.3;c.beginPath();c.moveTo(-14,y);c.lineTo(14,y);c.stroke()}for(const side of [-1,1]){c.fillStyle='#89918a';c.fillRect(side*17-2,-31,4,60);c.fillStyle='#d0c8b5';c.fillRect(side*17-1,-29,1.4,57);c.strokeStyle='#775b3a';c.lineWidth=2;c.beginPath();c.moveTo(side*21,-27);c.bezierCurveTo(side*9,-15,side*27,8,side*15,28);c.stroke();for(const y of [-35,0,34]){c.fillStyle='#b9b5a2';c.beginPath();c.arc(side*24,y,1.5,0,7);c.fill()}}c.fillStyle='#242b2a';c.fillRect(-9,-9,18,23);c.strokeStyle='#8a9490';c.strokeRect(-9,-9,18,23);const alarm=Math.sin(age*(12+age*18))>0?1:.1;c.save();c.globalCompositeOperation='screen';glow(c,0,0,54,'#ff1208',alarm*.7);c.restore();for(const side of [-1,1])for(const y of [-24,15]){c.shadowColor='#ff0000';c.shadowBlur=23*alarm;c.fillStyle=`rgba(255,18,12,${alarm})`;c.fillRect(side*23-3,y,6,12);c.fillStyle=`rgba(255,180,165,${alarm})`;c.fillRect(side*23-1,y+2,2,8)}c.restore()}
function drawPods(c){for(const f of podFlights){const e=f.age,dist=380*e+520*e*e,x=f.x+Math.sin(f.a)*dist,y=f.y-Math.cos(f.a)*dist;c.save();c.translate(x,y);c.rotate(f.a);c.scale(.85*(1+Math.min(.45,e*.6)),.85*(1+Math.min(.45,e*.6)));if(e<.7){const g=c.createLinearGradient(0,20,0,145);g.addColorStop(0,'#fff');g.addColorStop(.2,'#d9ffff');g.addColorStop(.4,'#35c8ffe0');g.addColorStop(1,'#00baff00');c.fillStyle=g;c.beginPath();c.moveTo(-10,24);c.lineTo(0,145);c.lineTo(10,24);c.fill()}const im=colouredSprite('turret',f.colour);c.shadowColor='#54dcff';c.shadowBlur=12;c.drawImage(im,im.width*.32,im.height*.34,im.width*.36,im.height*.51,-28.5,-47.5,57,95);c.restore();if(e<.8)softSmoke(c,f.x+Math.sin(f.a)*e*50,f.y-Math.cos(f.a)*e*50,15+e*30,.25*(1-e/.8))}}
function drawCombatFx(c){for(const w of wrecks){c.save();c.translate(w.x,w.y);c.fillStyle='#0a0909';c.beginPath();c.ellipse(0,15,80,65,0,0,7);c.fill();for(const f of w.pieces){const u=Math.min(1,w.age/f.land),ease=1-(1-u)**2,x=f.x+Math.cos(f.dir)*f.dist*ease,y=f.y+Math.sin(f.dir)*f.dist*ease,lift=u<1?Math.sin(u*Math.PI)*18:0;c.save();c.translate(x,y);c.rotate(f.angle+f.spin*ease);if(f.flip)c.scale(-1,1);c.shadowColor='#000a';c.shadowBlur=6;c.shadowOffsetY=7+lift;c.scale(1+lift/100,1+lift/100);c.filter='brightness(.6)';c.drawImage(f.image,-f.w/2,-f.h/2,f.w,f.h);c.restore()}for(let k=0;k<6;k++)glow(c,Math.sin(k*4)*30,15+Math.cos(k*8)*25,10+5*Math.sin(fxClock*12+k),'#ff7825',Math.min(1,(w.life-w.age)/4)*.7);softSmoke(c,0,-w.age*3,40+w.age*4,.32);c.restore()}
 for(const slot in flameStreams){const f=flameStreams[slot],range=f.range,atlas=perimeterTexture(),frame=Math.floor(fxClock*24)%16;c.save();c.translate(f.x,f.y);c.rotate(f.a-Math.PI/2);c.globalCompositeOperation='screen';c.drawImage(atlas,frame%4*256,Math.floor(frame/4)*128,256,128,0,-range*.26,range,range*.52);c.restore();const ex=f.x+Math.sin(f.a)*range,ey=f.y-Math.cos(f.a)*range;softSmoke(c,ex,ey,55,.28)}drawPods(c)}
function drawBlastOverlay(c){const events=[...blastEvents];for(const actor of [p,...enemies])if((actor===p||actor.human)&&actor.ejecting&&!actor.dead&&actor.ejecting.age>=3)events.push({x:actor.ejecting.x,y:actor.ejecting.y,age:actor.ejecting.age-3,white:true});for(const e of events){if(e.nuke){drawNuclearCloud(c,e);continue}c.save();c.translate(e.x,e.y);const t=e.age;if(e.white){const u=Math.min(1,t/.12),wave=u<.38?Math.sin(u/.38*Math.PI/2):Math.max(0,Math.cos((u-.38)/.62*Math.PI/2)),r=8+wave*1300;c.globalCompositeOperation='screen';glow(c,0,0,1800,'#eaf6ff',wave*.9);const g=c.createRadialGradient(0,0,0,0,0,r);g.addColorStop(0,'#fff');g.addColorStop(.65,'#fff');g.addColorStop(.84,'#e7f7fff8');g.addColorStop(1,'#d9eeff00');c.fillStyle=g;c.fillRect(-r,-r,r*2,r*2);c.restore();continue}
 const duration=e.nuke?1.8:1.35;c.globalCompositeOperation='screen';if(t<1.15){c.strokeStyle=`rgba(255,205,127,${.8*(1-t/1.15)})`;c.lineWidth=14*(1-t/1.15)+2;c.beginPath();c.arc(0,0,18+(e.nuke?420:310)*t,0,7);c.stroke()}if(t<duration){const growth=Math.min(1,t/.22),fade=1-t/duration;glow(c,0,0,335,'#ffbf66',Math.exp(-t*2.5));for(let k=0;k<13;k++){const a=k*2.399,spread=(k===0?0:35+(k%4)*21)*growth,px=Math.cos(a)*spread,py=Math.sin(a)*spread,r=((e.nuke?88:62)+(k%3)*18)*growth*(1+t*.23)+2,g=c.createRadialGradient(px-r*.18,py-r*.2,1,px,py,r);g.addColorStop(0,`rgba(255,255,230,${fade})`);g.addColorStop(.3,`rgba(255,225,111,${fade})`);g.addColorStop(.65,`rgba(255,108,12,${fade*.9})`);g.addColorStop(1,'#78200000');c.fillStyle=g;c.fillRect(px-r,py-r,r*2,r*2)}}c.globalCompositeOperation='source-over';if(t>.45)for(let k=0;k<(e.nuke?20:14);k++){const age=t-.45-k*.085;if(age<0||age>4)continue;softSmoke(c,Math.sin(k*7)*(25+age*10),Math.cos(k*6)*24-age*8,25+age*25,.4*(1-age/4))}c.restore()}}
function drawCombatLights(c){c.save();c.globalCompositeOperation='screen';for(const f of Object.values(flameStreams)){glow(c,f.x,f.y,100,'#ff9d32',.28);glow(c,f.x+Math.sin(f.a)*f.range*.7,f.y-Math.cos(f.a)*f.range*.7,150,'#ff8928',.28)}for(const e of blastEvents)if(e.age<1.5)glow(c,e.x,e.y,e.nuke?1400:340,'#ffc575',.8*Math.exp(-e.age*2.5));c.restore()}
