'use strict';
const PART_MAX={hull:700,turret:320,leftTrack:200,rightTrack:200,left:170,right:170,rear:200};
const PART_LABEL={hull:'Hull',turret:'Turret',leftTrack:'Left track',rightTrack:'Right track',left:'Primary',right:'Secondary',rear:'Support'};
function resetParts(actor=enemy){actor.parts={...PART_MAX};actor.hp=PART_MAX.hull;actor.lastPart='';actor.partSmoke=0}
resetParts();
const alphaMasks={};
function prepareHitMasks(){if(!document.createElement)return;for(const id of ['chassis','turret',...side.map(v=>v[0]),...rear.map(v=>v[0]),...BIPED_ASSETS]){const im=images[id],c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);alphaMasks[id]={w:im.width,h:im.height,data:ctx.getImageData(0,0,im.width,im.height).data}}}
function enemyShapes(actor=enemy){const enemy=actor,enemyLoadout=actorLoadout(actor);const shapes=[['left','primary',enemyLoadout.left],['right','secondary',enemyLoadout.right],['rear','support',enemyLoadout.rear]].map(([part,slot,id])=>({part,...weaponMount(slot,id),a:enemy.angle,id}));const upper=[...shapes,{part:'turret',x:0,y:-12,w:151,h:184,a:enemy.angle,id:'turret'}];if(enemyLoadout.chassis==='biped'){const legs=[];for(const side of [-1,1]){const foot=actor===p?bipedRig.feet.find(f=>f.side===side):null;const f=foot?{...rotatePoint((foot.x-actor.x)/.85,(foot.y-actor.y)/.85,-actor.heading),lift:foot.lift}:{x:side*60,y:57,lift:0},hip={x:side*35,y:0},dx=f.x-hip.x,dy=f.y-hip.y,raw=Math.hypot(dx,dy),d=Math.max(9,Math.min(101,raw)),ux=dx/(raw||1),uy=dy/(raw||1),along=(45*45-57*57+d*d)/(2*d),height=Math.sqrt(Math.max(0,45*45-along*along)),sign=-uy*side>0?1:-1,knee={x:hip.x+ux*along-uy*height*sign,y:hip.y+uy*along+ux*height*sign},part=side<0?'leftTrack':'rightTrack';for(const [id,a,b,w]of [['biped-thigh',hip,knee,32],['biped-shin',knee,f,29]]){const centre=rotatePoint((a.x+b.x)/2,(a.y+b.y)/2,actor.heading);legs.push({part,id,x:0,y:0,w,h:Math.hypot(b.x-a.x,b.y-a.y)+8,a:actor.heading+Math.atan2(b.x-a.x,-(b.y-a.y)),centre})}for(const point of [hip,knee,f]){legs.push({part,id:point===f?'biped-foot':'biped-knee',x:point.x,y:point.y,w:point===f?47*(1+.07*f.lift):31,h:point===f?43*(1+.07*f.lift):31,a:actor.heading})}}return [...upper,...legs]}return [...shapes,
 {part:'turret',x:0,y:-12,w:151,h:184,a:enemy.angle,id:'turret'},
 {part:'leftTrack',x:-82.5,y:30,w:60,h:212.5,a:enemy.heading,base:true},
 {part:'rightTrack',x:82.5,y:30,w:60,h:212.5,a:enemy.heading,base:true},
 {part:'hull',x:0,y:30,w:225,h:212.5,a:enemy.heading,id:'chassis'}
]}
function partLocal(x,y,s,enemyActor=enemy){const enemy=enemyActor;const dx=(x-enemy.x)/.85-(s.centre?.x||0),dy=(y-enemy.y)/.85-(s.centre?.y||0);return{x:dx*Math.cos(s.a)+dy*Math.sin(s.a),y:-dx*Math.sin(s.a)+dy*Math.cos(s.a)}}
function enemyPartAt(x,y,actor=enemy){const enemy=actor;if(!aliveActor(actor)||Math.hypot(x-enemy.x,y-enemy.y)>190)return null;for(const s of enemyShapes(actor)){if(!s.id&&!s.base)continue;const v=partLocal(x,y,s,actor);if(Math.abs(v.x-s.x)>s.w/2||Math.abs(v.y-s.y)>s.h/2)continue;const mask=alphaMasks[s.base?'chassis':s.id];if(mask){let u=s.base?(v.x+112.5)/225:(v.x-s.x+s.w/2)/s.w,z=s.base?(v.y-30+106.25)/212.5:(v.y-s.y+s.h/2)/s.h;if(s.flip)u=1-u;const ix=Math.max(0,Math.min(mask.w-1,Math.floor(u*mask.w))),iy=Math.max(0,Math.min(mask.h-1,Math.floor(z*mask.h)));if(mask.data[(iy*mask.w+ix)*4+3]<32)continue}return s.part}return null}
function componentDistance(x,y,s,actor=enemy){const v=partLocal(x,y,s,actor);return Math.hypot(Math.max(0,Math.abs(v.x-s.x)-s.w/2),Math.max(0,Math.abs(v.y-s.y)-s.h/2))*.85}
function componentImpact(id,x,y,stats,hit){for(const actor of [p,...enemies]){if(!aliveActor(actor)||actor===hit?.owner)continue;const direct=hit?.target===actor?hit.part:(!hit?.environment?enemyPartAt(x,y,actor):null);if(direct){if(actor===p?p.shield>0:actor.shield){absorbShield(actor,stats.damage);continue}enemyHit(id,stats,1,false,direct,actor)}if(stats.blast)for(const s of enemyShapes(actor)){if(!aliveActor(actor))break;if(s.part===direct||actor.parts[s.part]<=0)continue;const d=componentDistance(x,y,s,actor);if(d<stats.blast){if(actor===p?p.shield>0:actor.shield){absorbShield(actor,stats.damage*.45*(1-d/stats.blast));break}enemyHit(id,stats,.45*(1-d/stats.blast),false,s.part,actor)}}}}
function absorbShield(actor,damage){actor.energy=Math.max(0,actor.energy-damage*.2);if(actor.energy<=0){if(actor===p)actor.shield=0;else actor.shield=false}}
function brokenSprite(c,id,x,y,w,h,flip,health,colour){c.save();if(health===0)c.filter='grayscale(1) brightness(.25)';sprite(c,id,x,y,w,h,flip,colour);c.restore()}
function drawPartStatus(c){if(!enemy.alive)return;let x=enemy.x-110,y=enemy.y+130;c.font='10px system-ui';for(const key of ['left','right','rear','leftTrack','rightTrack','turret']){c.fillStyle=enemy.parts[key]<=0?'#ff8877':'#bac9b0';c.fillText(PART_LABEL[key]+': '+Math.ceil(enemy.parts[key]),x,y);y+=13}if(enemy.lastPart){c.fillStyle='#ffce8b';c.fillText('HIT: '+PART_LABEL[enemy.lastPart],enemy.x-50,enemy.y-140)}}
