'use strict';
const PART_MAX={hull:700,turret:320,leftTrack:200,rightTrack:200,left:170,right:170,rear:200};
const PART_LABEL={hull:'Hull',turret:'Turret',leftTrack:'Left track',rightTrack:'Right track',left:'Slot 1',right:'Slot 2',rear:'Slot 3'};
function resetParts(actor=enemy){actor.parts={...PART_MAX};actor.hp=PART_MAX.hull;actor.lastPart='';actor.partSmoke=0}
resetParts();
const alphaMasks={};
function prepareHitMasks(){if(!document.createElement)return;for(const id of ['chassis','turret',...side.map(v=>v[0]),...rear.map(v=>v[0]),...BIPED_ASSETS,...CHASSIS_ASSETS]){const im=images[id],c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);alphaMasks[id]={w:im.width,h:im.height,data:ctx.getImageData(0,0,im.width,im.height).data}}}
function enemyShapes(actor=enemy){const enemy=actor,enemyLoadout=actorLoadout(actor);const shapes=[['left','primary',enemyLoadout.left],['right','secondary',enemyLoadout.right],['rear','support',enemyLoadout.rear]].map(([part,slot,id])=>({part,...weaponMount(slot,id),a:enemy.angle,id}));const upper=[...shapes,{part:'turret',x:0,y:-12,w:151,h:184,a:enemy.angle,id:'turret'}];if(isBiped(enemyLoadout)){const profile=chassisProfile(enemyLoadout),legs=[{part:'hull',id:bipedAsset('biped-hip',enemyLoadout),x:0,y:8,w:90,h:78,a:enemy.heading}];for(const side of [-1,1]){const foot=actor.human?actor.rig.feet.find(f=>f.side===side):actor===p?bipedRig.feet.find(f=>f.side===side):null;const f=foot?{...rotatePoint((foot.x-actor.x)/.85,(foot.y-actor.y)/.85,-actor.heading),lift:foot.lift}:{x:side*60,y:57,lift:0},hip={x:side*35,y:0},dx=f.x-hip.x,dy=f.y-hip.y,raw=Math.hypot(dx,dy),d=Math.max(9,Math.min(101,raw)),ux=dx/(raw||1),uy=dy/(raw||1),along=(45*45-57*57+d*d)/(2*d),height=Math.sqrt(Math.max(0,45*45-along*along)),sign=-uy*side>0?1:-1,knee={x:hip.x+ux*along-uy*height*sign,y:hip.y+uy*along+ux*height*sign},part=side<0?'leftTrack':'rightTrack';for(const [id,a,b,w]of [['biped-thigh',hip,knee,32],['biped-shin',knee,f,29]]){const centre=rotatePoint((a.x+b.x)/2,(a.y+b.y)/2,actor.heading);legs.push({part,id:bipedAsset(id,enemyLoadout),x:0,y:0,w:w*profile.partWidth,h:Math.hypot(b.x-a.x,b.y-a.y)+8,a:actor.heading+Math.atan2(b.x-a.x,-(b.y-a.y)),centre})}for(const point of [hip,knee,f]){legs.push({part,id:bipedAsset(point===f?'biped-foot':'biped-knee',enemyLoadout),x:point.x,y:point.y,w:point===f?47*profile.footWidth*(1+.07*f.lift):31*profile.partWidth,h:point===f?43*(1+.07*f.lift):31,a:actor.heading})}}return [...upper,...legs]}const profile=chassisProfile(enemyLoadout);return [...upper,{part:'hull',x:0,y:30,w:profile.width,h:profile.height,a:enemy.heading,id:profile.asset}]
}
function partLocal(x,y,s,enemyActor=enemy){const enemy=enemyActor;const dx=(x-enemy.x)/.85-(s.centre?.x||0),dy=(y-enemy.y)/.85-(s.centre?.y||0);return{x:dx*Math.cos(s.a)+dy*Math.sin(s.a),y:-dx*Math.sin(s.a)+dy*Math.cos(s.a)}}
function enemyPartAt(x,y,actor=enemy){const enemy=actor;if(!aliveActor(actor)||Math.hypot(x-enemy.x,y-enemy.y)>190)return null;for(const s of enemyShapes(actor)){if(!s.id&&!s.base)continue;const v=partLocal(x,y,s,actor);if(Math.abs(v.x-s.x)>s.w/2||Math.abs(v.y-s.y)>s.h/2)continue;const mask=alphaMasks[s.base?'chassis':s.id];if(mask){let u=s.base?(v.x+112.5)/225:(v.x-s.x+s.w/2)/s.w,z=s.base?(v.y-30+106.25)/212.5:(v.y-s.y+s.h/2)/s.h;if(s.flip)u=1-u;const ix=Math.max(0,Math.min(mask.w-1,Math.floor(u*mask.w))),iy=Math.max(0,Math.min(mask.h-1,Math.floor(z*mask.h)));if(mask.data[(iy*mask.w+ix)*4+3]<32)continue}return s.part}return null}
function componentDistance(x,y,s,actor=enemy){const v=partLocal(x,y,s,actor);return Math.hypot(Math.max(0,Math.abs(v.x-s.x)-s.w/2),Math.max(0,Math.abs(v.y-s.y)-s.h/2))*.85}
function componentImpact(id,x,y,stats,hit){for(const actor of [p,...enemies]){if(!aliveActor(actor)||actor===hit?.owner)continue;const direct=hit?.target===actor||(!hit?.environment&&enemyPartAt(x,y,actor));let factor=direct?1:0;if(!direct&&stats.blast){const d=Math.min(...enemyShapes(actor).filter(s=>s.id||s.base).map(s=>componentDistance(x,y,s,actor)));if(d<stats.blast)factor=.45*(1-d/stats.blast)}if(factor){if(shielded(actor))absorbShield(actor,stats.damage*factor);else enemyHit(id,stats,factor,false,'hull',actor)}}}
function absorbShield(actor,damage){actor.energy=Math.max(0,actor.energy-damage*.2);if(actor.energy<=0){if(actor===p)actor.shield=0;else actor.shield=false}}
function brokenSprite(c,id,x,y,w,h,flip,health,colour){c.save();sprite(c,id,x,y,w,h,flip,colour);c.restore()}
function drawPartStatus(){}
