'use strict';
let combatMetrics=new Map(),combatShotSerial=0,damageSource=null;
function newCombatMetrics(){return{elapsed:0,fired:0,hits:new Set(),dealt:0,received:0,kills:0,use:{},active:{},record:null}}
function metricFor(a){if(!combatMetrics.has(a))combatMetrics.set(a,newCombatMetrics());return combatMetrics.get(a)}
const metricInit=initialiseProgressMatch;initialiseProgressMatch=function(duel){combatMetrics=new Map();for(const a of [p,...enemies])metricFor(a);metricInit(duel);for(const id of ['p1-panel','p2-panel']){const panel=node(id);panel?.classList.remove('report-visible');panel?.querySelector('.after-action')?.remove()}};
function recordUse(a,id,rate=.1){const m=metricFor(a);m.active[id]=Math.max(m.active[id]||0,m.elapsed+Math.min(.2,Math.max(.07,rate)))}
function registerRounds(){for(const r of rounds){if(r.stats._shot)continue;const owner=r.owner;if(!owner)continue;r.stats={...r.stats,_shot:++combatShotSerial,_owner:owner};metricFor(owner).fired++;recordUse(owner,r.id==='cluster-child'?'mortar':r.id,weaponStats(r.id).rate)}}
const metricLaunch=launchPort;launchPort=function(id,offset,index,stats,target,slot){const a=activeShooter||p;metricLaunch(id,offset,index,stats,target,slot);registerRounds();if(GUNS[id].continuous||['beam','arc','flame'].includes(GUNS[id].kind))recordUse(a,id,stats.rate)};
const metricMine=launchMine;launchMine=function(id,offset,index,stats){const a=activeShooter||p;metricMine(id,offset,index,{...stats,_owner:a});recordUse(a,id,.1)};
const metricAdvanced=stepAdvancedWeapons;stepAdvancedWeapons=function(dt){metricAdvanced(dt);registerRounds()};
const metricImpact=impact;impact=function(id,x,y,shield,stats,hit){const before=damageSource;damageSource=hit?.owner||stats?._owner||null;if(hit?.target&&damageSource&&hit.target!==damageSource&&stats?._shot)metricFor(damageSource).hits.add(stats._shot);try{return metricImpact(id,x,y,shield,stats,hit)}finally{damageSource=before}};
const metricHit=enemyHit;enemyHit=function(id,stats,falloff,tick,part,actor=enemy){const before=actor.hp,source=damageSource||(tick&&id==='flame'?actor.burnOwner:null)||stats?._owner;metricHit(id,stats,falloff,tick,part,actor);const amount=Math.max(0,before-actor.hp);if(amount){metricFor(actor).received+=amount;if(source&&source!==actor){metricFor(source).dealt+=amount;if(actor.hp<=0&&before>0)metricFor(source).kills++;if(id==='flame'&&!tick)actor.burnOwner=source}}};
const metricPlayer=damagePlayer;damagePlayer=function(amount){const before=p.hp;metricPlayer(amount);metricFor(p).received+=Math.max(0,before-p.hp)};
const metricNuke=detonateEject;detonateEject=function(){const old=damageSource;damageSource=p;try{metricNuke()}finally{damageSource=old}};
const metricStep=stepWeapons;stepWeapons=function(dt){if(!battleFinished()&&!deployment){for(const a of [p,...enemies]){const m=metricFor(a);if(aliveActor(a)){m.elapsed+=dt;for(const[id,until]of Object.entries(m.active))if(until>=m.elapsed)m.use[id]=(m.use[id]||0)+dt}}}metricStep(dt)};
function battleReport(a){const m=metricFor(a);if(m.record)return m.record;const favourite=Object.entries(m.use).sort((x,y)=>y[1]-x[1])[0]?.[0]||null;return m.record={accuracy:m.fired?Math.min(100,Math.round(m.hits.size/m.fired*100)):null,dealt:Math.round(m.dealt),received:Math.round(m.received),kills:m.kills,duration:m.elapsed,health:Math.max(0,Math.round(a.hp)),favourite};}
const reportFinish=finishBattle;finishBattle=function(winner){const was=!!battleResult;reportFinish(winner);if(!was)for(const a of [p,...enemies])battleReport(a)};
function showBattleReport(panel,a){if(panel.querySelector('.after-action'))return;const r=battleReport(a),won=battleResult.winner===a,el=document.createElement('div');el.className='after-action';el.innerHTML='<div class="report-header"><strong></strong><small>AFTER-ACTION REPORT</small></div><div class="report-stats"></div><div class="report-favourite"></div><div class="report-actions"></div>';el.querySelector('strong').textContent=won?'VICTORY':battleResult.winner?'PILOT RECOVERED':'DRAW';const stats=[['PROJECTILE ACCURACY',r.accuracy===null?'—':r.accuracy+'%'],['DAMAGE DEALT',r.dealt],['DAMAGE TAKEN',r.received],['MECHS DESTROYED',r.kills],['BATTLE TIME',Math.floor(r.duration/60)+':'+String(Math.floor(r.duration%60)).padStart(2,'0')],['HEALTH REMAINING',r.health+' / 700']];for(const[label,value]of stats){const cell=document.createElement('div');cell.innerHTML='<small></small><strong></strong>';cell.querySelector('small').textContent=label;cell.querySelector('strong').textContent=value;el.querySelector('.report-stats').appendChild(cell)}const favourite=el.querySelector('.report-favourite');if(r.favourite){const im=document.createElement('img');im.src='assets/'+r.favourite+'.png';im.alt='';favourite.appendChild(im)}const text=document.createElement('span');text.textContent='FAVOURITE WEAPON · '+(r.favourite?nameOf(r.favourite):'NONE USED');favourite.appendChild(text);const actions=el.querySelector('.report-actions'),next=document.createElement('button');next.className='next-battle ready-flash';next.textContent=won?(campaignActive?(rookieProgress.completed===5?'CHAMPIONSHIP RESULTS':'NEXT BATTLE →'):'RETURN TO WORKSHOP'):'RETURN TO WORKSHOP';next.onclick=()=>node('return').onclick();actions.appendChild(next);if(!won){const retry=document.createElement('button');retry.textContent='RETRY BATTLE';retry.onclick=()=>rematchBattle();actions.appendChild(retry)}panel.appendChild(el);panel.classList.add('report-visible')}
const reportPanel=updateBattlePanel;updateBattlePanel=function(){reportPanel();if(battleResult&&currentPanel()?.classList.contains('panel-off')&&!(typeof trainingActive!=='undefined'&&trainingActive))showBattleReport(currentPanel(),p)};
// Highlight the surviving mech without moving it or changing gameplay geometry.
const celebrateDraw=drawStadiumAtmosphere;drawStadiumAtmosphere=function(c,w,h){celebrateDraw(c,w,h);if(!battleResult?.winner)return;const v=stadiumView(w,h),a=battleResult.winner,t=battleResult.age;c.save();for(let i=0;i<20;i++){const u=(i+.5)/20,col=i%2?'205,255,250':'75,255,150',alpha=(.3+.3*Math.sin(t*3-i*.4))*Math.max(0,1-t/14);for(const y of [v.y-7,v.y+v.h+7])stadiumGlow(c,v.x+v.w*u,y,20,col,alpha)}const x=v.x+(a.x/ARENA.width)*v.w,y=v.y+(a.y/ARENA.height)*v.h;stadiumGlow(c,x,y,85,'205,255,225',.16);c.strokeStyle='#d3f9d766';c.lineWidth=1;c.beginPath();c.arc(x,y,43,0,Math.PI*2);c.stroke();c.fillStyle='#061c22df';c.fillRect(w*.16,28,w*.68,56);c.fillStyle='#d5ffeb';c.font='bold 20px system-ui';c.textAlign='center';const champion=campaignActive&&campaignOutcome?.won&&campaignOutcome.mission===4;c.fillText(champion?'ROOKIE CHAMPION · ROURKE':'VICTORY · '+(a===p?(campaignActive?'ROURKE':'YOU'):a.name),w/2,52);c.font='11px system-ui';c.fillStyle='#9ccfc3';c.fillText(champion?'SPONSORSHIP SECURED':campaignActive&&campaignOutcome?.won?ROOKIE_MATCHES[campaignOutcome.mission].round+' COMPLETE':'WEAPON SYSTEMS DEACTIVATED',w/2,72);c.restore()};
const celebrateBegin=beginVictoryCelebration;beginVictoryCelebration=function(){celebrateBegin();stadiumSound('crowd-cheer',1.55);crowdDuck=8;stadiumSound('flame-start',.5)};
// Short celebratory jets reuse the same softened flame renderer and audio.
const celebratePerimeter=drawPerimeter;drawPerimeter=function(c){celebratePerimeter(c);if(!battleResult?.winner||battleResult.age>2)return;const atlas=perimeterTexture(),frame=Math.floor(stadiumClock*24)%16;for(const jet of perimeterJets){c.save();c.translate(jet.x,jet.y);c.rotate(jet.a-Math.PI/2);c.globalCompositeOperation='screen';c.globalAlpha=Math.min(1,(2-battleResult.age)*2);c.drawImage(atlas,frame%4*256,Math.floor(frame/4)*128,256,128,0,-45,170,90);c.restore()}};
