'use strict';
// Two independent human control contexts, one shared simulation and one camera.
let duelActive=false,duelPlayers=[],buildTurn=0;const savedBots=enemies.slice(),soloPlayer=p;
const duelControls=['move','primary','secondary','support','shield','eject','turnLeft','turnRight','repair','charge','hullReadout','componentReadout','hullFill','minimap'];
const bottomPanel=document.querySelector('.panel');bottomPanel.id='p1-panel';
const topPanel=bottomPanel.cloneNode(true);topPanel.id='p2-panel';topPanel.classList.add('opposite-panel');for(const el of topPanel.querySelectorAll('[id]'))el.id='p2-'+el.id;topPanel.hidden=true;$('arena').insertBefore(topPanel,$('world'));
const topStatus=document.createElement('div');topStatus.id='p2-deploymentStatus';topStatus.hidden=true;topStatus.className='duel-status';$('arena').appendChild(topStatus);
function captureDuelState(s){Object.assign(s,{actor:p,build,modifications,input,firing,cooldown,traverse,keys,weaponHeat,missileLock,bipedRig,repairState,repairUses,ejectHeld,ejectPress,deployment,motionLoops:Sound.motionLoops,motionNodes:Sound.motionNodes,turretSession:Sound.turretSession,turretTail:Sound.turretTail,bipedNodes:Sound.bipedNodes})}
function installDuelState(s){p=s.actor;build=s.build;modifications=s.modifications;input=s.input;firing=s.firing;cooldown=s.cooldown;traverse=s.traverse;keys=s.keys;weaponHeat=s.weaponHeat;missileLock=s.missileLock;bipedRig=s.bipedRig;repairState=s.repairState;repairUses=s.repairUses;ejectHeld=s.ejectHeld;ejectPress=s.ejectPress;deployment=s.deployment;controlPrefix=s.index?'p2-':'';for(const key of ['motionLoops','motionNodes','turretSession','turretTail','bipedNodes'])Sound[key]=s[key];enemies.splice(0,enemies.length,...duelPlayers.filter(a=>a!==s).map(a=>a.actor))}
function withDuelPlayer(index,fn){const target=duelPlayers[index];if(!target)return;const previous=duelPlayers.find(s=>s.actor===p);if(previous)captureDuelState(previous);installDuelState(target);try{return fn()}finally{captureDuelState(target);if(previous)installDuelState(previous)}}
function freshDuelPlayer(index,config){const actor={id:'human-'+index,name:'PLAYER '+(index+1),human:true,duelIndex:index,marker:index?'#ffae68':'#65e9f3',loadout:config.build,modifications:config.modifications,x:900,y:index?430:1370,heading:index?Math.PI:0,angle:index?Math.PI:0,energy:100,shield:0,hp:700,dead:false,alive:true,ejecting:null,generation:Date.now()+index,slow:1,slowTime:0,burn:0,burnTime:0};resetParts(actor);const rig={feet:[],clock:0,active:false};actor.rig=rig;return{index,actor,build:config.build,modifications:config.modifications,input:{move:{x:0,y:0},aim:{x:0,y:0}},firing:{primary:false,secondary:false,support:false},cooldown:{primary:0,secondary:0,support:0},traverse:{left:false,right:false},keys:new Set(),weaponHeat:{primary:{id:null,value:0,locked:false,lastShot:-10},secondary:{id:null,value:0,locked:false,lastShot:-10}},missileLock:{held:false,progress:0,target:null,ready:false,tone:null,nextTone:0,keyHeld:false},bipedRig:rig,repairState:null,repairUses:2,ejectHeld:false,ejectPress:0,deployment:null,motionLoops:{},motionNodes:new Set(),turretSession:null,turretTail:null,bipedNodes:{}}}
const soloInstructions=$('buildInstructions').textContent;let duelBuilds=[],soloSnapshot=null;const soloHandlers=new Map();for(const id of duelControls){const el=$(id);if(el)soloHandlers.set(id,Object.fromEntries(['onclick','onpointerdown','onpointermove','onpointerup','onpointercancel','onlostpointercapture'].map(k=>[k,el[k]])))}
function displayBuildTurn(){const config=duelBuilds[buildTurn];build={...config.build};modifications={...config.modifications};for(const key in build)document.getElementById(key).value=build[key];$('builder').classList.toggle('opposite-builder',buildTurn===1);$('buildHeading').textContent='PLAYER '+(buildTurn+1)+' · BUILD YOUR MECH';$('deploy').textContent=buildTurn===0?'Confirm · Player Two builds next':'Start two-player match';$('builder').scrollTop=0;update()}
function beginDuelBuild(){$('buildVersion').textContent='TWO-PLAYER TEST · v27';$('buildInstructions').textContent='Two human players only. Player One builds first; Player Two builds from the opposite end. Your own Slot 1, Slot 2 and Slot 3 controls, shield, repair and eject work independently. The entire 1,800 × 1,800 arena stays visible. Roofs and the central monument block movement and direct fire. Hold Slot 3 to lock swarm/hunter missiles and release to fire. Last surviving mech wins.';duelBuilds=[{build:{...build},modifications:{...modifications}},{build:{...build,colour:build.colour==='red'?'green':'red'},modifications:{primary:'standard',secondary:'standard',support:'standard'}}];try{const stored=JSON.parse(localStorage.getItem('iron-pit-duel-builds'));if(stored?.length===2&&stored.every(s=>s.build&&s.modifications&&['green','red'].includes(s.build.colour)&&['chassis','biped'].includes(s.build.chassis)&&s.build.turret==='turret'&&PRIMARY_IDS.includes(s.build.left)&&SECONDARY_IDS.includes(s.build.right)&&rear.some(v=>v[0]===s.build.rear)))duelBuilds=stored}catch(e){}buildTurn=0;$('startScreen').hidden=true;$('builder').style.display='block';displayBuildTurn();Sound.startMusic()}
const soloDeploy=$('deploy').onclick;
$('deploy').onclick=()=>{if(!$('startScreen').hidden||buildTurn<0)return soloDeploy();if(!ready||!build.chassis||!build.turret)return;duelBuilds[buildTurn]={build:{...build},modifications:{...modifications}};if(buildTurn===0){buildTurn=1;displayBuildTurn();return}try{localStorage.setItem('iron-pit-duel-builds',JSON.stringify(duelBuilds))}catch(e){}startDuel()};
function startDuel(){soloSnapshot={index:0};captureDuelState(soloSnapshot);Sound.stopAll();cancelLaunches();clearCombatFx();duelPlayers=duelBuilds.map((v,i)=>freshDuelPlayer(i,v));duelActive=true;setArenaMode('duel');installDuelState(duelPlayers[0]);inArena=true;$('builder').classList.remove('opposite-builder');$('builder').style.display='none';$('arena').style.display='flex';$('arena').classList.add('two-player');topPanel.hidden=false;for(let i=0;i<2;i++)withDuelPlayer(i,()=>{resetHeat();resetRepair();resetBiped();bindDuelControls(i);startDeployment()});installDuelState(duelPlayers[0]);window.getSelection?.()?.removeAllRanges();last=0}
function bindDuelControls(index){const wrap=fn=>(...args)=>withDuelPlayer(index,()=>fn(...args));const move=$('move');let pointer=null;const set=e=>{const rect=move.getBoundingClientRect(),r=rect.width/2-20,flip=index?-1:1;let x=(e.clientX-rect.left-rect.width/2)/r,y=(e.clientY-rect.top-rect.height/2)/r;const m=Math.hypot(x,y);if(m>1){x/=m;y/=m}input.move={x,y};move.querySelector('.knob').style.transform=`translate(${x*r*flip}px,${y*r*flip}px)`};move.onpointerdown=wrap(e=>{if(pointer!==null||deployment||p.dead)return;e.preventDefault();pointer=e.pointerId;move.setPointerCapture(pointer);set(e)});move.onpointermove=wrap(e=>{if(e.pointerId===pointer)set(e)});const release=wrap(e=>{if(e.pointerId!==pointer)return;pointer=null;input.move={x:0,y:0};move.querySelector('.knob').style.transform=''});move.onpointerup=move.onpointercancel=move.onlostpointercapture=release;
 function bind(id,fn){hold(id,fn);const el=$(id);for(const name of ['onpointerdown','onpointerup','onpointercancel','onlostpointercapture'])el[name]=wrap(el[name])}
 bind('turnLeft',v=>traverse.left=v);bind('turnRight',v=>traverse.right=v);for(const slot of ['primary','secondary'])bind(slot,v=>{firing[slot]=v;if(!v)stopWeaponSound(slot)});bind('support',v=>supportControl(v));$('support').onpointercancel=$('support').onlostpointercapture=wrap(()=>{supportControl(false,true);$('support').classList.remove('active')});bind('eject',v=>{if(deployment||p.dead||p.ejecting)return;ejectHeld=v;if(!v)ejectPress=0});$('shield').onclick=wrap(()=>{if(!deployment&&!p.dead&&!p.ejecting&&p.energy>20&&p.shield<=0){p.shield=3;traverse.left=traverse.right=false}});$('repair').onclick=wrap(beginRepair)
}
function clearDuelInput(){if(!duelActive)return;for(let i=0;i<2;i++)withDuelPlayer(i,()=>{keys.clear();input.move={x:0,y:0};traverse.left=traverse.right=false;ejectHeld=false;ejectPress=0;for(const slot in firing)firing[slot]=false;clearLock();cancelPlayerLaunches();$('move').querySelector('.knob').style.transform='';for(const id of ['primary','secondary','support','turnLeft','turnRight','eject'])$(id).classList.remove('active')})}
const soundStopAll=Sound.stopAll.bind(Sound);Sound.stopAll=function(){if(duelActive)for(let i=0;i<2;i++)withDuelPlayer(i,()=>Sound.stopMotion());soundStopAll()};
window.addEventListener('blur',clearDuelInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearDuelInput()});
const soloReturn=$('return').onclick;
function leaveDuel(){clearDuelInput();Sound.stopAll();cancelLaunches();for(let i=0;i<2;i++)withDuelPlayer(i,()=>{cancelDeployment();stopRepair()});duelActive=false;inArena=false;if(soloSnapshot)installDuelState(soloSnapshot);controlPrefix='';p=soloPlayer;for(const [id,handlers]of soloHandlers)Object.assign($(id),handlers);enemies.splice(0,enemies.length,...savedBots);setArenaMode('solo');$('arena').classList.remove('two-player');topPanel.hidden=true;$('arena').style.display='none';$('builder').style.display='none';$('builder').classList.remove('opposite-builder');$('startScreen').hidden=false;build={...duelBuilds[0].build};modifications={...duelBuilds[0].modifications};deployment=null;stopFiring();Sound.startMusic()}
$('return').onclick=()=>{if(duelActive)leaveDuel();else{soloReturn();$('builder').style.display='none';$('startScreen').hidden=false}};
$('twoPlayer').onclick=beginDuelBuild;
$('onePlayer').onclick=()=>{$('buildVersion').textContent='RADIAL FFA · v27';$('buildInstructions').textContent=soloInstructions;buildTurn=-1;$('startScreen').hidden=true;$('builder').style.display='block';$('buildHeading').textContent='BUILD YOUR MECH';$('deploy').textContent='Enter arena';for(const key in build)$(key).value=build[key];update();Sound.startMusic()};
$('buildBack').onclick=()=>{$('builder').classList.remove('opposite-builder');$('builder').style.display='none';$('startScreen').hidden=false};
function duelFrame(t){const dt=document.hidden?0:Math.min((t-last)/1000||0,.035);last=t;Sound.stepMusic(dt);if(ready&&!document.hidden){const delivering=duelPlayers.some(s=>s.deployment);document.querySelector('#hud span').textContent=delivering?'v27 · TRANSPORT / COCKPIT BOOT':'v27 · TWO-PLAYER TEST';if(delivering){for(let i=0;i<2;i++)withDuelPlayer(i,()=>{if(deployment)stepDeployment(dt);updateDiagnostics()})}else{for(let i=0;i<2;i++)withDuelPlayer(i,()=>{stepRepair(dt);stepPlayer(dt);updateDiagnostics()});stepWeapons(dt);stepUrban(dt)}renderDuel()}requestAnimationFrame(frame)}
function renderDuel(){const[c,w,h]=resize($('world')),zoom=Math.min(w,h)/1800;c.fillStyle='#101925';c.fillRect(0,0,w,h);c.save();c.translate((w-1800*zoom)/2,(h-1800*zoom)/2);c.scale(zoom,zoom);urbanVisible.bounds={x0:0,y0:0,x1:1800,y1:1800};drawUrbanGround(c,w,h);drawWeapons(c);for(let i=0;i<2;i++)withDuelPlayer(i,()=>{if(deployment)drawDeployment(c,w,h);else if(!p.dead&&(!p.ejecting||p.ejecting.age<3.03))mech(c,p.x,p.y,.85,p.heading,p.angle,build,p.parts,build.chassis==='biped'?bipedRig:null,p.id);if(p.shield>0)drawEnergyShield(c,p.x,p.y);drawLock(c);c.save();c.translate(p.x,p.y+(i?-150:160));if(i)c.rotate(Math.PI);c.font='24px ui-monospace';c.textAlign='center';c.fillStyle=p.marker;c.fillText(p.name,0,0);c.restore();drawPanelMinimap(w,h)});drawSmokeClouds(c);drawLocalLights(c);drawCombatLights(c);drawBlastOverlay(c);c.restore();const alive=duelPlayers.filter(s=>aliveActor(s.actor));const pending=duelPlayers.some(s=>s.actor.ejecting&&!s.actor.dead);if(alive.length<2&&!pending&&!duelPlayers.some(s=>s.deployment)){c.fillStyle='#000c';c.fillRect(0,h/2-30,w,60);c.fillStyle='#d8f5ff';c.font='bold 18px system-ui';c.textAlign='center';c.fillText(alive.length?alive[0].actor.name+' WINS':'DRAW',w/2,h/2+6);c.textAlign='start'}}
