'use strict';
const BOT_BUILDS=[
 {colour:'red',chassis:'chassis',turret:'turret',left:'rotary',right:'siege',rear:'hunter'},
 {colour:'green',chassis:'chassis',turret:'turret',left:'pulse',right:'plasma',rear:'swarm'},
 {colour:'red',chassis:'chassis',turret:'turret',left:'machine-gun',right:'tri-salvo',rear:'barrage'}
];
const enemies=BOT_BUILDS.map((loadout,i)=>({id:'bot-'+i,name:['BREAKER','VOLT','SALVO'][i],marker:['#ff9274','#c0ef85','#dab5ff'][i],loadout,x:0,y:0,r:100,heading:0,angle:0,hp:700,alive:true,shield:false,shieldTimer:0,energy:100,generation:0,slow:1,slowTime:0,burn:0,burnTime:0,hit:0,parts:null,cooldown:{primary:0,secondary:0,support:0},heat:{primary:{value:0,locked:false},secondary:{value:0,locked:false}},path:[],repath:0,lockTime:0,target:null,shots:0}));
const enemy=enemies[0],enemyLoadout=enemy.loadout;
function aliveActor(a){return a.human||a===p?!a.dead&&!a.ejecting:a.alive}
function actorLoadout(a){return a.human?a.loadout:a===p?build:a.loadout}
function placeUrbanEnemy(){enemies.splice(0,enemies.length,enemy);enemies.forEach((a,i)=>{Object.assign(a,ARENA.spawns[i+1],{alive:true,heading:Math.atan2(ARENA.width/2-ARENA.spawns[i+1].x,-(ARENA.height/2-ARENA.spawns[i+1].y)),energy:100,shield:false,shieldTimer:0,slow:1,slowTime:0,burnTime:0,hit:0,path:[],repath:0,target:null,lockTime:0,shots:0,leftMode:'move',leftTimer:0,leftSlot:null,slotIndex:i,reaction:.6,rightPause:0,aimHeld:0});a.angle=a.heading;a.generation++;resetParts(a);for(const slot in a.cooldown)a.cooldown[slot]=i*.25;for(const slot in a.heat)Object.assign(a.heat[slot],{value:0,locked:false});trackMotion[a.id]=[0,0]})}
function botHeat(a,slot,id,dt,shooting){const h=a.heat[slot],cfg=HEAT_CONFIG[id];if(!h||!cfg)return true;if(h.locked||!shooting){h.value=Math.max(0,h.value-dt*80/cfg.cool);if(h.locked&&h.value<=20)h.locked=false}return !h.locked}
function stepEnemy(dt){for(const a of enemies){if(!a.alive)continue;const oldAngle=a.angle;a.hit=Math.max(0,a.hit-dt);a.leftTimer-=dt;a.reaction=Math.max(0,a.reaction-dt);a.rightPause=Math.max(0,a.rightPause-dt);a.slowTime=Math.max(0,a.slowTime-dt);if(!a.slowTime)a.slow=1;if(a.burnTime>0){a.burnTime-=dt;enemyHit('flame',{damage:a.burn*dt,penetration:1},1,true,'hull',a);if(!a.alive)continue}a.shieldTimer=Math.max(0,a.shieldTimer-dt);if(a.shield){a.energy=Math.max(0,a.energy-30*dt);a.shield=a.shieldTimer>0&&a.energy>0}else a.energy=Math.min(100,a.energy+12*dt);
 if(fieldEnabled()&&fieldEvade(a,dt))continue;
 const rivals=[p,...enemies].filter(t=>t!==a&&aliveActor(t));if(!rivals.length)continue;
 const visible=rivals.filter(t=>!urbanSweep(a.x,a.y,t.x,t.y)&&!smokeObscures(a.x,a.y,t.x,t.y));const choices=visible.length?visible:rivals;choices.sort((b,c)=>Math.hypot(b.x-a.x,b.y-a.y)-Math.hypot(c.x-a.x,c.y-a.y));const target=choices[0];if(target!==a.target){a.target=target;a.lockTime=0;a.repath=0;a.reaction=.6;a.aimHeld=0}const dx=target.x-a.x,dy=target.y-a.y,distance=Math.hypot(dx,dy),desired=Math.atan2(dx,-dy)+Math.sin(urbanClock*1.7+enemies.indexOf(a)*2)*.045,clear=visible.includes(target);const delta=Math.atan2(Math.sin(desired-a.angle),Math.cos(desired-a.angle));if(a.rightPause<=0&&a.reaction<=0&&Math.abs(delta)>.035)a.angle+=Math.max(-TURRET_SPEED*dt,Math.min(TURRET_SPEED*dt,delta));
 const oldX=a.x,oldY=a.y,oldHeading=a.heading,tracks=2;
 // Search along connected roads when buildings hide an opponent.
 const slots=['primary','secondary','support'],keys=['left','right','rear'];
 if(a.leftTimer<=0){if(a.leftMode==='switch'){a.leftMode='fire';a.leftTimer=a.leftSlot==='support'?1.65:1.05;a.lockTime=0}else if(a.leftMode==='fire'){a.leftMode='recover';a.leftTimer=.35;a.leftSlot=null}else{let selected=null;if(clear&&distance<850&&a.reaction<=0)for(let j=0;j<3;j++){const i=(a.slotIndex+j)%3,key=keys[i],slot=slots[i];if(a.cooldown[slot]<=0&&!a.heat[slot]?.locked){selected=slot;a.slotIndex=(i+1)%3;break}}if(selected){a.leftMode='switch';a.leftSlot=selected;a.leftTimer=.3}else{a.leftMode='move';a.leftTimer=.2}}}
 a.repath-=dt;if(a.leftMode==='move'&&(!clear||distance>650)){if(a.repath<=0){a.path=navPath(a,target);a.repath=1.4}while(a.path.length&&Math.hypot(a.path[0].x-a.x,a.path[0].y-a.y)<30)a.path.shift();const goal=a.path[0];if(goal&&tracks){const heading=Math.atan2(goal.x-a.x,-(goal.y-a.y)),diff=Math.atan2(Math.sin(heading-a.heading),Math.cos(heading-a.heading));a.heading+=Math.max(-1.8*dt,Math.min(1.8*dt,diff));const speed=loadoutSpeed(a.loadout)*a.slow*(tracks===2?1:.4),nx=a.x+Math.sin(heading)*speed*dt,ny=a.y-Math.cos(heading)*speed*dt;if(![p,...enemies].some(t=>t!==a&&aliveActor(t)&&Math.hypot(t.x-nx,t.y-ny)<210))urbanMove(a,nx,ny)}}
 stepTrackMotion(a.id,(a.x-oldX)*Math.sin(a.heading)-(a.y-oldY)*Math.cos(a.heading),Math.atan2(Math.sin(a.heading-oldHeading),Math.cos(a.heading-oldHeading)));
 const aligned=clear&&Math.abs(delta)<.16&&distance<950;if(aligned&&a.reaction<=0&&a.rightPause<=0)a.aimHeld+=dt;else a.aimHeld=0;if(aligned&&a.leftMode==='fire'&&a.leftSlot==='support')a.lockTime+=dt;else a.lockTime=0;
 if(a.hp<420&&clear&&distance<750&&!a.shield&&a.energy>65&&a.shieldTimer<=0){a.shield=true;a.shieldTimer=2.5;a.rightPause=.5;a.aimHeld=0;a.angle=oldAngle}
 for(const [slot,key,offset]of [['primary','left',-85],['secondary','right',85],['support','rear',0]]){const id=a.loadout[key],g=GUNS[id];a.cooldown[slot]-=dt;const shooting=a.leftMode==='fire'&&a.leftSlot===slot&&a.reaction<=0&&a.aimHeld>=.35&&aligned&&distance<(g.range||950)&&(!['hunter','swarm'].includes(id)||a.lockTime>=1);if(botHeat(a,slot,id,dt,shooting)&&shooting&&a.cooldown[slot]<=0){withShooter(a,()=>fireWeapon(id,offset,['hunter','swarm'].includes(id)?target:null));a.shots++;a.cooldown[slot]=weaponStats(id).rate;const h=a.heat[slot],cfg=HEAT_CONFIG[id];if(h&&cfg){h.value=Math.min(100,h.value+(cfg.seconds?80*a.cooldown[slot]/cfg.seconds:80/(cfg.shots-.5)));if(h.value>=100)h.locked=true}}}
 }}
function enemyHit(id,stats=weaponStats(id),falloff=1,tick=false,part='hull',actor=enemy){if(!aliveActor(actor))return;let amount=stats.damage*falloff*(1-.25*(1-(stats.penetration||0)));if(stats.slow){actor.slow=Math.min(actor.slow||1,stats.slow);actor.slowTime=stats.duration}if(stats.burn&&!tick){actor.burn=stats.burn;actor.burnTime=1.3}actor.hp=Math.max(0,actor.hp-amount);actor.parts.hull=actor.hp;actor.hit=.12;actor.lastPart='hull';if(amount>0&&!tick&&actor.hp>0)crowdHitReaction();if(actor.hp<=0){if(actor.human){actor.dead=true;actor.alive=false;withDuelPlayer(actor.duelIndex,()=>{stopFiring();cancelPlayerLaunches();stopRepair()})}else if(actor===p){actor.dead=true;stopFiring();cancelPlayerLaunches()}else actor.alive=false;destroyMech(actor.x,actor.y,actor.heading,actor.angle,actorLoadout(actor))}}
function drawEnemy(c){for(const a of enemies){if(!a.alive)continue;const b=urbanVisible.bounds;if(b&&(a.x+200<b.x0||a.x-200>b.x1||a.y+200<b.y0||a.y-200>b.y1))continue;mech(c,a.x,a.y,.85,a.heading,a.angle,a.loadout,a.parts,null,a.id);if(a.shield)drawEnergyShield(c,a.x,a.y);if(a.hit>0)glow(c,a.x,a.y,55,'#ffb373',a.hit*3);c.fillStyle='#632f30';c.fillRect(a.x-45,a.y-135,90,6);c.fillStyle=a.marker;c.fillRect(a.x-45,a.y-135,90*a.hp/700,6);c.fillStyle=a.marker;c.font='14px system-ui';c.textAlign='center';c.fillText(a.name,a.x,a.y-147);c.textAlign='start'}}
function drawEnergyShield(c,x,y){const g=c.createRadialGradient(x-25,y-35,5,x,y,145);g.addColorStop(0,'#a7eaff33');g.addColorStop(.8,'#328eff18');g.addColorStop(1,'#60cfff88');c.fillStyle=g;c.beginPath();c.arc(x,y,142,0,Math.PI*2);c.fill();c.strokeStyle='#76d8ffc0';c.lineWidth=2;c.stroke()}
