'use strict';
// Grid cells have >= two fully armed mech widths of clear floor.
const FIELD_GRID={cols:3,rows:4,thickness:18,period:30,warning:5};
let fieldState=null,fieldRevision=0;
function fieldEnabled(){return arenaMode==='solo'}
function fieldEdges(){if(arenaKind==='rotating')return rotatingFieldEdges();const out=[],g=FIELD_GRID,cw=ARENA.width/g.cols,ch=ARENA.height/g.rows;for(let y=0;y<g.rows;y++)for(let x=1;x<g.cols;x++)out.push({key:'v'+x+':'+y,a:y*g.cols+x-1,b:y*g.cols+x,x:x*cw-g.thickness/2,y:y*ch,w:g.thickness,h:ch});for(let y=1;y<g.rows;y++)for(let x=0;x<g.cols;x++)out.push({key:'h'+x+':'+y,a:(y-1)*g.cols+x,b:y*g.cols+x,x:x*cw,y:y*ch-g.thickness/2,w:cw,h:g.thickness});return out}
function fieldConnected(walls){if(arenaKind==='rotating')return true;const blocked=new Set(walls.map(e=>e.key)),edges=fieldEdges(),seen=new Set([0]),queue=[0];for(let i=0;i<queue.length;i++)for(const e of edges){if(blocked.has(e.key))continue;const n=e.a===queue[i]?e.b:e.b===queue[i]?e.a:-1;if(n>=0&&!seen.has(n)){seen.add(n);queue.push(n)}}return seen.size===FIELD_GRID.cols*FIELD_GRID.rows}
function fieldOverlap(x,y,r,walls){return walls.some(b=>{let xx=x,yy=y;if(b.mounted){const dx=x-ARENA.width/2,dy=y-ARENA.height/2;xx=ARENA.width/2+dx*Math.cos(terrainAngle)+dy*Math.sin(terrainAngle);yy=ARENA.height/2-dx*Math.sin(terrainAngle)+dy*Math.cos(terrainAngle)}return Math.hypot(xx-Math.max(b.x,Math.min(b.x+b.w,xx)),yy-Math.max(b.y,Math.min(b.y+b.h,yy)))<=r})}
function fieldGenerate(previous=[],initial=false,random=Math.random){if(arenaKind==='rotating')return rotatingFieldGenerate(previous,random);const all=fieldEdges(),old=new Set(previous.map(e=>e.key));for(let attempt=0;attempt<24;attempt++){const shuffled=[...all];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}const walls=[];for(const e of shuffled){if(initial&&ARENA.spawns.some(s=>fieldOverlap(s.x,s.y,ARENA.radius+20,[e])))continue;if(fieldConnected([...walls,e]))walls.push(e);if(walls.length===5)break}if(walls.length>=4&&walls.some(e=>!old.has(e.key)))return walls}return previous.length?all.filter(e=>!old.has(e.key)).reduce((out,e)=>out.length<5&&fieldConnected([...out,e])?[...out,e]:out,[]):[]}
function resetFields(){fieldRevision++;fieldState=fieldEnabled()?{age:0,walls:fieldGenerate([],true),next:null,flash:0}:null;Sound.stopLoop('field-warning');if(typeof navigation!=='undefined')navigation=null}
function fieldSolid(x,y){return fieldEnabled()&&fieldState?fieldOverlap(x,y,0,fieldState.walls):false}
function fieldKill(actor){if(!aliveActor(actor))return;actor.hp=0;actor.parts.hull=0;actor.shield=actor===p?0:false;if(actor===p){actor.dead=true;stopFiring();cancelPlayerLaunches();stopRepair()}else actor.alive=false;destroyMech(actor.x,actor.y,actor.heading,actor.angle,actorLoadout(actor))}
function stepFields(dt){const s=fieldState;if(s)s.flash=Math.max(0,s.flash-dt);if(!s||!fieldEnabled()||!inArena||[p,...enemies].filter(aliveActor).length<2){Sound.stopLoop('field-warning');return}s.age+=dt;if(s.age>=25&&!s.next){s.next=fieldGenerate(s.walls);stadiumSound('crowd-hit',.85);crowdHitWait=Math.max(crowdHitWait,5)}if(s.next&&s.age<30)Sound.loop('stadium-siren','field-warning',p.x,p.y,.95,1);if(s.age>=30){s.walls=s.next||fieldGenerate(s.walls);s.next=null;s.age-=30;s.flash=.8;fieldRevision++;navigation=null;lampMode=null;for(const actor of [p,...enemies])if(aliveActor(actor)&&fieldOverlap(actor.x,actor.y,ARENA.radius,s.walls))fieldKill(actor);for(const a of enemies){a.path=[];a.repath=0}Sound.stopLoop('field-warning')}}
function fieldWarningLights(){const s=fieldState;if(!s||!fieldEnabled())return null;if(s.next){const t=s.age-25,red=t>=4;return{colour:red?'255,35,25':'255,205,35',alpha:red?1:Math.sin(t*7+t*t*3)>0?1:0}}if(s.flash>0)return{colour:'255,35,25',alpha:s.flash/.8};return null}
function drawFields(c){const s=fieldState;if(!s||!fieldEnabled())return;const g=FIELD_GRID,cw=ARENA.width/g.cols,ch=ARENA.height/g.rows;c.save();c.strokeStyle='rgba(93,165,195,.22)';c.lineWidth=2;for(let i=0;i<=g.cols;i++){c.beginPath();c.moveTo(i*cw,0);c.lineTo(i*cw,ARENA.height);c.stroke()}for(let j=0;j<=g.rows;j++){c.beginPath();c.moveTo(0,j*ch);c.lineTo(ARENA.width,j*ch);c.stroke()}
 function beam(b,col,a){c.save();if(b.mounted){c.translate(ARENA.width/2,ARENA.height/2);c.rotate(terrainAngle);c.translate(-ARENA.width/2,-ARENA.height/2)}const vertical=b.w<b.h,x=vertical?b.x+b.w/2:b.x,y=vertical?b.y:b.y+b.h/2,ex=vertical?x:b.x+b.w,ey=vertical?b.y+b.h:y;c.globalAlpha=a;c.strokeStyle=col;c.lineWidth=24;c.shadowColor=col;c.shadowBlur=28;c.beginPath();c.moveTo(x,y);c.lineTo(ex,ey);c.stroke();c.shadowBlur=0;c.strokeStyle='#d5faff';c.lineWidth=3;c.stroke();c.globalAlpha=1;c.restore()}
 for(const b of s.walls)beam(b,'#25cfff',.75+.1*Math.sin(urbanClock*8));if(s.next){const light=fieldWarningLights();for(const b of s.next)if(!s.walls.some(w=>w.key===b.key))beam(b,s.age>=29?'#ff4535':'#ffd442',.18+light.alpha*.5)}
 for(let y=0;y<=g.rows;y++)for(let x=0;x<=g.cols;x++){const xx=x*cw,yy=y*ch,lit=s.walls.some(b=>fieldOverlap(xx,yy,5,[b]));c.fillStyle='#101923';c.strokeStyle='#61717d';c.lineWidth=2;c.fillRect(xx-13,yy-13,26,26);c.strokeRect(xx-13,yy-13,26,26);c.fillStyle=lit?'#8af2ff':'#516e81';c.shadowColor='#3ccfff';c.shadowBlur=lit?16:0;c.beginPath();c.arc(xx,yy,5,0,Math.PI*2);c.fill();c.shadowBlur=0}if(arenaKind==='rotating'){c.save();c.translate(ARENA.width/2,ARENA.height/2);c.rotate(terrainAngle);for(const b of s.walls.filter(b=>b.mounted)){const vertical=b.w<b.h;for(const[x,y]of vertical?[[b.x+b.w/2,b.y],[b.x+b.w/2,b.y+b.h]]:[[b.x,b.y+b.h/2],[b.x+b.w,b.y+b.h/2]]){c.fillStyle='#17232b';c.fillRect(x-ARENA.width/2-13,y-ARENA.height/2-13,26,26);c.fillStyle='#a1f5ff';c.fillRect(x-ARENA.width/2-5,y-ARENA.height/2-5,10,10)}}c.restore()}c.restore()}
function fieldEvade(a,dt){const s=fieldState;if(!s?.next||!fieldOverlap(a.x,a.y,ARENA.radius+25,s.next))return false;if(a.escapeRevision!==fieldRevision||a.escapeTarget==null||(arenaKind==='rotating'&&Math.abs((a.escapeAngle||0)-terrainAngle)>.08)){a.escapeAngle=terrainAngle;const goals=[];for(let y=0;y<FIELD_GRID.rows;y++)for(let x=0;x<FIELD_GRID.cols;x++)goals.push({x:(x+.5)*ARENA.width/FIELD_GRID.cols,y:(y+.5)*ARENA.height/FIELD_GRID.rows});goals.sort((b,c)=>Math.hypot(b.x-a.x,b.y-a.y)-Math.hypot(c.x-a.x,c.y-a.y));a.escapeTarget=goals.find(g=>!fieldOverlap(g.x,g.y,ARENA.radius+25,s.next)&&navPath(a,g).length);a.escapeRevision=fieldRevision;a.escapePath=a.escapeTarget?navPath(a,a.escapeTarget):[]}const path=a.escapePath||[];while(path.length&&Math.hypot(path[0].x-a.x,path[0].y-a.y)<28)path.shift();const goal=path[0];if(goal){const angle=Math.atan2(goal.x-a.x,-(goal.y-a.y)),oldX=a.x,oldY=a.y,old=a.heading;a.heading=angle;urbanMove(a,a.x+Math.sin(angle)*loadoutSpeed(a.loadout)*dt,a.y-Math.cos(angle)*loadoutSpeed(a.loadout)*dt);stepTrackMotion(a.id,(a.x-oldX)*Math.sin(angle)-(a.y-oldY)*Math.cos(angle),angle-old)}return true}

// Corner barriers end toward the open centre; no combination can seal a pocket.
function rotatingFieldEdges(){const cx=ARENA.width/2,cy=ARENA.height/2,t=FIELD_GRID.thickness;return [
 ...[[0,480],[1250,480],[0,1520],[1250,1520]].map(([x,y],i)=>({key:'corner'+i,x,y:y-t/2,w:500,h:t})),
 ...[-1,1].map((k,i)=>({key:'disk-v'+i,mounted:true,x:cx+k*260-t/2,y:cy-170,w:t,h:340})),
 ...[-1,1].map((k,i)=>({key:'disk-h'+i,mounted:true,x:cx-170,y:cy+k*260-t/2,w:340,h:t}))]}
function rotatingFieldGenerate(previous,random){const edges=rotatingFieldEdges(),prior=previous.find(b=>b.mounted)?.key,vertical=prior?prior.startsWith('disk-h'):random()<.5,corners=edges.filter(b=>!b.mounted);const skip=Math.floor(random()*4);return [...corners.filter((b,i)=>i!==skip),...edges.filter(b=>b.mounted&&b.key.startsWith(vertical?'disk-v':'disk-h'))]}
