'use strict';
let controlPrefix='';const CONTROL_IDS=new Set(['primary','secondary','support','shield','eject','turnLeft','turnRight','repair','move','charge','hullReadout','hullFill','componentReadout','minimap','deploymentStatus']);const $=id=>document.getElementById((CONTROL_IDS.has(id)?controlPrefix:'')+id);function currentPanel(){return document.getElementById(controlPrefix?'p2-panel':'p1-panel')}
const side=[['machine-gun','Belt-fed machine gun'],['tri-salvo','Tri-salvo rocket launcher'],['rotary','Rotary autocannon'],['siege','Twin siege cannons'],['railgun','Railgun'],['flak','Flak cannon'],['plasma','Plasma cannon'],['pulse','Pulse lasers'],['beam','Heavy beam laser'],['flame','Flamethrower'],['arc','Arc projector'],['emp','EMP launcher']];
const rear=[['swarm','Swarm missiles'],['hunter','Heavy hunter missiles'],['barrage','Rocket barrage'],['mines','Mine dispenser'],['smoke','Smoke-screen launcher'],['mortar','Cluster mortar']];
for(const id of ['left','right','rear'])$(id).innerHTML='<option value="">None</option>'+(id==='rear'?rear:side.filter(v=>(id==='left'?PRIMARY_IDS:SECONDARY_IDS).includes(v[0]))).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');
const images={};let ready=false,inArena=false,last=0,build={colour:'green',chassis:'chassis',turret:'turret',left:'machine-gun',right:'tri-salvo',rear:'swarm'};
try{const saved=JSON.parse(localStorage.getItem('iron-pit-build-v2'));if(saved)for(const key in build){const allowed=key==='colour'?Object.keys(PALETTES):key==='chassis'?['','chassis','biped']:key==='turret'?['','turret']:['',...(key==='rear'?rear:side).map(x=>x[0])];if(allowed.includes(saved[key]))build[key]=saved[key]}}catch(e){}
if(build.left&&!PRIMARY_IDS.includes(build.left)){if(PRIMARY_IDS.includes(build.right))[build.left,build.right]=[build.right,build.left];else build.left='machine-gun'}if(build.right&&!SECONDARY_IDS.includes(build.right))build.right='tri-salvo';
for(const key in build){$(key).value=build[key];$(key).onchange=()=>{build[key]=$(key).value;save();update()}}
function save(){try{localStorage.setItem('iron-pit-build-v2',JSON.stringify(build))}catch(e){}}
function update(){refreshWeaponAccess();refreshMods();refreshWeaponAccess();$('buildTag').textContent='LIVE ASSEMBLY · '+PALETTES[build.colour].name.toUpperCase();$('turret').options&&($('turret').options[1].textContent='Raised armoured turret · '+PALETTES[build.colour].cockpit.toLowerCase()+' cockpit');$('deploy').disabled=!ready||!build.chassis||!build.turret;$('status').textContent=build.chassis&&build.turret?'Build ready • '+[build.left,build.right,build.rear].filter(Boolean).length+' systems fitted':'Choose a chassis and turret to deploy.'}
function sprite(c,id,x,y,w,h,flip=false,colour='green'){if(!id||!images[id])return;c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(colouredSprite(id,colour),-w/2,-h/2,w,h);c.restore()}
function mech(c,x,y,scale,heading,angle,loadout=build,partHealth=null,rig=null,trackKey=null){c.save();c.translate(x,y);c.scale(scale,scale);if(loadout.chassis==='biped')drawBiped(c,heading,rig,loadout.colour);else{c.save();c.rotate(heading);drawTrackedChassis(c,loadout.chassis,loadout.colour,trackKey||(loadout===build?(p.id||'player'):'enemy'));c.restore()}if(loadout.turret){c.rotate(angle);c.save();c.shadowColor='#000b';c.shadowBlur=12;c.shadowOffsetY=7;brokenSprite(c,loadout.turret,0,-12,151,184,false,partHealth?.turret,loadout.colour);c.restore();if(inArena&&loadout===build&&p.ejecting)drawCockpitBay(c);drawCockpitLights(c,loadout===build?p:enemies.find(a=>a.loadout===loadout)||{hp:700},loadout);for(const[slot,id,part]of [['primary',loadout.left,'left'],['secondary',loadout.right,'right'],['support',loadout.rear,'rear']]){const m=weaponMount(slot,id);c.save();if(slot==='support'){c.shadowColor='#000c';c.shadowBlur=10;c.shadowOffsetY=9}brokenSprite(c,id,m.x,m.y,m.w,m.h,m.flip,partHealth?.[part],loadout.colour);c.restore()}}c.restore()}
function resize(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d)}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);return [c,r.width,r.height]}
let p={x:ARENA.spawn.x,y:ARENA.spawn.y,heading:0,angle:0,energy:100,shield:0,hp:700,dead:false,ejecting:null,generation:0,slow:1,slowTime:0,burn:0,burnTime:0};let input={move:{x:0,y:0},aim:{x:0,y:0}};const effects=[];let firing={primary:false,secondary:false,support:false},cooldown={primary:0,secondary:0,support:0};const ZOOM=.40,TURRET_SPEED=Math.PI*5/12;function stopFiring(){Sound.stopMotion();for(const slot in weaponSoundStates)if(!p.human||slot.startsWith(p.id+'-'))stopWeaponSound(slot);clearLock();$('support').textContent=SLOT_LABELS.support;for(const k in firing)firing[k]=false;if(typeof traverse!=='undefined'){traverse.left=false;traverse.right=false}}
function stick(id){const el=$(id);let pointer=null;function set(e){const r=el.getBoundingClientRect(),radius=r.width/2-20;let x=(e.clientX-r.left-r.width/2)/radius,y=(e.clientY-r.top-r.height/2)/radius;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len}if(id==='aim')y=0;input[id]={x,y};el.querySelector('.knob').style.transform=`translate(${x*radius}px,${y*radius}px)`}el.onpointerdown=e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;el.setPointerCapture(pointer);set(e)};el.onpointermove=e=>{if(e.pointerId===pointer)set(e)};function release(e){if(e.pointerId!==pointer)return;pointer=null;input[id]={x:0,y:0};el.querySelector('.knob').style.transform=''}el.onpointerup=release;el.onpointercancel=release;el.onlostpointercapture=release}
stick('move');let traverse={left:false,right:false};hold('turnLeft',v=>traverse.left=v);hold('turnRight',v=>traverse.right=v);
function hold(id,fn){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);fn(true);b.classList.add('active')};const end=()=>{fn(false);b.classList.remove('active')};b.onpointerup=end;b.onpointercancel=end;b.onlostpointercapture=end}
hold('primary',v=>{firing.primary=v;if(!v)stopWeaponSound('primary')});hold('secondary',v=>{firing.secondary=v;if(!v)stopWeaponSound('secondary')});hold('support',v=>supportControl(v));const cancelSupport=()=>{supportControl(false,true);$('support').classList.remove('active')};$('support').onpointercancel=cancelSupport;$('support').onlostpointercapture=cancelSupport;
$('mute').onclick=()=>Sound.toggle();
$('shield').onclick=()=>{if(!deployment&&!p.dead&&!p.ejecting&&p.energy>20&&p.shield<=0)p.shield=3};
$('deploy').onclick=()=>{if(!ready||!build.chassis||!build.turret)return;Sound.stopAll();clearCombatFx();resetUrban();p.x=ARENA.spawn.x;p.y=ARENA.spawn.y;p.heading=0;p.angle=0;resetParts(p);placeUrbanEnemy();resetHeat();resetBiped();p.energy=100;p.shield=0;p.slow=1;p.slowTime=0;p.burnTime=0;for(const slot in cooldown)cooldown[slot]=0;ejectHeld=false;ejectPress=0;inArena=true;lockBattlePage(true);initialiseProgressMatch(false);resetRepair();startDeployment();window.getSelection?.()?.removeAllRanges();$('builder').style.display='none';$('arena').style.display='flex';input.move={x:0,y:0};input.aim={x:0,y:0}};
$('return').onclick=()=>{inArena=false;lockBattlePage(false);cancelDeployment();stopRepair();stopFiring();cancelLaunches();Sound.stopAll();ejectHeld=false;ejectPress=0;input.move={x:0,y:0};input.aim={x:0,y:0};$('arena').style.display='none';$('builder').style.display='flex';Sound.startMusic()};
$('reset').onclick=()=>{for(const key in build){build[key]=key==='colour'?'green':'';$(key).value=build[key]}save();update()};
let keys=new Set();onkeydown=e=>{if(inArena&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase())};onkeyup=e=>keys.delete(e.key.toLowerCase());onblur=()=>{keys.clear();stopFiring();cancelLaunches();ejectHeld=false;ejectPress=0;input.move={x:0,y:0};input.aim={x:0,y:0}};
let ejectHeld=false,ejectPress=0;hold('eject',v=>{if(deployment||p.dead||p.ejecting)return;ejectHeld=v;if(!v)ejectPress=0});
function stepPlayer(dt){p.slowTime=Math.max(0,p.slowTime-dt);if(!p.slowTime)p.slow=1;if(p.burnTime>0&&!p.dead&&!p.ejecting){p.burnTime-=dt;enemyHit('flame',{damage:p.burn*dt,penetration:1},1,true,'hull',p)}let mx=input.move.x,my=input.move.y;if(keys.size){mx+=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft'));my+=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'))}if(p.dead||p.ejecting){mx=0;my=0}mx*=p.slow;my*=p.slow;let m=Math.hypot(mx,my);const oldX=p.x,oldY=p.y,oldHeading=p.heading;if(m>.08){if(m>1){mx/=m;my/=m}const desired=Math.atan2(mx,-my);if(build.chassis==='biped'){moveBiped(dt,mx,my);if(enemies.some(a=>a.alive&&Math.hypot(a.x-p.x,a.y-p.y)<210)){p.x=oldX;p.y=oldY}}else{const diff=Math.atan2(Math.sin(desired-p.heading),Math.cos(desired-p.heading));if(Math.abs(diff)<Math.PI*2/3)p.heading=desired;{const nx=p.x+mx*loadoutSpeed(build)*dt,ny=p.y+my*loadoutSpeed(build)*dt;if(!enemies.some(a=>a.alive&&Math.hypot(a.x-nx,a.y-ny)<210))urbanMove(p,nx,ny)}}}const travelled=Math.hypot(p.x-oldX,p.y-oldY);if(build.chassis==='biped')stepBiped(dt,travelled);else stepTrackMotion(p.id||'player',(p.x-oldX)*Math.sin(p.heading)-(p.y-oldY)*Math.cos(p.heading),Math.atan2(Math.sin(p.heading-oldHeading),Math.cos(p.heading-oldHeading)));
 const turn=p.dead||p.ejecting?0:(traverse.right?1:0)-(traverse.left?1:0)+(keys.has('e')?1:0)-(keys.has('q')?1:0);Sound.motion(build.chassis!=='biped'&&travelled>.001?Math.min(1,travelled/(loadoutSpeed(build)*dt||1)):0,Math.min(1,Math.abs(turn)));if(Math.abs(turn)>.08)p.angle+=Math.max(-1,Math.min(1,turn))*TURRET_SPEED*dt;
 if(p.shield>0){p.shield-=dt;p.energy=Math.max(0,p.energy-30*dt);if(p.energy<=0)p.shield=0}else p.energy=Math.min(100,p.energy+12*dt);$('charge').textContent=Math.round(p.energy)+'%';$('shield').classList.toggle('active',p.shield>0);
 if((ejectHeld||keys.has('x'))&&!p.dead&&!p.ejecting){ejectPress+=dt;if(ejectPress>=.45){beginEject();ejectHeld=false;ejectPress=0}}$('eject').textContent=p.dead?'MECH LOST':p.ejecting?'POD AWAY':ejectHeld?'HOLD…':'EJECT';$('eject').style.background=ejectHeld?'#c13722':'';
 for(const slot in cooldown)cooldown[slot]-=dt;stepHeat(dt);if(!repairState&&!p.dead&&!p.ejecting){const supportKey=keys.has('r');if(isLockWeapon()&&supportKey!==missileLock.keyHeld){supportControl(supportKey);missileLock.keyHeld=supportKey}stepLock(dt);for(const[slot,id,offset,key]of [['primary',build.left,-85,' '],['secondary',build.right,85,'f'],['support',build.rear,0,'r']])if(id&&!(slot==='support'&&isLockWeapon())&&(firing[slot]||keys.has(key))&&cooldown[slot]<=.000001&&canFireHeat(slot,id)){fireWeapon(id,offset);addWeaponHeat(slot,id);cooldown[slot]=Math.max(-dt,cooldown[slot])+weaponStats(id,modifications[slot]).rate}}for(const[slot,key]of [['primary','left'],['secondary','right'],['support','rear']]){const id=build[key];if(HEAT_CONFIG[id])continue;const button=$(slot);if(slot==='support'&&missileLock.held)continue;button.textContent=SLOT_LABELS[slot]+(cooldown[slot]>0?'\nRELOAD '+Math.ceil(cooldown[slot])+'s':'')}
}
function renderArena(){const[c,w,h]=resize($('world'));c.fillStyle='#101925';c.fillRect(0,0,w,h);drawStadiumFrame(c,w,h);const view=stadiumView(w,h);c.fillStyle='#293642';c.fillRect(view.x,view.y,view.w,view.h);c.save();c.beginPath();c.rect(view.x,view.y,view.w,view.h);c.clip();c.translate(view.x+view.w/2,view.y+view.h/2);c.scale(view.zoom,view.zoom);c.translate(-ARENA.width/2,-ARENA.height/2);drawUrbanGround(c,w,h);urbanVisible.bounds={x0:0,y0:0,x1:ARENA.width,y1:ARENA.height};drawUrbanDetails(c,w,h);drawUrbanRubble(c);drawUrbanStructures(c);drawUrbanNight(c);drawWeapons(c,false);drawEnemy(c);if(!deployment&&!p.dead&&(!p.ejecting||p.ejecting.age<3.03))mech(c,p.x,p.y,.85,p.heading,p.angle,build,p.parts,build.chassis==='biped'?bipedRig:null);if(p.shield>0){const g=c.createRadialGradient(p.x-25,p.y-35,5,p.x,p.y,145);g.addColorStop(0,'#a7eaff33');g.addColorStop(.8,'#328eff18');g.addColorStop(1,'#60cfff88');c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,142,0,Math.PI*2);c.fill();c.strokeStyle='#76d8ffc0';c.lineWidth=2;c.stroke()}drawUrbanLights(c);drawUrbanEffects(c);drawMechHeadlights(c);drawCrowdShield(c);drawLock(c);if(deployment)drawDeployment(c,w,h);c.restore();c.save();c.translate(view.x+view.w/2,view.y+view.h/2);c.scale(view.zoom,view.zoom);c.translate(-ARENA.width/2,-ARENA.height/2);drawWeaponCosmetics(c);drawSmokeClouds(c);drawLocalLights(c);drawCombatLights(c);drawBlastOverlay(c);c.restore();drawStadiumAtmosphere(c,w,h);c.fillStyle='#c1c9ba';c.font='11px system-ui';c.fillText('v33 · STADIUM 1v1 · HULL '+Math.ceil(p.hp)+(w>650?' · WASD move · Q/E turret · X eject':''),12,20);drawPanelMinimap(w,h);checkProgressVictory();if(p.dead)Sound.pauseMusic();const survivors=[p,...enemies].filter(aliveActor);if(survivors.length===1){c.fillStyle='#e1efe3';c.font='bold 16px system-ui';c.textAlign='center';c.fillText(survivors[0]===p?'YOU WIN':survivors[0].name+' WINS',w/2,46);c.textAlign='start'}if(p.dead){c.fillStyle='#0009';c.fillRect(0,h-65,w,65);c.fillStyle='#ffe2bb';c.font='bold 15px system-ui';c.textAlign='center';c.fillText('MECH LOST · RETURN TO MECH BUILD TO REDEPLOY',w/2,h-30);c.textAlign='start'}}
function frame(t){if(typeof duelActive!=='undefined'&&duelActive){duelFrame(t);return}const dt=document.hidden?0:Math.min((t-last)/1000||0,.035);last=t;Sound.stepMusic(dt);if(inArena&&!document.hidden)stepStadium(dt);updateCrowdAudio();if(ready&&!document.hidden){if(!inArena){const[c,w,h]=resize($('assembly'));c.clearRect(0,0,w,h);mech(c,w/2,h/2-5,Math.min(w/310,h/290),0,0)}else{if(deployment)stepDeployment(dt);else{stepRepair(dt);stepPlayer(dt);stepEnemy(dt);stepWeapons(dt);stepUrban(dt)}updateDiagnostics();renderArena()}}requestAnimationFrame(frame)}
Promise.all(['fx','chassis','turret','duel-ground','duel-roofs','duel-monument','duel-city','stadium-frame','stadium-urban',...URBAN_ASSETS,...BIPED_ASSETS,...side.map(v=>v[0]),...rear.map(v=>v[0])].map(id=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[id]=im;resolve()};im.onerror=()=>reject(id);im.src='assets/'+id+'.png'}))).then(()=>{prepareHitMasks();prepareColourSprites();prepareUrbanSprites();ready=true;$('loading').style.display='none';update();requestAnimationFrame(frame)}).catch(id=>{$('loading').textContent='Asset missing: '+id+'. Please upload the complete assets folder.'});
if('serviceWorker'in navigator&&location.protocol!=='file:'){let reloading=false;const controlled=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(controlled&&!reloading){reloading=true;location.reload()}});navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{})}

// Battle controls must not trigger text selection or the touch context menu.
for(const event of ['selectstart','contextmenu'])document.addEventListener(event,e=>{if(inArena)e.preventDefault()},{capture:true});

// Keep gameplay touches in the game; operating-system gestures remain under iPadOS control.
function lockBattlePage(on){document.body?.classList.toggle('battle-locked',on);document.documentElement?.classList.toggle('battle-locked',on)}
for(const event of ['gesturestart','gesturechange','gestureend','touchmove','dblclick','dragstart'])document.addEventListener(event,e=>{if(inArena&&e.cancelable!==false)e.preventDefault()},{capture:true,passive:false});
window.addEventListener('blur',()=>{if(!inArena||typeof duelActive!=='undefined'&&duelActive)return;stopFiring();keys.clear();input.move={x:0,y:0};ejectHeld=false;ejectPress=0;window.getSelection?.()?.removeAllRanges()});

function stadiumView(w,h){const x=w*.167,y=h*.153,width=w*.668,height=h*.699;return{x,y,w:width,h:height,zoom:Math.min(70/ARENA.mechWidth,width/ARENA.width,height/ARENA.height)}}
function drawStadiumFrame(c,w,h){c.save();c.drawImage(images['stadium-frame'],0,0,w,h);c.restore()}
