'use strict';
const $=id=>document.getElementById(id);
const side=[['machine-gun','Belt-fed machine gun'],['tri-salvo','Tri-salvo rocket launcher'],['rotary','Rotary autocannon'],['siege','Twin siege cannons'],['railgun','Railgun'],['flak','Flak cannon'],['plasma','Plasma cannon'],['pulse','Pulse lasers'],['beam','Heavy beam laser'],['flame','Flamethrower'],['arc','Arc projector'],['emp','EMP launcher']];
const rear=[['swarm','Swarm missiles'],['hunter','Heavy hunter missiles'],['barrage','Rocket barrage'],['mines','Mine dispenser'],['smoke','Smoke-screen launcher'],['mortar','Cluster mortar']];
for(const id of ['left','right','rear'])$(id).innerHTML='<option value="">None</option>'+(id==='rear'?rear:side).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');
const images={};let ready=false,inArena=false,last=0,build={colour:'green',chassis:'chassis',turret:'turret',left:'machine-gun',right:'tri-salvo',rear:'swarm'};
try{const saved=JSON.parse(localStorage.getItem('iron-pit-build-v2'));if(saved)for(const key in build){const allowed=key==='colour'?Object.keys(PALETTES):key==='chassis'?['','chassis']:key==='turret'?['','turret']:['',...(key==='rear'?rear:side).map(x=>x[0])];if(allowed.includes(saved[key]))build[key]=saved[key]}}catch(e){}
for(const key in build){$(key).value=build[key];$(key).onchange=()=>{build[key]=$(key).value;save();update()}}
function save(){try{localStorage.setItem('iron-pit-build-v2',JSON.stringify(build))}catch(e){}}
function update(){refreshMods();$('buildTag').textContent='LIVE ASSEMBLY · '+PALETTES[build.colour].name.toUpperCase();$('turret').options&&($('turret').options[1].textContent='Raised armoured turret · '+PALETTES[build.colour].cockpit.toLowerCase()+' cockpit');$('deploy').disabled=!ready||!build.chassis||!build.turret;$('status').textContent=build.chassis&&build.turret?'Build ready • '+[build.left,build.right,build.rear].filter(Boolean).length+' systems fitted':'Choose a chassis and turret to deploy.'}
function sprite(c,id,x,y,w,h,flip=false,colour='green'){if(!id||!images[id])return;c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(colouredSprite(id,colour),-w/2,-h/2,w,h);c.restore()}
function mech(c,x,y,scale,heading,angle,loadout=build,partHealth=null){c.save();c.translate(x,y);c.scale(scale,scale);c.save();c.rotate(heading);sprite(c,loadout.chassis,0,30,180,170,false,loadout.colour);c.restore();if(loadout.turret){c.rotate(angle);c.save();c.shadowColor='#000b';c.shadowBlur=12;c.shadowOffsetY=7;brokenSprite(c,loadout.turret,0,-12,151,184,false,partHealth?.turret,loadout.colour);c.restore();if(loadout.rear){c.save();c.shadowColor='#000b';c.shadowBlur=5;c.shadowOffsetY=3;brokenSprite(c,loadout.rear,0,52,80,58,false,partHealth?.rear,loadout.colour);c.restore()} // attachment joints face inward for each side
brokenSprite(c,loadout.left,-99,-34,67,154,side.findIndex(v=>v[0]===loadout.left)>=6,partHealth?.left,loadout.colour);
brokenSprite(c,loadout.right,99,-34,67,154,side.findIndex(v=>v[0]===loadout.right)<6,partHealth?.right,loadout.colour);
}c.restore()}
function resize(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d)}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);return [c,r.width,r.height]}
const p={x:1200,y:1200,heading:0,angle:0,energy:100,shield:0},input={move:{x:0,y:0},aim:{x:0,y:0}},effects=[];const firing={primary:false,secondary:false,support:false},cooldown={primary:0,secondary:0,support:0};const ZOOM=.50,TURRET_SPEED=Math.PI/4;function stopFiring(){Sound.stopMotion();clearLock();$('support').textContent='SUPPORT';for(const k in firing)firing[k]=false;if(typeof traverse!=='undefined'){traverse.left=false;traverse.right=false}}
function stick(id){const el=$(id);let pointer=null;function set(e){const r=el.getBoundingClientRect(),radius=r.width/2-20;let x=(e.clientX-r.left-r.width/2)/radius,y=(e.clientY-r.top-r.height/2)/radius;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len}if(id==='aim')y=0;input[id]={x,y};el.querySelector('.knob').style.transform=`translate(${x*radius}px,${y*radius}px)`}el.onpointerdown=e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;el.setPointerCapture(pointer);set(e)};el.onpointermove=e=>{if(e.pointerId===pointer)set(e)};function release(e){if(e.pointerId!==pointer)return;pointer=null;input[id]={x:0,y:0};el.querySelector('.knob').style.transform=''}el.onpointerup=release;el.onpointercancel=release;el.onlostpointercapture=release}
stick('move');const traverse={left:false,right:false};hold('turnLeft',v=>traverse.left=v);hold('turnRight',v=>traverse.right=v);
function hold(id,fn){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);fn(true);b.classList.add('active')};const end=()=>{fn(false);b.classList.remove('active')};b.onpointerup=end;b.onpointercancel=end;b.onlostpointercapture=end}
hold('primary',v=>firing.primary=v);hold('secondary',v=>firing.secondary=v);hold('support',v=>supportControl(v));const cancelSupport=()=>{supportControl(false,true);$('support').classList.remove('active')};$('support').onpointercancel=cancelSupport;$('support').onlostpointercapture=cancelSupport;
$('mute').onclick=()=>Sound.toggle();
$('shield').onclick=()=>{if(p.energy>20&&p.shield<=0)p.shield=3};
$('deploy').onclick=()=>{if(!ready||!build.chassis||!build.turret)return;inArena=true;window.getSelection?.()?.removeAllRanges();$('builder').style.display='none';$('arena').style.display='flex';input.move={x:0,y:0};input.aim={x:0,y:0}};
$('return').onclick=()=>{inArena=false;stopFiring();input.move={x:0,y:0};input.aim={x:0,y:0};$('arena').style.display='none';$('builder').style.display='block'};
$('reset').onclick=()=>{for(const key in build){build[key]=key==='colour'?'green':'';$(key).value=build[key]}save();update()};
const keys=new Set();onkeydown=e=>{if(inArena&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase())};onkeyup=e=>keys.delete(e.key.toLowerCase());onblur=()=>{keys.clear();stopFiring();input.move={x:0,y:0};input.aim={x:0,y:0}};
function frame(t){const dt=Math.min((t-last)/1000||0,.035);last=t;if(ready){if(!inArena){const[c,w,h]=resize($('assembly'));c.clearRect(0,0,w,h);mech(c,w/2,h/2-5,Math.min(w/310,h/290),0,0)}else{let mx=input.move.x,my=input.move.y;if(keys.size){mx+=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft'));my+=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'))}let m=Math.hypot(mx,my);if(m>.08){if(m>1){mx/=m;my/=m}p.heading=Math.atan2(mx,-my);p.x=Math.max(115,Math.min(2285,p.x+mx*260*dt));p.y=Math.max(115,Math.min(2285,p.y+my*260*dt))}const turn=(traverse.right?1:0)-(traverse.left?1:0)+(keys.has('e')?1:0)-(keys.has('q')?1:0);Sound.motion(m>.08?Math.min(1,m):0,Math.min(1,Math.abs(turn)));if(Math.abs(turn)>.08)p.angle+=Math.max(-1,Math.min(1,turn))*TURRET_SPEED*dt;if(p.shield>0){p.shield-=dt;p.energy=Math.max(0,p.energy-30*dt);if(p.energy<=0)p.shield=0}else p.energy=Math.min(100,p.energy+12*dt);$('charge').textContent=Math.round(p.energy)+'%';$('shield').classList.toggle('active',p.shield>0);for(const slot in cooldown)cooldown[slot]-=dt;const supportKey=keys.has('r');if(isLockWeapon()&&supportKey!==missileLock.keyHeld){supportControl(supportKey);missileLock.keyHeld=supportKey}stepLock(dt);for(const [slot,id,offset,key,interval] of [['primary',build.left,-85,' ',.15],['secondary',build.right,85,'f',.15],['support',build.rear,0,'r',1.2]])if(!(slot==='support'&&isLockWeapon())&&(firing[slot]||keys.has(key))&&cooldown[slot]<=0){fireWeapon(id,offset);cooldown[slot]=id?weaponStats(id,modifications[slot]).rate:interval}const[c,w,h]=resize($('world'));c.fillStyle='#272e2b';c.fillRect(0,0,w,h);c.save();c.translate(w/2,h/2);c.scale(ZOOM,ZOOM);c.translate(-p.x,-p.y);c.strokeStyle='#3a4440';c.lineWidth=1;for(let n=0;n<=2400;n+=100){c.beginPath();c.moveTo(n,0);c.lineTo(n,2400);c.moveTo(0,n);c.lineTo(2400,n);c.stroke()}c.strokeStyle='#abb68b';c.lineWidth=18;c.strokeRect(0,0,2400,2400);c.strokeStyle='#566657';c.lineWidth=4;for(let y=300;y<2400;y+=600)for(let x=300;x<2400;x+=600){c.strokeRect(x-60,y-60,120,120);c.fillStyle='#5c695a';c.font='18px system-ui';c.fillText('TEST ZONE',x-50,y+5)}stepEnemy(dt);stepWeapons(dt);drawWeapons(c);drawEnemy(c);mech(c,p.x,p.y,.85,p.heading,p.angle);if(p.shield>0){const g=c.createRadialGradient(p.x-25,p.y-35,5,p.x,p.y,145);g.addColorStop(0,'#a7eaff33');g.addColorStop(.8,'#328eff18');g.addColorStop(1,'#60cfff88');c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,142,0,Math.PI*2);c.fill();c.strokeStyle='#76d8ffc0';c.lineWidth=2;c.stroke()}drawLocalLights(c);drawLock(c);c.restore();c.fillStyle='#c1c9ba';c.font='11px system-ui';c.fillText('2400 × 2400 · WASD / arrows · Q/E traverse · space/F/R weapons',12,20)}}requestAnimationFrame(frame)}
Promise.all(['fx','chassis','turret',...side.map(v=>v[0]),...rear.map(v=>v[0])].map(id=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[id]=im;resolve()};im.onerror=()=>reject(id);im.src='assets/'+id+'.png'}))).then(()=>{prepareHitMasks();prepareColourSprites();ready=true;$('loading').style.display='none';update();requestAnimationFrame(frame)}).catch(id=>{$('loading').textContent='Asset missing: '+id+'. Please upload the complete assets folder.'});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});

// Battle controls must not trigger text selection or the touch context menu.
for(const event of ['selectstart','contextmenu'])document.addEventListener(event,e=>{if(inArena)e.preventDefault()},{capture:true});
