'use strict';
const $=id=>document.getElementById(id);
const side=[['machine-gun','Belt-fed machine gun'],['tri-salvo','Tri-salvo rocket launcher'],['rotary','Rotary autocannon'],['siege','Twin siege cannons'],['railgun','Railgun'],['flak','Flak cannon'],['plasma','Plasma cannon'],['pulse','Pulse lasers'],['beam','Heavy beam laser'],['flame','Flamethrower'],['arc','Arc projector'],['emp','EMP launcher']];
const rear=[['swarm','Swarm missiles'],['hunter','Heavy hunter missiles'],['barrage','Rocket barrage'],['mines','Mine dispenser'],['smoke','Smoke-screen launcher'],['mortar','Cluster mortar']];
for(const id of ['left','right','rear'])$(id).innerHTML='<option value="">None</option>'+(id==='rear'?rear:side).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');
const images={};let ready=false,inArena=false,last=0,build={chassis:'chassis',turret:'turret',left:'machine-gun',right:'tri-salvo',rear:'swarm'};
try{const saved=JSON.parse(localStorage.getItem('iron-pit-build-v2'));if(saved)for(const key in build){const allowed=key==='chassis'?['','chassis']:key==='turret'?['','turret']:['',...(key==='rear'?rear:side).map(x=>x[0])];if(allowed.includes(saved[key]))build[key]=saved[key]}}catch(e){}
for(const key in build){$(key).value=build[key];$(key).onchange=()=>{build[key]=$(key).value;save();update()}}
function save(){try{localStorage.setItem('iron-pit-build-v2',JSON.stringify(build))}catch(e){}}
function update(){$('deploy').disabled=!ready||!build.chassis||!build.turret;$('status').textContent=build.chassis&&build.turret?'Build ready • '+[build.left,build.right,build.rear].filter(Boolean).length+' systems fitted':'Choose a chassis and turret to deploy.'}
function sprite(c,id,x,y,w,h,flip=false){if(!id||!images[id])return;c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(images[id],-w/2,-h/2,w,h);c.restore()}
function mech(c,x,y,scale,heading,angle){c.save();c.translate(x,y);c.scale(scale,scale);c.save();c.rotate(heading);sprite(c,build.chassis,0,30,180,170);c.restore();if(build.turret){c.rotate(angle);if(build.rear)sprite(c,build.rear,0,87,126,110);c.save();c.shadowColor='#000b';c.shadowBlur=12;c.shadowOffsetY=7;sprite(c,build.turret,0,-12,151,184);c.restore(); // attachment joints face inward for each side
sprite(c,build.left,-99,-34,67,154,side.findIndex(v=>v[0]===build.left)>=6);
sprite(c,build.right,99,-34,67,154,side.findIndex(v=>v[0]===build.right)<6);
}c.restore()}
function resize(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d)}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);return [c,r.width,r.height]}
const p={x:1200,y:1200,heading:0,angle:0,energy:100,shield:0},input={move:{x:0,y:0},aim:{x:0,y:0}},effects=[];let fire=false,rearFire=false,shotClock=0,rearClock=0;
function stick(id){const el=$(id);let pointer=null;function set(e){const r=el.getBoundingClientRect(),radius=r.width/2-20;let x=(e.clientX-r.left-r.width/2)/radius,y=(e.clientY-r.top-r.height/2)/radius;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len}input[id]={x,y};el.querySelector('.knob').style.transform=`translate(${x*radius}px,${y*radius}px)`}el.onpointerdown=e=>{if(pointer!==null)return;pointer=e.pointerId;el.setPointerCapture(pointer);set(e)};el.onpointermove=e=>{if(e.pointerId===pointer)set(e)};function release(e){if(e.pointerId!==pointer)return;pointer=null;input[id]={x:0,y:0};el.querySelector('.knob').style.transform=''}el.onpointerup=release;el.onpointercancel=release;el.onlostpointercapture=release}
stick('move');stick('aim');
function hold(id,fn){const b=$(id);b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);fn(true);b.classList.add('active')};const end=()=>{fn(false);b.classList.remove('active')};b.onpointerup=end;b.onpointercancel=end;b.onlostpointercapture=end}
hold('fire',v=>fire=v);hold('special',v=>rearFire=v);
$('shield').onclick=()=>{if(p.energy>20&&p.shield<=0)p.shield=3};
$('deploy').onclick=()=>{if(!ready||!build.chassis||!build.turret)return;inArena=true;$('builder').style.display='none';$('arena').style.display='flex';input.move={x:0,y:0};input.aim={x:0,y:0}};
$('return').onclick=()=>{inArena=false;fire=rearFire=false;input.move={x:0,y:0};input.aim={x:0,y:0};$('arena').style.display='none';$('builder').style.display='block'};
$('reset').onclick=()=>{for(const key in build){build[key]='';$(key).value=''}save();update()};
const keys=new Set();onkeydown=e=>{if(inArena&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase())};onkeyup=e=>keys.delete(e.key.toLowerCase());onblur=()=>{keys.clear();fire=rearFire=false;input.move={x:0,y:0};input.aim={x:0,y:0}};
$('world').onpointermove=e=>{if(e.pointerType==='mouse'){const r=$('world').getBoundingClientRect();p.angle=Math.atan2(e.clientX-r.left-r.width/2,-(e.clientY-r.top-r.height/2))}};
function shoot(id,offset){if(!id)return;const a=p.angle,x=p.x+Math.cos(a)*offset+Math.sin(a)*75,y=p.y+Math.sin(a)*offset-Math.cos(a)*75;effects.push({x,y,a,life:1.6,type:id,v:id==='mines'||id==='smoke'?0:600});if(id==='mines'||id==='smoke'){effects.at(-1).x=p.x-Math.sin(p.heading)*110;effects.at(-1).y=p.y+Math.cos(p.heading)*110;effects.at(-1).life=id==='mines'?20:5}}
function frame(t){const dt=Math.min((t-last)/1000||0,.035);last=t;if(ready){if(!inArena){const[c,w,h]=resize($('assembly'));c.clearRect(0,0,w,h);mech(c,w/2,h/2-5,Math.min(w/310,h/290),0,0)}else{let mx=input.move.x,my=input.move.y;if(keys.size){mx+=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft'));my+=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'))}let m=Math.hypot(mx,my);if(m>.08){if(m>1){mx/=m;my/=m}p.heading=Math.atan2(mx,-my);p.x=Math.max(115,Math.min(2285,p.x+mx*260*dt));p.y=Math.max(115,Math.min(2285,p.y+my*260*dt))}if(Math.hypot(input.aim.x,input.aim.y)>.1)p.angle=Math.atan2(input.aim.x,-input.aim.y);if(p.shield>0){p.shield-=dt;p.energy=Math.max(0,p.energy-30*dt);if(p.energy<=0)p.shield=0}else p.energy=Math.min(100,p.energy+12*dt);$('charge').textContent=Math.round(p.energy)+'%';$('shield').classList.toggle('active',p.shield>0);shotClock-=dt;rearClock-=dt;if((fire||keys.has(' '))&&shotClock<=0){shoot(build.left,-85);shoot(build.right,85);shotClock=.15}if(rearFire&&rearClock<=0){shoot(build.rear,0);rearClock=1.2}const[c,w,h]=resize($('world'));c.fillStyle='#272e2b';c.fillRect(0,0,w,h);c.save();c.translate(w/2-p.x,h/2-p.y);c.strokeStyle='#3a4440';c.lineWidth=1;for(let n=0;n<=2400;n+=100){c.beginPath();c.moveTo(n,0);c.lineTo(n,2400);c.moveTo(0,n);c.lineTo(2400,n);c.stroke()}c.strokeStyle='#abb68b';c.lineWidth=18;c.strokeRect(0,0,2400,2400);c.strokeStyle='#566657';c.lineWidth=4;for(let y=300;y<2400;y+=600)for(let x=300;x<2400;x+=600){c.strokeRect(x-60,y-60,120,120);c.fillStyle='#5c695a';c.font='18px system-ui';c.fillText('TEST ZONE',x-50,y+5)}for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.x+=Math.sin(e.a)*e.v*dt;e.y-=Math.cos(e.a)*e.v*dt;if(e.life<=0){effects.splice(i,1);continue}c.fillStyle=e.type==='smoke'?'#abb8b255':e.type==='mines'?'#c7a95b':['plasma','pulse','beam','arc','emp'].includes(e.type)?'#6ddfff':'#ffcf6a';c.beginPath();c.arc(e.x,e.y,e.type==='smoke'?50:e.type==='mines'?8:4,0,Math.PI*2);c.fill()}mech(c,p.x,p.y,.85,p.heading,p.angle);if(p.shield>0){const g=c.createRadialGradient(p.x-25,p.y-35,5,p.x,p.y,145);g.addColorStop(0,'#a7eaff33');g.addColorStop(.8,'#328eff18');g.addColorStop(1,'#60cfff88');c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,142,0,Math.PI*2);c.fill();c.strokeStyle='#76d8ffc0';c.lineWidth=2;c.stroke()}c.restore();c.fillStyle='#c1c9ba';c.font='11px system-ui';c.fillText('2400 × 2400 · WASD / arrows · mouse aim · space fire',12,20)}}requestAnimationFrame(frame)}
Promise.all(['chassis','turret',...side.map(v=>v[0]),...rear.map(v=>v[0])].map(id=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[id]=im;resolve()};im.onerror=()=>reject(id);im.src='assets/'+id+'.png'}))).then(()=>{ready=true;$('loading').style.display='none';update();requestAnimationFrame(frame)}).catch(id=>{$('loading').textContent='Asset missing: '+id+'. Please upload the complete assets folder.'});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
