'use strict';
const WEAPON_WEIGHT={'machine-gun':2,rotary:5,pulse:4,beam:8,flame:5,arc:6,siege:10,railgun:9,plasma:8,'tri-salvo':6,flak:5,emp:7,swarm:6,hunter:9,barrage:10,mines:4,smoke:3,mortar:8};
const WEAPON_UNLOCK={'machine-gun':0,'tri-salvo':0,mines:0,rotary:1,flak:2,swarm:3,pulse:4,smoke:5,plasma:6,flame:7,siege:8,hunter:9,arc:10,railgun:12,barrage:14,beam:16,emp:18,mortar:20};
function loadoutWeight(b){return ['left','right','rear'].reduce((n,k)=>n+(WEAPON_WEIGHT[b[k]]||0),0)}
function loadoutSpeed(b){return Math.max(b.chassis==='biped'?110:100,(b.chassis==='biped'?220:170)-loadoutWeight(b)*(b.chassis==='biped'?3:1.7))}
let victoryProfiles=[{wins:0},{wins:0}],testLoadouts=false,matchProgress=null;
try{const v=JSON.parse(localStorage.getItem('iron-pit-victories'));if(Array.isArray(v)&&v.length===2)victoryProfiles=v.map(p=>({wins:Math.max(0,Math.floor(Number(p.wins)||0))}));testLoadouts=localStorage.getItem('iron-pit-test-loadouts')==='true'}catch(e){}
function builderProfile(){return typeof buildTurn!=='undefined'&&buildTurn===1?1:0}
function weaponAvailable(id,profile=builderProfile()){return !id||testLoadouts||victoryProfiles[profile].wins>=WEAPON_UNLOCK[id]}
function initialiseProgressMatch(duel){matchProgress={duel,test:testLoadouts,recorded:false}}
function checkProgressVictory(){if(!matchProgress||matchProgress.recorded)return;const actors=typeof duelActive!=='undefined'&&duelActive?duelPlayers.map(s=>s.actor):[p,...enemies],survivors=actors.filter(aliveActor);if(survivors.length!==1||actors.some(a=>a.ejecting&&!a.dead))return;const winner=survivors[0];if(rounds.some(r=>r.owner!==winner)||launchQueue.some(q=>q.owner!==winner))return;matchProgress.recorded=true;if(matchProgress.test||!(winner.human||winner===p))return;const profile=winner.human?winner.duelIndex:0;victoryProfiles[profile].wins++;try{localStorage.setItem('iron-pit-victories',JSON.stringify(victoryProfiles))}catch(e){}updateProgressDisplay()}
function updateProgressDisplay(){document.getElementById('progressSummary').textContent='PLAYER 1: '+victoryProfiles[0].wins+' WINS · PLAYER 2: '+victoryProfiles[1].wins+' WINS';document.getElementById('testLoadouts').checked=testLoadouts}
function refreshWeaponAccess(){for(const key of ['left','right','rear']){const select=document.getElementById(key);for(const option of Array.from(select.options)){const id=option.value;if(!id)continue;const label=(key==='rear'?rear:side).find(v=>v[0]===id)?.[1]||id;option.disabled=!weaponAvailable(id);option.textContent=label+' · '+WEAPON_WEIGHT[id]+' wt'+(option.disabled?' · '+WEAPON_UNLOCK[id]+' wins to unlock':'')}if(!weaponAvailable(build[key])){build[key]='';select.value=''}}document.getElementById('loadoutReadout').textContent='WEAPON WEIGHT '+loadoutWeight(build)+' · SPEED '+Math.round(loadoutSpeed(build))+' units/sec · '+(testLoadouts?'TEST: ALL UNLOCKED':'PLAYER '+(builderProfile()+1)+' · '+victoryProfiles[builderProfile()].wins+' WINS');if(typeof syncBuildPickers==='function')syncBuildPickers()}
