'use strict';
const missileLock={held:false,progress:0,target:null,ready:false,tone:null,nextTone:0,keyHeld:false};
function isLockWeapon(){return ['swarm','hunter'].includes(build.rear)}
function clearLock(){missileLock.keyHeld=false;missileLock.nextTone=0;document.getElementById('support').textContent='SUPPORT';missileLock.held=false;missileLock.progress=0;missileLock.target=null;missileLock.ready=false;if(missileLock.tone){try{missileLock.tone.stop()}catch(e){}missileLock.tone=null}}
function supportControl(down,cancel=false){if(p.dead||p.ejecting||p.parts?.rear===0||p.parts?.turret===0){clearLock();return}if(!isLockWeapon()){firing.support=down;return}if(down){if(cooldown.support>0)return;missileLock.held=true;missileLock.progress=0;missileLock.target=null;missileLock.ready=false}else{if(missileLock.held&&!cancel){if(cooldown.support<=0){fireWeapon(build.rear,0,missileLock.ready&&lockCandidate()===missileLock.target?missileLock.target:null);cooldown.support=weaponStats(build.rear,modifications.support).rate}}clearLock()}}
function lockCandidate(){if(p.parts?.rear===0||p.parts?.turret===0)return null;const candidates=enemies.filter(a=>a.alive).map(a=>({a,d:Math.hypot(a.x-p.x,a.y-p.y),diff:Math.atan2(Math.sin(Math.atan2(a.x-p.x,-(a.y-p.y))-p.angle),Math.cos(Math.atan2(a.x-p.x,-(a.y-p.y))-p.angle))})).filter(v=>v.d<=950&&Math.abs(v.diff)<=.20&&!smokeObscures(p.x,p.y,v.a.x,v.a.y)).sort((a,b)=>a.d-b.d);for(const v of candidates){const hit=sweepHit(p.x,p.y,v.a.x,v.a.y);if(!hit||hit.target===v.a)return v.a}return null}
function stepLock(dt){if(!missileLock.held)return;const candidate=lockCandidate();if(!candidate||candidate!==missileLock.target){missileLock.progress=0;missileLock.ready=false;missileLock.target=candidate}if(candidate){missileLock.progress=Math.min(1,missileLock.progress+dt);if(missileLock.progress>=1&&!missileLock.ready){missileLock.ready=true;lockBeep(1100,.15)}else if(!missileLock.ready){missileLock.nextTone-=dt;if(missileLock.nextTone<=0){lockBeep(400+missileLock.progress*450,.045);missileLock.nextTone=.18}}}document.getElementById('support').textContent=missileLock.ready?'LOCKED':candidate?'LOCK '+Math.round(missileLock.progress*100)+'%':'SEEKING'}
function lockBeep(freq,duration){if(typeof Sound==='undefined'||Sound.muted||!Sound.context||Sound.context.state!=='running')return;const c=Sound.context,o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g);g.connect(Sound.dry);o.start();o.stop(c.currentTime+duration);o.onended=()=>{o.disconnect();g.disconnect()}}
function drawLock(c){if(!missileLock.held)return;c.save();c.strokeStyle=missileLock.ready?'#9bff91':'#ffd874';c.lineWidth=2;if(missileLock.target){const e=missileLock.target;c.beginPath();c.arc(e.x,e.y,130,-Math.PI/2,-Math.PI/2+missileLock.progress*Math.PI*2);c.stroke();c.fillStyle=c.strokeStyle;c.font='13px system-ui';c.fillText(missileLock.ready?'LOCKED · RELEASE TO FIRE':'ACQUIRING',e.x-70,e.y-165)}c.globalAlpha=.3;c.beginPath();c.moveTo(p.x,p.y);for(const a of [p.angle-.2,p.angle+.2])c.lineTo(p.x+Math.sin(a)*700,p.y-Math.cos(a)*700);c.closePath();c.stroke();c.restore()}
