'use strict';
// Short, telegraphed arena hazards. Flame animation is a reusable 16-frame atlas.
let perimeterJets=[],perimeterWait=6,flameAtlas=null;
const PERIMETER={warning:.65,length:390,damage:85,maxActive:2};
function resetPerimeter(){for(const j of perimeterJets)Sound.stopLoop('perimeter-'+j.id);perimeterJets=[];perimeterWait=5+Math.random()*3;if(arenaMode!=='solo')return;for(let i=0;i<3;i++){const y=ARENA.height*(.22+i*.28);perimeterJets.push({id:'l'+i,x:24,y,a:Math.PI/2,age:-1,duration:1},{id:'r'+i,x:ARENA.width-24,y,a:-Math.PI/2,age:-1,duration:1})}for(const side of [-1,1])for(const u of [.3,.7])perimeterJets.push({id:'e'+side+u,x:ARENA.width*u,y:side<0?24:ARENA.height-24,a:side<0?Math.PI:0,age:-1,duration:1})}
function perimeterActive(j){return j.age>=PERIMETER.warning&&j.age<PERIMETER.warning+j.duration}
function perimeterReach(j){const dx=Math.sin(j.a),dy=-Math.cos(j.a),hit=urbanSweep(j.x,j.y,j.x+dx*PERIMETER.length,j.y+dy*PERIMETER.length);return hit?Math.hypot(hit.x-j.x,hit.y-j.y):PERIMETER.length}
function perimeterContains(j,a){const dx=a.x-j.x,dy=a.y-j.y,forward=dx*Math.sin(j.a)-dy*Math.cos(j.a),side=dx*Math.cos(j.a)+dy*Math.sin(j.a),range=perimeterReach(j);return forward>=-25&&forward<range+60&&Math.abs(side)<28+Math.max(0,forward)*.15+55&&!urbanSweep(j.x,j.y,a.x,a.y)}
function stepPerimeter(dt){if(!inArena||arenaMode!=='solo'||battleFinished()||deployment||[p,...enemies].filter(aliveActor).length<2){for(const j of perimeterJets)Sound.stopLoop('perimeter-'+j.id);return}perimeterWait-=dt;if(perimeterWait<=0){const idle=perimeterJets.filter(j=>j.age<0);const count=perimeterJets.filter(j=>j.age>=0).length;if(idle.length&&count<PERIMETER.maxActive){const j=idle[Math.floor(Math.random()*idle.length)];j.age=0;j.duration=.8+Math.random()*.4;j.smoke=0;Sound.play('flame-start',j.x,j.y,.7,1,true)}perimeterWait=3+Math.random()*5}
for(const j of perimeterJets){if(j.age<0)continue;j.age+=dt;if(perimeterActive(j)){Sound.loop('fire-flame','perimeter-'+j.id,j.x,j.y,.9,1);for(const actor of [p,...enemies])if(aliveActor(actor)&&perimeterContains(j,actor)){if(shielded(actor))absorbShield(actor,PERIMETER.damage*dt);else enemyHit('flame',{damage:PERIMETER.damage*dt,penetration:1},1,true,'hull',actor)}j.smoke-=dt;if(j.smoke<=0){const r=perimeterReach(j);smokePuff(j.x+Math.sin(j.a)*r,j.y-Math.cos(j.a)*r,30,2.5);j.smoke=.16}}else Sound.stopLoop('perimeter-'+j.id);if(j.age>=PERIMETER.warning+j.duration+2.5)j.age=-1}}
function perimeterTexture(){if(flameAtlas)return flameAtlas;const atlas=document.createElement('canvas');atlas.width=256*4;atlas.height=128*4;const c=atlas.getContext('2d');for(let f=0;f<16;f++){c.save();c.translate((f%4)*256,Math.floor(f/4)*128+64);c.beginPath();c.rect(0,-64,256,128);c.clip();c.globalCompositeOperation='screen';c.lineCap='round';c.lineJoin='round';const t=f/16;for(let layer=0;layer<4;layer++){c.save();c.filter='blur('+[7,4,2,1][layer]+'px)';for(let k=0;k<13;k++){const frac=k/12,sign=k%2?1:-1,L=220*(.78+.22*Math.sin(k*17+t*Math.PI*2)**2);c.beginPath();for(let n=0;n<=30;n++){const u=n/30,x=6+u*L,wave=Math.sin(u*18-t*Math.PI*4+k*1.4)+.45*Math.sin(u*37-t*Math.PI*6+k*3),y=sign*frac*(3+u*29)+wave*(1+u*9)*Math.sin(u*Math.PI);n?c.lineTo(x,y):c.moveTo(x,y)}const g=c.createLinearGradient(6,0,L+6,0);g.addColorStop(0,['rgba(255,99,8,.35)','rgba(255,135,16,.5)','rgba(255,203,70,.65)','rgba(255,252,207,.9)'][layer]);g.addColorStop(.4,['rgba(244,70,4,.25)','rgba(255,143,17,.35)','rgba(255,198,72,.4)','rgba(255,232,141,.4)'][layer]);g.addColorStop(.8,'rgba(240,76,5,'+(.13*(4-layer))+')');g.addColorStop(1,'rgba(225,50,0,0)');c.strokeStyle=g;c.lineWidth=[19,13,7,3][layer]*(1-frac*.35);c.stroke()}c.restore()}c.restore()}flameAtlas=atlas;return atlas}
function drawPerimeter(c){if(arenaMode!=='solo'||!perimeterJets.length)return;for(const j of perimeterJets){c.save();c.translate(j.x,j.y);c.rotate(j.a);c.fillStyle='#182026';c.strokeStyle='#78817c';c.lineWidth=3;c.fillRect(-65,35,130,115);c.strokeRect(-65,35,130,115);c.fillStyle='#d0ae48';for(const x of [-58,48])c.fillRect(x,43,10,20);for(const x of [-54,54])for(const y of [43,140]){c.fillStyle='#89908b';c.beginPath();c.arc(x,y,3,0,7);c.fill()}sprite(c,'flame',0,72,140,166);const warning=j.age>=0&&j.age<PERIMETER.warning,active=perimeterActive(j)&&!battleFinished(),lamp=warning&&(Math.sin(j.age*35)>0)||active;c.fillStyle=lamp?'#ffd25d':'#4b422d';c.shadowColor='#ffb329';c.shadowBlur=lamp?18:0;c.fillRect(-50,26,7,10);c.shadowBlur=0;if(warning){stadiumGlow(c,0,-12,12,'255,130,40',.45)}c.restore();if(active){const age=j.age-PERIMETER.warning,strength=Math.min(1,age*12,(j.duration-age)*12),range=perimeterReach(j),atlas=perimeterTexture(),f=Math.floor(urbanClock*24+j.y)%16;c.save();c.translate(j.x,j.y);c.rotate(j.a-Math.PI/2);stadiumGlow(c,range*.35,0,range*.8,'255,126,15',.28*strength);c.globalCompositeOperation='screen';c.drawImage(atlas,f%4*256,Math.floor(f/4)*128,256,128,0,-range*.26,range*strength,range*.52);c.restore()}}}
