'use strict';
// Screen-space stadium atmosphere; cosmetic effects never affect collision or damage.
let victorySequence=null,stadiumSequence=null,stadiumClock=0,crowdHitWait=0,crowdDuck=0;
const FIREWORK_STARTS=[2.9,3.3,3.8,4.35,5];
function stadiumSound(name,gain=1,offset=0){const listener=duelActive?{x:ARENA.width/2,y:ARENA.height/2}:p;Sound.play(name,listener.x,listener.y,gain,1,true,offset)}
function resetStadium(){victorySequence=null;stadiumSequence=null;stadiumClock=0;crowdHitWait=0;crowdDuck=0;Sound.stopLoop('stadium-crowd')}
function beginStadiumCountdown(){if(stadiumSequence)return;stadiumSequence={age:0,events:new Set()};stadiumSound('stadium-countdown',1.2);stadiumSound('stadium-siren',.65)}
function crowdHitReaction(){if(!inArena||crowdHitWait>0||crowdDuck>0)return;crowdHitWait=4;stadiumSound('crowd-hit',.8)}
function crowdDestroyReaction(){if(!inArena||crowdDuck>6)return;crowdDuck=7;crowdHitWait=7;stadiumSound('crowd-cheer',1.35)}
function stepStadium(dt){stadiumClock+=dt;if(battleResult)battleResult.age+=dt;stepVictoryCelebration(dt);stepWinnerAnnouncement(dt);crowdHitWait=Math.max(0,crowdHitWait-dt);crowdDuck=Math.max(0,crowdDuck-dt);if(!stadiumSequence)return;const s=stadiumSequence;s.age+=dt;FIREWORK_STARTS.forEach((start,i)=>{if(s.age>=start&&!s.events.has('launch'+i)){s.events.add('launch'+i);stadiumSound('firework-launch',.75)}if(s.age>=start+.85&&!s.events.has('burst'+i)){s.events.add('burst'+i);stadiumSound('firework-bang',.95)}})}
function stadiumGlow(c,x,y,r,col,a){if(a<=0)return;const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba('+col+','+a+')');g.addColorStop(1,'rgba('+col+',0)');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2)}
function drawStadiumAtmosphere(c,w,h){const s=victorySequence||stadiumSequence,t=s?.age??-1,v=arenaMode==='solo'?stadiumView(w,h):{x:(w-ARENA.width*Math.min(w/ARENA.width,h/ARENA.height))/2,y:(h-ARENA.height*Math.min(w/ARENA.width,h/ARENA.height))/2,w:ARENA.width*Math.min(w/ARENA.width,h/ARENA.height),h:ARENA.height*Math.min(w/ARENA.width,h/ARENA.height)},x0=v.x,y0=v.y,x1=v.x+v.w,y1=v.y+v.h;const flares=[[.075,.33,'255,65,35'],[.925,.6,'60,155,255'],[.33,.065,'255,65,95'],[.66,.925,'75,255,160']];c.save();for(const[x,y,col]of arenaMode==='solo'?flares:[]){const xx=x*w,yy=y*h;stadiumGlow(c,xx,yy,18,col,.38);stadiumGlow(c,xx,yy,3,'255,245,225',.9);for(let j=0;j<7;j++){const age=(stadiumClock+j*.53)%3.7;stadiumGlow(c,xx+age*w*.009+Math.sin(j+stadiumClock)*3,yy-age*h*.018,5+age*5,col,.07*(1-age/3.7))}}
 if(!victorySequence&&t>=0&&t<4.9){const red=t<2.9,lit=red?[0,1.1,2].some(at=>t>=at&&t<at+.24):true,a=red?(lit?1:0):Math.max(0,1-(t-2.9)/2),col=red?'255,30,25':'55,255,115';const lamps=[];for(let i=0;i<12;i++){const u=(i+.5)/12;lamps.push([x0+(x1-x0)*u,y0-5],[x0+(x1-x0)*u,y1+5])}for(let i=0;i<14;i++){const u=(i+.5)/14;lamps.push([x0-5,y0+(y1-y0)*u],[x1+5,y0+(y1-y0)*u])}for(const[x,y]of lamps){stadiumGlow(c,x,y,24,col,a*.6);c.fillStyle='rgba('+col+','+a+')';c.fillRect(x-3,y-2,6,4)}}
 const warning=fieldWarningLights();if(warning){for(let i=0;i<14;i++)for(const x of [x0-6,x1+6]){const y=y0+(i+.5)/14*(y1-y0);stadiumGlow(c,x,y,25,warning.colour,warning.alpha*.65);c.fillStyle='rgba('+warning.colour+','+warning.alpha+')';c.fillRect(x-3,y-5,6,10)}}
 const launches=[[.08,.14,.25,.27,'255,110,55'],[.92,.85,.74,.67,'75,170,255'],[.92,.13,.73,.3,'255,70,135'],[.08,.85,.27,.69,'80,255,160'],[.5,.055,.5,.23,'255,220,90']];if(victorySequence)launches.push([.08,.5,.27,.45,'255,170,65'],[.92,.45,.73,.48,'115,150,255'],[.3,.94,.35,.73,'90,255,170'],[.7,.06,.65,.25,'255,90,120'],[.9,.92,.7,.72,'255,225,90']);if(s)launches.forEach(([x,y,bx,by,col],i)=>{const age=t-(victorySequence?VICTORY_FIREWORK_STARTS:FIREWORK_STARTS)[i];if(age<0||age>3)return;x*=w;y*=h;bx*=w;by*=h;if(age<.85){const u=age/.85,tail=Math.max(0,u-.25),xx=x+(bx-x)*u,yy=y+(by-y)*u;c.strokeStyle='rgba('+col+',.8)';c.lineWidth=2;c.beginPath();c.moveTo(x+(bx-x)*tail,y+(by-y)*tail);c.lineTo(xx,yy);c.stroke();stadiumGlow(c,xx,yy,6,'255,245,220',.9)}else{const a=age-.85,fade=Math.max(0,1-a/2.15),r=Math.min(w,h)*.11*(1-Math.exp(-a*2.8));if(a<.2)stadiumGlow(c,bx,by,Math.min(w,h)*.22,col,(1-a/.2)*.45);c.strokeStyle='rgba('+col+','+fade+')';c.lineWidth=1.4;for(let k=0;k<60;k++){const angle=k*2.39996,rr=r*(.45+.55*((k*37)%67)/67);c.beginPath();c.moveTo(bx+Math.cos(angle)*rr*.78,by+Math.sin(angle)*rr*.78);c.lineTo(bx+Math.cos(angle)*rr,by+Math.sin(angle)*rr);c.stroke()}stadiumGlow(c,bx+a*8,by-a*4,18+a*22,'145,151,162',fade*.12)}});c.restore()}

document.addEventListener('visibilitychange',()=>{if(!document.hidden&&inArena&&stadiumSequence){const age=stadiumSequence.age;if(age<3.76)stadiumSound('stadium-countdown',1.2,age);if(age<4.6)stadiumSound('stadium-siren',.65,age)}});

const VICTORY_FIREWORK_STARTS=[.2,.65,1.1,5.1,5.55,6,6.5,7,7.6,8.2];
function beginVictoryCelebration(){victorySequence={age:0,events:new Set()};crowdDuck=Math.max(crowdDuck,10)}
function stepVictoryCelebration(dt){const s=victorySequence;if(!s)return;s.age+=dt;VICTORY_FIREWORK_STARTS.forEach((start,i)=>{if(s.age>=start&&!s.events.has('launch'+i)){s.events.add('launch'+i);stadiumSound('firework-launch',.48,0)}if(s.age>=start+.9&&!s.events.has('burst'+i)){s.events.add('burst'+i);stadiumSound('firework-bang',.65,0)}})}
