'use strict';
let trainingActive=false,trainingState=null,trainingSnapshot=null;
const TRAINING_SAVE='iron-pit-training-v1';
const TRAINING_STEPS=[
 ['move','DRIVE THE MECH','Use the left stick. Drive through the two green checkpoints.'],
 ['turnRight','TURN THE TURRET','Use the turret buttons. Point the nose toward the training target.'],
 ['primary','WPN 1 · CONTROLLED BURSTS','Hit the target with the machine gun. Red filling means heat; release to cool.'],
 ['secondary','WPN 2 · ROCKET SALVO','Hit the target with your rockets. Each rocket has a separate launch.'],
 ['support','WPN 3 · MINE DISPENSER','Press WPN 3. Five mines spin backwards and beep when armed.'],
 ['shield','SHIELD DRILL','Press SHIELD as the training shots arrive. The blue dome absorbs them.'],
 ['repair','FIELD REPAIR','Press REPAIR. Weapons power down for five seconds while health recovers.'],
 ['move','FORCEFIELD WARNING','Yellow marks show the next walls. Drive into the green safe circle before they turn red.'],
 ['primary','PRACTICE DUEL','Destroy the practice mech. Move, aim and fire one system at a time.'],
 ['eject','ESCAPE POD DRILL','Hold EJECT. Your pod launches, drops in an arc, then opens its parachute.']
];
function trainingCompleted(){try{return localStorage.getItem(TRAINING_SAVE)==='complete'}catch(e){return false}}
function trainingOverlay(){let el=node('trainingOverlay');if(el)return el;el=document.createElement('aside');el.id='trainingOverlay';el.hidden=true;el.innerHTML='<img alt="Dave"><div><small>TRAINING LINK · DAVE</small><strong id="trainingTitle"></strong><p id="trainingCopy"></p></div><button id="trainingSkip">SKIP TRAINING</button>';node('arena').appendChild(el);node('trainingSkip').onclick=()=>endTraining(false);return el}
function startPilotTraining(after=null){if(!ready)return;if(trainingActive)endTraining(false);if(duelActive)leaveDuel();resetBattleInputs();trainingSnapshot={build:{...build},mods:{...modifications},mode:selectedMode,arena:arenaKind,opponents:selectedOpponents,campaign:campaignActive,bots:BOT_ACTORS.map(a=>({name:a.name,loadout:{...a.loadout},ai:a.ai})),after};campaignActive=false;selectedMode='1';selectedOpponents=1;arenaKind='desert';setArenaMode('solo');build={...rookieLoadout('tank-light','machine-gun','tri-salvo','mines','green')};modifications={primary:'standard',secondary:'standard',support:'standard'};hideGameMenus();storyScreen().hidden=true;trainingActive=true;trainingState={stage:0,age:0,checkpoint:0,hits:new Set(),absorbed:false,shotWait:1,repairStarted:false,safe:false,finishWait:0};node('deploy').onclick();matchProgress.test=true;enemy.name='TRAINING TARGET';enemy.loadout=rookieLoadout('tank-light','machine-gun','','','red');enemy.ai={reaction:1.5,burst:.3,turn:.5,standOff:650};fieldState=null;perimeterJets=[];trainingOverlay().hidden=false;setTrainingStage(0)}
function trainingTarget(){enemy.alive=true;enemy.dead=false;enemy.ejecting=null;resetParts(enemy);enemy.x=ARENA.width/2;enemy.y=ARENA.height*.30;enemy.heading=enemy.angle=Math.PI;enemy.shield=false;enemy.energy=100;enemy.burnTime=0;enemy.reaction=2;enemy.path=[];enemy.target=null}
function setTrainingStage(stage){resetBattleInputs();trainingState.stage=stage;trainingState.age=0;trainingState.hits.clear();for(const e of document.querySelectorAll('.tutorial-focus'))e.classList.remove('tutorial-focus');const[id,title,copy]=TRAINING_STEPS[stage];node(id).classList.add('tutorial-focus');if(stage===1)node('turnLeft').classList.add('tutorial-focus');node('trainingTitle').textContent=(stage+1)+' / '+TRAINING_STEPS.length+' · '+title;node('trainingCopy').textContent='“'+copy+'”';trainingOverlay().querySelector('img').src=portraitFor('dave');commsSound('comms-in');clearCombatFx();for(const s in cooldown)cooldown[s]=0;resetHeat();
 if(stage<=3){trainingTarget();if(stage===1){p.x=ARENA.width/2;p.y=ARENA.height*.72;p.angle=-.65}}
 if(stage===4){p.angle=0;enemy.x=ARENA.width*.85;enemy.y=ARENA.height*.2}
 if(stage===5){trainingTarget();enemy.x=p.x;enemy.y=p.y-530;p.hp=Math.max(500,p.hp);p.parts.hull=p.hp;p.energy=100;trainingState.shotWait=.8}
 if(stage===6){clearCombatFx();p.hp=500;p.parts.hull=p.hp;p.shield=0;repairUses=2;trainingState.repairStarted=false}
 if(stage===7){const g=fieldCell(),o=fieldOrigin(),wall={key:'training-wall',x:o.x+g-9,y:o.y+g,w:18,h:g};p.x=wall.x+9;p.y=wall.y+g*.5;enemy.x=ARENA.width*.85;enemy.y=ARENA.height*.20;fieldState={age:10,walls:[],next:[wall],flash:0};trainingState.safeGoal={x:wall.x+g*.48,y:p.y};trainingState.safe=false}
 if(stage===8){fieldState=null;trainingTarget();enemy.hp=240;enemy.parts.hull=240;p.hp=700;p.parts.hull=700;p.energy=100;p.x=ARENA.width/2;p.y=ARENA.height*.72;enemy.name='PRACTICE MECH';enemy.reaction=1.5}
 if(stage===9){fieldState=null;p.energy=100;p.hp=Math.max(200,p.hp);p.parts.hull=p.hp;enemy.alive=false}
 updateDiagnostics();
}
function endTraining(complete){if(!trainingActive)return;const saved=trainingSnapshot;resetBattleInputs();trainingActive=false;trainingState=null;trainingSnapshot=null;trainingOverlay().hidden=true;for(const e of document.querySelectorAll('.tutorial-focus'))e.classList.remove('tutorial-focus');cancelDeployment();stopRepair();stopFiring();Sound.stopAll();clearCombatFx();resetBattleResult();inArena=false;lockBattlePage(false);node('arena').style.display='none';build={...saved.build};modifications={...saved.mods};selectedMode=saved.mode;selectedOpponents=saved.opponents;arenaKind=saved.arena;campaignActive=saved.campaign;for(let i=0;i<BOT_ACTORS.length;i++)Object.assign(BOT_ACTORS[i],saved.bots[i]);if(complete)try{localStorage.setItem(TRAINING_SAVE,'complete')}catch(e){}update();if(saved.after)saved.after();else showLevelSelect();}
const tutorialButton=document.createElement('button');tutorialButton.id='pilotTraining';tutorialButton.textContent='PILOT TRAINING · LEARN THE CONTROLS';tutorialButton.onclick=()=>startPilotTraining();node('championshipStart').after(tutorialButton);
const trainingLadder=showRookieLadder;showRookieLadder=function(){trainingLadder();const qualifier=node('storyBody').querySelector('[data-mission="0"]');if(qualifier&&!trainingCompleted()&&rookieProgress.completed===0){const play=qualifier.onclick;qualifier.onclick=()=>showStoryDialogue([['dave','Before we send you into a qualifier, let’s make sure you can drive this thing. Movement, weapons, shield, repair and an escape drill.']],()=>{const offer=document.createElement('div');offer.id='trainingOffer';offer.className='training-offer';offer.innerHTML='<h2>PILOT TRAINING</h2><p>Hands-on practice. No victories or equipment rewards.</p><button class="ready-flash">START TRAINING</button><button class="skip">SKIP · ENTER QUALIFIER</button>';node('storyBody').replaceChildren(offer);offer.querySelector('.ready-flash').onclick=()=>startPilotTraining(play);offer.querySelector('.skip').onclick=play},{title:'Pilot Training',round:'BOOT CAMP',arena:'desert',brief:'Training is optional and can be replayed from Mission Select.'})}};
const trainingEnemy=stepEnemy;stepEnemy=function(dt){if(!trainingActive)return trainingEnemy(dt);if(deployment)return;const s=trainingState;if(s.stage===8){trainingEnemy(dt);return}if(s.stage===5){s.shotWait-=dt;if(s.shotWait<=0){enemy.angle=Math.atan2(p.x-enemy.x,-(p.y-enemy.y));withShooter(enemy,()=>fireWeapon('machine-gun',-85));s.shotWait=.35}}};
const trainingHit=enemyHit;enemyHit=function(id,stats,falloff,tick,part,actor=enemy){const before=actor.hp;trainingHit(id,stats,falloff,tick,part,actor);if(trainingActive&&actor===enemy&&actor.hp<before&&damageSource===p)trainingState.hits.add(id)};
const trainingAbsorb=absorbShield;absorbShield=function(actor,damage){trainingAbsorb(actor,damage);if(trainingActive&&trainingState.stage===5&&actor===p&&damage>0)trainingState.absorbed=true};
const trainingRepair=beginRepair;beginRepair=function(){trainingRepair();if(trainingActive&&trainingState.stage===6&&repairState)trainingState.repairStarted=true};
const trainingProgress=checkProgressVictory;checkProgressVictory=function(){if(!trainingActive)trainingProgress()};
const trainingFields=stepFields;stepFields=function(dt){if(!trainingActive)return trainingFields(dt);if(trainingState.stage!==7||trainingState.safe)return;const s=fieldState;s.age+=dt;if(s.age>=15){const clear=!fieldOverlap(p.x,p.y,ARENA.radius+20,s.next);if(clear){trainingState.safe=true;s.walls=s.next;s.next=null;s.flash=.8;fieldRevision++;Sound.stopLoop('field-warning')}else{resetBattleInputs();p.x=s.next[0].x+9;p.y=s.next[0].y+fieldCell()*.5;s.age=10;node('trainingCopy').textContent='“That wall would destroy your mech in battle. Try again: move into the green circle.”'}}else Sound.loop('stadium-siren','field-warning',p.x,p.y,.75,1)};
const trainingPerimeter=stepPerimeter;stepPerimeter=function(dt){if(!trainingActive)trainingPerimeter(dt)};
function stepTraining(dt){if(!trainingActive||deployment)return;const s=trainingState;s.age+=dt;let advance=false;
 if(s.stage===0){const goals=[{x:ARENA.width*.62,y:ARENA.height*.76},{x:ARENA.width*.5,y:ARENA.height*.68}],g=goals[s.checkpoint];if(g&&Math.hypot(p.x-g.x,p.y-g.y)<95)s.checkpoint++;advance=s.checkpoint===goals.length}
 if(s.stage===1){const desired=Math.atan2(enemy.x-p.x,-(enemy.y-p.y));advance=Math.abs(Math.atan2(Math.sin(desired-p.angle),Math.cos(desired-p.angle)))<.13&&s.age>.5}
 if(s.stage===2)advance=s.hits.has('machine-gun');if(s.stage===3)advance=s.hits.has('tri-salvo');if(s.stage===4)advance=mines.filter(m=>m.owner===p&&m.armed<=0).length>=5;
 if(s.stage===5)advance=s.absorbed;if(s.stage===6){if(repairState)s.repairStarted=true;advance=s.repairStarted&&!repairState&&p.hp>=649;}if(s.stage===7)advance=s.safe&&Math.hypot(p.x-s.safeGoal.x,p.y-s.safeGoal.y)<110;if(s.stage===8)advance=!enemy.alive;
 if(s.stage===9&&p.dead){s.finishWait+=dt;if(s.finishWait>5){endTraining(true);return}}
 if(advance)setTrainingStage(s.stage+1);if(p.dead&&s.stage!==9){p.dead=false;p.ejecting=null;p.hp=700;resetParts(p);clearCombatFx();node('trainingCopy').textContent='“Training reset. You’re safe—let’s try that drill again.”'}
}
const trainingWeapons=stepWeapons;stepWeapons=function(dt){trainingWeapons(dt);stepTraining(dt)};
const trainingStadiumDraw=drawStadiumAtmosphere;drawStadiumAtmosphere=function(c,w,h){trainingStadiumDraw(c,w,h);if(!trainingActive)return;const s=trainingState,v=stadiumView(w,h);let goal=null;if(s.stage===0)goal=[{x:ARENA.width*.62,y:ARENA.height*.76},{x:ARENA.width*.5,y:ARENA.height*.68}][s.checkpoint];if(s.stage===7)goal=s.safeGoal;if(goal){const x=v.x+goal.x*v.zoom,y=v.y+goal.y*v.zoom;c.save();stadiumGlow(c,x,y,35,'100,255,150',.3);c.strokeStyle='#9affbd';c.lineWidth=2;c.beginPath();c.arc(x,y,95*v.zoom,0,Math.PI*2);c.stroke();c.font='bold 11px monospace';c.fillStyle='#d7ffe3';c.textAlign='center';c.fillText(s.stage===7?'SAFE AREA':'CHECKPOINT',x,y-100*v.zoom);c.restore()}};
const trainingReturn=node('return').onclick;node('return').onclick=()=>trainingActive?endTraining(false):trainingReturn();
// Training keeps unrelated actions offline until their drill, so a stray tap
// cannot destroy the target or eject the pilot before the lesson is ready.
const trainingPanel=updateBattlePanel;updateBattlePanel=function(){trainingPanel();if(!trainingActive||deployment)return;const stage=trainingState.stage,allowed={primary:stage===2||stage===8,secondary:stage===3||stage===8,support:stage===4||stage===8,shield:stage===5||stage===8,repair:stage===6||stage===8,eject:stage===9};for(const[id,ok]of Object.entries(allowed))if(!ok)node(id).disabled=true;};
const trainingPlayer=stepPlayer;stepPlayer=function(dt){if(trainingActive){const stage=trainingState.stage;if(stage!==2&&stage!==8){firing.primary=false;keys.delete(' ')}if(stage!==3&&stage!==8)firing.secondary=false;if(stage!==4&&stage!==8)firing.support=false;if(stage!==9){ejectHeld=false;ejectPress=0;keys.delete('x')}}trainingPlayer(dt)};
