'use strict';
// v24: plain radial blockout. No urban artwork or destructible scenery.
const SOLO_ARENA={size:3000,width:3000,height:3000,mechWidth:225.25,radius:155,spawn:{x:2500,y:1500},spawns:[{x:2500,y:1500},{x:1000,y:634},{x:500,y:1500},{x:2000,y:2366}]};
const ARENA={...SOLO_ARENA};let arenaMode='solo';function setArenaMode(mode){arenaMode=mode;Object.assign(ARENA,mode==='duel'?{size:2640,width:2640,height:1800,mechWidth:225.25,radius:155,spawn:{x:1320,y:1370},spawns:[{x:1320,y:1370},{x:1320,y:430}]}:SOLO_ARENA);layoutCanvas=null;resetUrban()}
const URBAN_ASSETS=[],urbanObjects=[],urbanVisible={bounds:null};let urbanClock=0;
function roadPoint(x,y){if(arenaMode==='duel'){const dx=x-1320,dy=y-900,ring=Math.hypot(Math.max(0,Math.abs(dx)-420),dy);return Math.hypot(dx,dy)<=420||Math.abs(ring-735)<=170||Math.abs(dx)<=225||Math.abs(dy)<=225}const dx=x-1500,dy=y-1500,r=Math.hypot(dx,dy);if(r<=600||Math.abs(r-1250)<=225)return true;for(let i=0;i<6;i++){const a=i*Math.PI/3,along=dx*Math.cos(a)+dy*Math.sin(a),across=-dx*Math.sin(a)+dy*Math.cos(a);if(along>=0&&Math.abs(across)<=(i%3===0?337.5:225))return true}return false}
function solidPoint(x,y){return x<0||y<0||x>ARENA.width||y>ARENA.height||!roadPoint(x,y)||(arenaMode==='duel'?Math.hypot(x-1320,y-900)<=90:(Math.abs(x-1500)<=70&&Math.abs(y-1500)<=110))}
function urbanBlocked(x,y,r=ARENA.radius){if(solidPoint(x,y)||x<r||y<r||x>ARENA.width-r||y>ARENA.height-r)return true;for(let i=0;i<32;i++){const a=i*Math.PI/16;if(solidPoint(x+Math.cos(a)*(r+3),y+Math.sin(a)*(r+3)))return true}return false}
function urbanMove(actor,x,y,r=ARENA.radius){const dx=x-actor.x,dy=y-actor.y,n=Math.max(1,Math.ceil(Math.hypot(dx,dy)/8));for(let i=0;i<n;i++){const sx=dx/n,sy=dy/n,nx=actor.x+sx,ny=actor.y+sy;if(!urbanBlocked(nx,ny,r)){actor.x=nx;actor.y=ny;continue}let rx=0,ry=0;for(let j=0;j<32;j++){const a=j*Math.PI/16,ux=Math.cos(a),uy=Math.sin(a);if(solidPoint(nx+ux*(r+4),ny+uy*(r+4))){rx-=ux;ry-=uy}}const len=Math.hypot(rx,ry);if(len>.01){rx/=len;ry/=len;const inward=Math.min(0,sx*rx+sy*ry),tx=sx-rx*inward,ty=sy-ry*inward;if(Math.hypot(tx,ty)>.01&&!urbanBlocked(actor.x+tx,actor.y+ty,r)){actor.x+=tx;actor.y+=ty;continue}}if(!urbanBlocked(nx,actor.y,r))actor.x=nx;if(!urbanBlocked(actor.x,ny,r))actor.y=ny}}

function segmentSection(x,y,ex,ey,s){let lo=0,hi=1;for(const [start,end,c,size] of [[x,ex,s.x,s.w],[y,ey,s.y,s.h]]){const d=end-start;if(Math.abs(d)<1e-9){if(start<c-size/2||start>c+size/2)return null;continue}let a=(c-size/2-start)/d,b=(c+size/2-start)/d;if(a>b)[a,b]=[b,a];lo=Math.max(lo,a);hi=Math.min(hi,b);if(lo>hi)return null}return lo}
const blockTarget={type:'building',shield:false};
function urbanSweep(x,y,ex,ey){const n=Math.max(1,Math.ceil(Math.hypot(ex-x,ey-y)/4));for(let i=0;i<=n;i++){const t=i/n,xx=x+(ex-x)*t,yy=y+(ey-y)*t;if(solidPoint(xx,yy))return{x:xx,y:yy,t,target:blockTarget,environment:blockTarget}}return null}
function urbanImpact(){}function urbanNuke(){}function prepareUrbanSprites(){}function resetUrban(){urbanClock=0}function stepUrban(dt){urbanClock+=dt}
let layoutCanvas=null;
function makeLayout(){if(arenaMode==='duel')return makeDuelLayout();if(layoutCanvas)return layoutCanvas;const cv=document.createElement('canvas');cv.width=cv.height=1000;const c=cv.getContext('2d');c.scale(1/3,1/3);c.fillStyle='#685e77';c.fillRect(0,0,3000,3000);c.strokeStyle='#344f5d';c.fillStyle='#344f5d';c.beginPath();c.arc(1500,1500,1250,0,Math.PI*2);c.lineWidth=450;c.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3;c.beginPath();c.moveTo(1500,1500);c.lineTo(1500+2100*Math.cos(a),1500+2100*Math.sin(a));c.lineWidth=i%3===0?675:450;c.stroke()}c.beginPath();c.arc(1500,1500,600,0,Math.PI*2);c.fill();c.strokeStyle='#82969c';c.lineWidth=3;c.stroke();c.fillStyle='#a08759';c.fillRect(1430,1390,140,220);c.fillStyle='#e1d9e7';c.font='38px system-ui';c.textAlign='center';for(let i=0;i<6;i++){const a=(i+.5)*Math.PI/3;c.fillText('ABCDEF'[i],1500+840*Math.cos(a),1500+840*Math.sin(a)+12)}layoutCanvas=cv;return cv}
function drawUrbanGround(c,w,h){urbanVisible.bounds={x0:p.x-w/ZOOM/2-250,y0:p.y-h/ZOOM/2-250,x1:p.x+w/ZOOM/2+250,y1:p.y+h/ZOOM/2+250};c.drawImage(makeLayout(),0,0,ARENA.width,ARENA.height)}
function drawUrbanDetails(){}function drawUrbanRubble(){}function drawUrbanStructures(){}function drawUrbanEffects(){}
function drawPanelMinimap(viewW,viewH){const cv=$('minimap');if(!cv)return;const[c,w,h]=resize(cv),scale=Math.min(w/ARENA.width,h/ARENA.height),mw=ARENA.width*scale,mh=ARENA.height*scale,ox=(w-mw)/2,oy=(h-mh)/2;c.clearRect(0,0,w,h);c.drawImage(makeLayout(),ox,oy,mw,mh);for(const actor of [p,...enemies]){if(!aliveActor(actor))continue;c.fillStyle=actor===p?'#6fe6ff':actor.marker;c.beginPath();c.arc(ox+actor.x*scale,oy+actor.y*scale,2.8,0,7);c.fill()}c.strokeStyle='#d7e5ec';c.lineWidth=.8;if(arenaMode==='duel')c.strokeRect(ox,oy,mw,mh);else c.strokeRect((p.x-viewW/ZOOM/2)*scale,(p.y-viewH/ZOOM/2)*scale,viewW/ZOOM*scale,viewH/ZOOM*scale)}
// Fixed 50-unit navigation graph, using the same full-mech clearance as movement.
const NAV_SIZE=60,navFree=new Uint8Array(3600);
for(let y=0;y<NAV_SIZE;y++)for(let x=0;x<NAV_SIZE;x++)navFree[y*NAV_SIZE+x]=!urbanBlocked(x*50+25,y*50+25);
function navPath(actor,goal){function nearest(a){let best=-1,d=Infinity;for(let i=0;i<navFree.length;i++)if(navFree[i]){const dd=(i%60*50+25-a.x)**2+(Math.floor(i/60)*50+25-a.y)**2;if(dd<d){d=dd;best=i}}return best}const start=nearest(actor),end=nearest(goal),parent=new Int32Array(3600).fill(-1),queue=[start];parent[start]=start;for(let k=0;k<queue.length&&parent[end]<0;k++){const i=queue[k],x=i%60,y=Math.floor(i/60);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,j=yy*60+xx;if(xx<0||xx>=60||yy<0||yy>=60||!navFree[j]||parent[j]>=0)continue;parent[j]=i;queue.push(j)}}if(parent[end]<0)return[];const path=[];for(let i=end;i!==start;i=parent[i])path.push({x:i%60*50+25,y:Math.floor(i/60)*50+25});return path.reverse()}
resetUrban();

// One unique city image, registered to the existing 2640 x 1800 world.
function makeDuelLayout(){if(layoutCanvas)return layoutCanvas;const cv=document.createElement('canvas');cv.width=2640;cv.height=1800;const c=cv.getContext('2d');c.drawImage(images['duel-city'],0,0,2640,1800);drawCityCollisionEdges(c);layoutCanvas=cv;return cv}
function cityRoofPaths(){const paths=[];for(const sx of [-1,1])for(const sy of [-1,1]){const points=[];const cx=1320+sx*420,cy=900,r=565;points.push([1320+sx*225,900+sy*565],[cx,900+sy*565]);const angle=Math.asin(225/r);for(let i=0;i<=48;i++){const a=Math.PI/2+(angle-Math.PI/2)*i/48;points.push([cx+sx*Math.cos(a)*r,cy+sy*Math.sin(a)*r])}points.push([1320+sx*Math.sqrt(420*420-225*225),900+sy*225]);for(let i=0;i<=20;i++){const a=Math.asin(225/420)+(Math.acos(225/420)-Math.asin(225/420))*i/20;points.push([1320+sx*420*Math.cos(a),900+sy*420*Math.sin(a)])}paths.push(points)}return paths}
function drawCityCollisionEdges(c){c.save();c.strokeStyle='#73716a';c.lineWidth=7;c.lineJoin='round';for(const points of cityRoofPaths()){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.stroke()}c.restore()}

// Night lighting uses the collision footprint, so beams cannot cross roofs or the monument.
let streetLamps=[],lampMode=null;const headlightCache=new WeakMap();
function lightRay(x,y,a,range){let d=0;for(let next=6;next<=range;next+=6){if(solidPoint(x+Math.sin(a)*next,y-Math.cos(a)*next))break;d=next}return [x+Math.sin(a)*d,y-Math.cos(a)*d]}
function lightPolygon(x,y,a,spread,range,steps=28){const points=[[x,y]];for(let i=0;i<=steps;i++)points.push(lightRay(x,y,a-spread/2+spread*i/steps,range));return points}
function clipLight(c,points){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.clip()}
function prepareStreetLamps(){if(lampMode===arenaMode)return;lampMode=arenaMode;streetLamps=[];const step=arenaMode==='duel'?240:300;for(let y=120;y<ARENA.height-100;y+=step)for(let x=120;x<ARENA.width-100;x+=step){if(solidPoint(x,y))continue;let edge=false;for(let i=0;i<8;i++)if(solidPoint(x+Math.cos(i*Math.PI/4)*85,y+Math.sin(i*Math.PI/4)*85))edge=true;if(!edge)continue;streetLamps.push({x,y,points:lightPolygon(x,y,0,Math.PI*2,210,40)})}}
function lightVisible(x,y,r){const b=urbanVisible.bounds;return !b||x+r>b.x0&&x-r<b.x1&&y+r>b.y0&&y-r<b.y1}
function drawUrbanNight(c){c.save();c.fillStyle='rgba(3,10,25,.53)';c.fillRect(0,0,ARENA.width,ARENA.height);c.restore()}
function drawUrbanLights(c){prepareStreetLamps();for(const l of streetLamps){if(!lightVisible(l.x,l.y,210))continue;c.save();clipLight(c,l.points);c.globalCompositeOperation='screen';glow(c,l.x,l.y,210,'#ffb456',.42);glow(c,l.x,l.y,42,'#ffc779',.22);c.restore();c.save();c.fillStyle='#090e16';c.beginPath();c.roundRect(l.x-7,l.y-11,14,22,3);c.fill();c.fillStyle='#ffe3a3';c.fillRect(l.x-3,l.y-6,6,12);c.restore()}}
function mechHeadlightState(actor){if(actor.dead||actor.alive===false||!actorLoadout(actor)?.turret)return null;if(actor.ejecting){const age=actor.ejecting.age;if(age>=3.03)return null;return{colour:'#ff3024',strength:Math.sin(age*(12+age*18))>0?.65:.035}}let boot=actor===p?deployment:actor.human&&typeof duelPlayers!=='undefined'?duelPlayers[actor.duelIndex]?.deployment:null;if(boot)return null;return{colour:'#fff0c9',strength:.18}}
function drawMechHeadlights(c){for(const actor of new Set([p,...enemies])){const state=mechHeadlightState(actor);if(!state||!lightVisible(actor.x,actor.y,460))continue;const a=actor.angle||0,key=[Math.round(actor.x/4),Math.round(actor.y/4),Math.round(a/.02),arenaMode].join(':');let cached=headlightCache.get(actor);if(!cached||cached.key!==key){const lamps=[];for(const side of [-1,1]){const lx=side*88*.85,ly=18*.85,x=actor.x+lx*Math.cos(a)-ly*Math.sin(a),y=actor.y+lx*Math.sin(a)+ly*Math.cos(a);if(solidPoint(x,y))continue;lamps.push({x,y,points:lightPolygon(x,y,a,.88,420,40)})}cached={key,lamps};headlightCache.set(actor,cached)}for(const l of cached.lamps){c.save();clipLight(c,l.points);c.globalCompositeOperation='screen';c.globalAlpha=state.strength*2.7;c.translate(l.x,l.y);c.rotate(a);c.drawImage(headlightTexture(state.colour),-200,-420,400,420);c.restore();c.save();c.globalCompositeOperation='screen';glow(c,l.x,l.y,22,state.colour,state.strength*1.5);c.restore()}}}

const headlightTextures=new Map();
function headlightTexture(colour){if(headlightTextures.has(colour))return headlightTextures.get(colour);const cv=document.createElement('canvas');cv.width=192;cv.height=256;const c=cv.getContext('2d'),im=c.createImageData(192,256),rgb=colour==='#ff3024'?[255,48,36]:[255,240,201];for(let y=0;y<256;y++)for(let x=0;x<192;x++){const d=(256-y)/256,across=Math.abs((x-95.5)/96),width=Math.tan(.44)*420*d/200,angular=Math.max(0,1-across/Math.max(.002,width)),fade=(1-d)**1.35,near=Math.min(1,d*20),i=(y*192+x)*4;im.data[i]=rgb[0];im.data[i+1]=rgb[1];im.data[i+2]=rgb[2];im.data[i+3]=Math.round(255*angular**1.6*fade*near)}c.putImageData(im,0,0);headlightTextures.set(colour,cv);return cv}
