'use strict';
const rangeHUD=document.getElementById('rangeHUD');let rangeState=null,rangeEnemySnapshot=null;
function openWeaponRange(){if(duelActive)leaveDuel();if(!ready||!build.chassis||!build.turret)return;rangeEnemySnapshot={loadout:enemy.loadout,name:enemy.name};soloDeploy();weaponRange=true;rangeHUD.hidden=false;deployment=null;stadiumSequence=null;resetBattleResult();matchProgress=null;fieldState=null;clearCombatFx();p.x=ARENA.width/2;p.y=ARENA.height/2;p.angle=p.heading=0;enemies.splice(0,enemies.length,enemy);enemy.alive=true;enemy.name='RANGE TARGET';enemy.loadout={colour:'red',chassis:'chassis',turret:'turret',left:'',right:'',rear:''};resetRangeTarget();}
function resetRangeTarget(){if(!weaponRange)return;clearCombatFx();resetBattleResult();resetHeat();for(const s in cooldown)cooldown[s]=0;for(const s in firing)firing[s]=false;p.x=ARENA.width/2;p.y=ARENA.height/2;p.angle=p.heading=0;p.shield=0;p.energy=100;p.burnTime=0;p.slow=1;p.slowTime=0;enemy.x=p.x;enemy.y=p.y-Number(document.getElementById('rangeDistance').value||500);enemy.angle=enemy.heading=Math.PI;enemy.alive=true;enemy.dead=false;enemy.ejecting=null;enemy.shield=false;enemy.burnTime=0;enemy.slow=1;enemy.generation++;resetParts(enemy);rangeState={running:false,time:0,shots:0,shotsFired:0,cooling:0,reloads:0,slotShots:{},done:false,startTime:null};document.getElementById('rangeResult').textContent='700 HP · shields off · ready';document.getElementById('rangeRun').disabled=false;}
function startRangeTest(){resetRangeTarget();rangeState.running=true;document.getElementById('rangeRun').disabled=true;}
function rangeSlots(){const choice=document.getElementById('rangeSlot').value;return [['primary',build.left,-85],['secondary',build.right,85],['support',build.rear,0]].filter(([slot,id])=>id&&(choice==='all'||choice===slot))}
function stepWeaponRange(dt){if(!rangeState?.running)return;const slots=rangeSlots();if(!slots.length){rangeState.running=false;document.getElementById('rangeRun').disabled=false;document.getElementById('rangeResult').textContent='Fit a weapon in this slot first';return;}enemy.burnTime=Math.max(0,enemy.burnTime-dt);if(enemy.burnTime>0&&enemy.alive)enemyHit('flame',{damage:enemy.burn*dt,penetration:1},1,true,'hull',enemy);if(slots.some(([slot])=>weaponHeat[slot]?.locked))rangeState.cooling+=dt;for(const [slot,id,offset]of slots){firing[slot]=true;if(cooldown[slot]<=.000001&&canFireHeat(slot,id)){const local=weaponMount(slot,id),port=GUNS[id].ports[0],dx=(local.x+((local.flip?1-port[0]:port[0])-.5)*local.w)*MECH_SCALE;/* Account for shoulder muzzle offset when lining up the stationary target. */const distance=Math.hypot(enemy.x-p.x,enemy.y-p.y);p.angle=Math.asin(Math.max(-.6,Math.min(.6,-dx/distance)));if(id==='mines'){p.angle=0;enemy.y=p.y+Number(document.getElementById('rangeDistance').value||500);}else enemy.y=p.y-Number(document.getElementById('rangeDistance').value||500);fireWeapon(id,offset,['swarm','hunter','smart'].includes(id)?enemy:null);addWeaponHeat(slot,id);cooldown[slot]=weaponStats(id,modifications[slot]).rate;rangeState.shots++;if(rangeState.slotShots[slot]&&!weaponStats(id,modifications[slot]).continuous)rangeState.reloads++;rangeState.slotShots[slot]=(rangeState.slotShots[slot]||0)+1;if(rangeState.startTime===null)rangeState.startTime=rangeState.time;}}}
function finishRangeTick(dt){if(!rangeState?.running)return;rangeState.time+=dt;const elapsed=rangeState.time-(rangeState.startTime||0);document.getElementById('rangeResult').textContent=elapsed.toFixed(2)+'s · '+Math.ceil(enemy.hp)+' HP · '+rangeState.shots+' volleys';if(!enemy.alive||enemy.hp<=0||elapsed>=180){rangeState.running=false;rangeState.done=true;for(const s in firing)firing[s]=false;const result={date:new Date().toISOString(),distance:Number(document.getElementById('rangeDistance').value),slot:document.getElementById('rangeSlot').value,build:{...build},modifications:{...modifications},ttk:enemy.hp<=0?Number(elapsed.toFixed(3)):null,damage:Math.round(700-enemy.hp),volleys:rangeState.shots,projectiles:rangeState.shotsFired,reloads:rangeState.reloads,cooling:Number(rangeState.cooling.toFixed(2))};document.getElementById('rangeResult').textContent=(result.ttk===null?'NO KILL IN 180s':result.ttk.toFixed(2)+'s TTK')+' · '+result.damage+' damage · '+result.volleys+' volleys · '+result.reloads+' reloads · '+result.cooling+'s cooling';try{const history=JSON.parse(localStorage.getItem('iron-pit-range-results')||'[]');history.push(result);localStorage.setItem('iron-pit-range-results',JSON.stringify(history.slice(-100)))}catch(e){}document.getElementById('rangeRun').disabled=false;}}
document.getElementById('rangeOpen').onclick=openWeaponRange;document.getElementById('rangeRun').onclick=startRangeTest;document.getElementById('rangeReset').onclick=resetRangeTarget;document.getElementById('rangeDistance').onchange=resetRangeTarget;document.getElementById('rangeSlot').onchange=resetRangeTarget;
const rangeWorkshopReturn=$('return').onclick;$('return').onclick=()=>{if(weaponRange){for(const s in firing)firing[s]=false;rangeState.running=false;rangeHUD.hidden=true;weaponRange=false;enemy.loadout=rangeEnemySnapshot?.loadout||BOT_BUILDS[0];enemy.name=rangeEnemySnapshot?.name||'BREAKER';}rangeWorkshopReturn()};
