'use strict';
// Normalised firing points measured against each cropped approved sprite.
const GUNS={
 'machine-gun':{ports:[[.55,.01]],rate:0.1,speed:1500,kind:'bullet',color:'#ffd08a'},
 rotary:{ports:[[.42,.01],[.48,.01],[.55,.01],[.61,.01]],cycle:true,rate:0.12,speed:1350,kind:'bullet',color:'#ffbd69'},
 siege:{ports:[[.30,.015],[.51,.015]],rate:3,speed:820,kind:'shell',color:'#ffc875'},
 'tri-salvo':{ports:[[.24,.015],[.43,.015],[.62,.015]],rate:2,speed:470,kind:'rocket',color:'#ffb36a'},
 railgun:{ports:[[.36,.015]],rate:2.5,speed:2600,kind:'rail',color:'#d9f5ff'},
 flak:{ports:[[.42,.02]],rate:1,speed:920,kind:'flak',color:'#ffd17f'},
 plasma:{ports:[[.45,.015]],rate:0.9,speed:540,kind:'plasma',color:'#52e8ff'},
 pulse:{ports:[[.35,.04],[.64,.04]],rate:0.2,speed:2200,kind:'pulse',color:'#ff4545'},
 beam:{ports:[[.4,.015]],rate:.07,speed:0,kind:'beam',color:'#ffbe51',range:780},
 flame:{ports:[[.24,.015]],rate:.055,speed:340,kind:'flame',color:'#ff922f',range:260},
 arc:{ports:[[.37,.015],[.63,.015]],rate:.13,speed:0,kind:'arc',color:'#b985ff',range:360},
 emp:{ports:[[.38,.015]],rate:8,speed:480,kind:'emp',color:'#5c9dff'},
 swarm:{ports:[[.20,.02],[.28,.02],[.36,.02],[.64,.02],[.72,.02],[.80,.02]],rate:6,speed:440,kind:'rocket',color:'#ffc581'},
 hunter:{ports:[[.23,.02],[.36,.02],[.64,.02],[.77,.02]],rate:9,speed:380,kind:'rocket',color:'#ffc581'},
 barrage:{ports:[[.20,.02],[.35,.02],[.50,.02],[.65,.02],[.80,.02]],rate:7,speed:520,kind:'rocket',color:'#ffc581'},
 mortar:{ports:[[.33,.10],[.73,.10]],rate:7,speed:390,kind:'mortar',color:'#ffd279'},
 mines:{ports:[[.5,.98]],rate:10,speed:0,kind:'mine',color:'#d9b54f'},
 smoke:{ports:[[.25,.88],[.75,.88]],rate:12,speed:150,kind:'smoke',color:'#b3bbb7'}
};
const rounds=[],particles=[],flashes=[],lines=[],marks=[],mines=[];const barrelCycle={};const targets=[];
const MAX_PARTICLES=700,MECH_SCALE=.85;
let activeShooter=null;
function withShooter(actor,fn){const previous=activeShooter;activeShooter=actor;try{return fn()}finally{activeShooter=previous}}
function cancelPlayerLaunches(){for(let i=launchQueue.length-1;i>=0;i--)if(launchQueue[i].owner===p)launchQueue.splice(i,1)}
function shielded(actor){return actor===p?p.shield>0:!!actor.shield}
function emit(o){if(particles.length<(o.kind==='smoke'?MAX_PARTICLES-80:MAX_PARTICLES))particles.push(o)}
function worldPoint(x,y,a=(activeShooter||p).angle){const actor=activeShooter||p;return{x:actor.x+(x*Math.cos(a)-y*Math.sin(a))*MECH_SCALE,y:actor.y+(x*Math.sin(a)+y*Math.cos(a))*MECH_SCALE}}
const PRIMARY_IDS=['machine-gun','rotary','pulse','beam','flame','arc'];
const SECONDARY_IDS=['siege','railgun','plasma','tri-salvo','flak','emp'];
function weaponMount(slot,id){if(slot==='support')return{x:0,y:72,w:112,h:100,flip:false};const right=slot==='secondary';return{x:right?99:-99,y:-34,w:67,h:154,flip:side.findIndex(v=>v[0]===id)<6?right:!right}}
function mountPorts(id,offset){const g=GUNS[id],m=weaponMount(offset<0?'primary':offset>0?'secondary':'support',id);return g.ports.map(([u,v])=>worldPoint(m.x+((m.flip?1-u:u)-.5)*m.w,m.y+(v-.5)*m.h))}
function puff(x,y,color,n,speed,size,life){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=Math.random()*speed;emit({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,color,size:size*(.4+Math.random()),life,max:life,kind:'spark'})}}
function smokePuff(x,y,size=9,life=.8){emit({x,y,vx:(Math.random()-.5)*12,vy:(Math.random()-.5)*12,color:'#88918b',size,life,max:life,kind:'smoke'})}
function addMark(x,y,r){marks.push({x,y,r,life:14});if(marks.length>90)marks.shift()}
function impact(id,x,y,shield=false,stats=weaponStats(id),hit=null){const g=GUNS[id];if(!shield){componentImpact(id,x,y,stats,hit);urbanImpact(x,y,stats,hit);}if(typeof Sound!=='undefined')Sound.play(shield?'shield':'hit-'+id,x,y,shield?.72:['rocket','shell','mortar','mine'].includes(GUNS[id].kind)?1.08:.72);if(shield){if(hit?.target&&[p,...enemies].includes(hit.target)){absorbShield(hit.target,stats.damage);if(id==='emp'){if(hit.target===p)p.shield=0;else hit.target.shield=false}}if(id==='emp')for(const t of targets)if(t.shield&&Math.hypot(x-t.x,y-t.y)<t.r+25){t.shield=false;t.shieldTimer=2.5}flashes.push({x,y,r:5,max:55,life:.4,total:.4,color:'#65d9ff',ring:true,tex:7});puff(x,y,'#9deaff',14,100,2,.32);return}
 const kind=g.kind;
 if(['rocket','shell','mortar','mine'].includes(kind)){const r=id==='hunter'?62:kind==='shell'?42:kind==='mine'?48:30;flashes.push({x,y,r,max:r,life:.28,total:.28,color:'#ffb44d',tex:2});puff(x,y,'#ffb64e',26,190,3,.6);puff(x,y,'#827868',14,115,4,.9);for(let j=0;j<9;j++)smokePuff(x+(Math.random()-.5)*r,y+(Math.random()-.5)*r,12,1.3);addMark(x,y,r*.5)}
 else if(kind==='flak'){puff(x,y,'#ffe5ae',35,240,1.5,.5);puff(x,y,'#8b9386',12,130,3,.5);addMark(x,y,12)}
 else if(kind==='plasma'){flashes.push({x,y,r:24,max:32,life:.45,total:.45,color:'#58edff',tex:3});puff(x,y,'#59e4ff',22,100,3,.6);addMark(x,y,14)}
 else if(kind==='emp'){flashes.push({x,y,r:10,max:110,life:.65,total:.65,color:'#5fafff',ring:true});for(let i=0;i<5;i++)lines.push({x,y,ex:x+(Math.random()-.5)*80,ey:y+(Math.random()-.5)*80,life:.25,total:.25,color:'#71b8ff',arc:true});}
 else if(kind==='arc'){for(let i=0;i<5;i++)lines.push({x,y,ex:x+(Math.random()-.5)*75,ey:y+(Math.random()-.5)*75,life:.2,total:.2,color:g.color,arc:true});puff(x,y,g.color,5,60,2,.2)}
 else if(kind==='flame'){emit({x,y,vx:0,vy:0,size:12,life:.65,max:.65,color:'#ff9d35',kind:'fire'});smokePuff(x,y,12,1);addMark(x,y,8)}
 else{puff(x,y,kind==='rail'?'#ecfaff':g.color,kind==='rail'?28:8,kind==='rail'?210:100,1.5,.3);flashes.push({x,y,r:kind==='rail'?15:6,max:12,life:.12,total:.12,color:g.color});addMark(x,y,kind==='rail'?7:3)}
}
function sweepHit(x,y,ex,ey,owner=activeShooter||p){let best=urbanSweep(x,y,ex,ey),tmin=best?best.t:1;const dx=ex-x,dy=ey-y;if(dx*dx+dy*dy<.0001)return best;for(const actor of [p,...enemies]){if(actor===owner||!aliveActor(actor))continue;if(shielded(actor)){const cx=x-actor.x,cy=y-actor.y,aa=dx*dx+dy*dy,b=2*(cx*dx+cy*dy),cc=cx*cx+cy*cy-142*142,d=b*b-4*aa*cc;if(d>=0){const q=cc<=0?0:(-b-Math.sqrt(d))/(2*aa);if(q>=0&&q<=tmin){tmin=q;best={x:x+dx*q,y:y+dy*q,t:q,target:actor,part:'hull'}}}continue}const bounds={x:actor.x,y:actor.y,w:380,h:380};const entry=segmentSection(x,y,ex,ey,bounds);if(entry===null||entry>tmin)continue;const reverse=segmentSection(ex,ey,x,y,bounds),exit=1-reverse;const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/3));for(let i=Math.max(0,Math.ceil(entry*steps));i<=Math.min(steps,Math.floor(Math.min(tmin,exit)*steps));i++){const q=i/steps,part=enemyPartAt(x+dx*q,y+dy*q,actor);if(part){tmin=q;best={x:x+dx*q,y:y+dy*q,t:q,target:actor,part};break}}}if(best)best.owner=owner;return best}
const launchQueue=[],weaponSoundStates={},flameStreams={};let shotSerial=0;
function cancelLaunches(){launchQueue.length=0;for(const key in weaponSoundStates)stopWeaponSound(key);for(const key in flameStreams)delete flameStreams[key];for(const r of rounds)if(r.soundKey)Sound.stopLoop(r.soundKey);for(const m of mines)if(m.soundKey)Sound.stopLoop(m.soundKey)}
function stopWeaponSound(slot){if(p.human&&['primary','secondary','support'].includes(slot))slot=p.id+'-'+slot;const old=weaponSoundStates[slot];if(!old)return;Sound.stopLoop('weapon-'+slot);if(old.id==='beam')Sound.play('beam-stop',p.x,p.y,.7);delete weaponSoundStates[slot]}
function sustainWeaponSound(id,slot,rate){const actor=activeShooter||p;let old=weaponSoundStates[slot];if(old?.id!==id){stopWeaponSound(slot);if(id==='beam')Sound.play('beam-start',actor.x,actor.y,.7);if(id==='flame')Sound.play('flame-start',actor.x,actor.y,.8)}weaponSoundStates[slot]={id,life:rate+.055};Sound.loop('fire-'+id,'weapon-'+slot,actor.x,actor.y,id==='flame'?.85:.72)}
function queueLaunch(delay,fn){const owner=activeShooter||p;if(delay<=0)fn();else launchQueue.push({delay,generation:owner.generation,owner,fn})}
function fireWeapon(id,offset,lockedTarget=null){const actor=activeShooter||p;if(!id||!aliveActor(actor))return;const g=GUNS[id],stats=actor.human?weaponStats(id,actor.modifications[offset===0?'support':offset<0?'primary':'secondary']):actor===p?shotStats(id,offset):weaponStats(id),slot=(actor.human?actor.id+'-':actor===p?'':actor.id+'-')+(offset===0?'support':offset<0?'primary':'secondary');let indices=g.ports.map((_,i)=>i);if(g.cycle){const i=barrelCycle[id]||0;indices=[i%g.ports.length];barrelCycle[id]=i+1}
 if(['beam','flame','arc'].includes(g.kind))sustainWeaponSound(id,slot,stats.rate);
 if(id==='plasma')Sound.play('plasma-charge',actor.x,actor.y,.8);
 if(g.kind==='mine'){for(let i=0;i<5;i++)queueLaunch(i*.09,()=>launchMine(id,offset,i,stats));return}
 for(const index of indices){const gap=id==='tri-salvo'?.2:id==='swarm'?.1:id==='barrage'?.5:0;queueLaunch((id==='plasma'?.3:0)+index*gap,()=>launchPort(id,offset,index,stats,lockedTarget,slot));}
}
function launchMine(id,offset,i,stats){if(mines.length>=30)return;const actor=activeShooter||p;if(actor.parts.rear<=0||actor.parts.turret<=0)return;const point=mountPorts(id,offset)[0],a=actor.angle+Math.PI+(i-2)*.32,duration=.68+i*.035,dist=135+(2-Math.abs(i-2))*25,key='mine-flight-'+(++shotSerial);mines.push({owner:actor,x:point.x,y:point.y,startX:point.x,startY:point.y,dx:Math.sin(a)*dist,dy:-Math.cos(a)*dist,life:20,armed:duration,age:0,flight:duration,angle:0,spin:(i%2?-1:1)*Math.PI*(5+i*.5),stats,soundKey:key});Sound.play('fire-mines',point.x,point.y,.65,null,true)}
function launchPort(id,offset,index,baseStats,target,slot){const actor=activeShooter||p;if(!aliveActor(actor)||actor.parts.turret<=0||actor.parts[offset<0?'left':offset>0?'right':'rear']<=0)return;const g=GUNS[id],ports=mountPorts(id,offset),point=ports[index],{x,y}=point;let a=actor.angle,stats={...baseStats};if(stats.continuous){stats.damage*=stats.rate/(g.kind==='arc'?g.ports.length:1)}
 if(['beam','arc'].includes(g.kind)){let ex=x+Math.sin(a)*g.range,ey=y-Math.cos(a)*g.range;const hit=sweepHit(x,y,ex,ey);if(hit){ex=hit.x;ey=hit.y;impact(id,ex,ey,shielded(hit.target),stats,hit)}lines.push({x,y,ex,ey,color:g.color,life:baseStats.rate*1.5,total:baseStats.rate*1.5,arc:g.kind==='arc'});return}
 if(g.kind==='flame'){const range=g.range;let hit=null;for(const delta of [0,-.10,.10]){const aa=a+delta;hit=sweepHit(x,y,x+Math.sin(aa)*range,y-Math.cos(aa)*range);if(hit)break}flameStreams[slot]={smoke:flameStreams[slot]?.smoke??0,x,y,a,range:hit?Math.hypot(hit.x-x,hit.y-y):range,life:baseStats.rate+.08};if(hit)impact(id,hit.x,hit.y,shielded(hit.target),stats,hit);return}
 Sound.play('fire-'+id,x,y,.85,id==='barrage'?[1,.96,1.025,.98,1.04][index]:null,true);
 if(id==='swarm')a+=[-.9,.72,-.48,.98,-.22,.3][index];else if(id==='barrage')a+=(index-(ports.length-1)/2)*.018;
 if(g.kind==='rocket')for(let j=0;j<7;j++){const back=10+Math.random()*24;emit({x:x-Math.sin(a)*back,y:y+Math.cos(a)*back,vx:-Math.sin(a)*(25+Math.random()*35)+(Math.random()-.5)*25,vy:Math.cos(a)*(25+Math.random()*35)+(Math.random()-.5)*25,color:'#9da6a3',size:12+Math.random()*10,life:1.1,max:1.1,kind:'smoke'})}
 if(g.kind==='smoke')a+=Math.PI+(index?-.3:.3);
 flashes.push({x,y,r:g.kind==='bullet'?5:9,max:9,life:g.kind==='shell'?.1:.065,total:g.kind==='shell'?.1:.065,color:g.color,muzzle:true,lightRadius:g.kind==='shell'?170:g.kind==='bullet'?80:115});
 if(['bullet','shell','flak'].includes(g.kind))emit({x,y,vx:Math.cos(a)*90,vy:Math.sin(a)*90,size:2,life:.7,max:.7,color:'#b89956',kind:'case'});
 const count=g.kind==='flak'?5:1;
 for(let pellet=0;pellet<count;pellet++){if(rounds.length>=230)break;const angle=a+(count>1?(pellet-2)*.025:0),centre=ports.reduce((c,v)=>({x:c.x+v.x/ports.length,y:c.y+v.y/ports.length}),{x:0,y:0});rounds.push({owner:actor,x,y,px:x,py:y,a:angle,id,stats,target,targetLife:target?.generation,speed:g.speed*(id==='swarm'?[.91,1.08,.98,1.13,.94,1.04][index]:1),life:g.kind==='mortar'?1.3:g.kind==='smoke'?.45:id==='swarm'?4:2,age:0,trail:0,travel:0,...(id==='swarm'?{curveSide:index%2?1:-1,curveBias:[1.12,.83,.67,1.24,.4,.52][index],curveTime:[1.2,1.05,.85,1.3,.7,.95][index],soundKey:'swarm-flight-'+(++shotSerial),soundRate:[.94,1.03,.98,1.06,.96,1.01][index]}:{})})}
}
function stepWeapons(dt){for(let i=launchQueue.length-1;i>=0;i--){const q=launchQueue[i];q.delay-=dt;if(q.delay<=.000001){launchQueue.splice(i,1);if(q.generation===q.owner.generation&&aliveActor(q.owner))withShooter(q.owner,q.fn)}}for(const slot in weaponSoundStates){const state=weaponSoundStates[slot];state.life-=dt;if(state.life<=0||(!aliveActor([p,...enemies].find(a=>slot.startsWith(a.id+'-'))||p))||(weaponHeat[slot]?.locked&&last/1000-weaponHeat[slot].lastShot>.001))stopWeaponSound(slot)}for(const slot in flameStreams){flameStreams[slot].life-=dt;if(flameStreams[slot].life<=0)delete flameStreams[slot];else{const f=flameStreams[slot];f.smoke=(f.smoke||0)-dt;if(f.smoke<=0){const ex=f.x+Math.sin(f.a)*f.range,ey=f.y-Math.cos(f.a)*f.range;for(let i=0;i<3;i++)smokePuff(ex+(Math.random()-.5)*35,ey+(Math.random()-.5)*35,18+Math.random()*8,2.5);f.smoke=.09}}}
 stepCombatFx(dt);
for(const t of targets)if(t.shieldTimer>0){t.shieldTimer-=dt;if(t.shieldTimer<=0)t.shield=true}
 for(let i=rounds.length-1;i>=0;i--){const e=rounds[i],g=GUNS[e.id];e.life-=dt;e.age+=dt;e.px=e.x;e.py=e.y;if(e.id==='swarm'){let desired=e.a;const guided=e.target&&aliveActor(e.target)&&e.target.generation===e.targetLife;if(guided){const distance=Math.hypot(e.target.x-e.x,e.target.y-e.y),fan=e.curveSide*e.curveBias*Math.max(0,1-e.age/e.curveTime)*Math.min(1,distance/230);desired=Math.atan2(e.target.x-e.x,-(e.target.y-e.y))+fan}else if(e.age<1.25)desired=e.a+e.curveSide*.65*dt;const diff=Math.atan2(Math.sin(desired-e.a),Math.cos(desired-e.a));e.a+=Math.max(-2.7*dt,Math.min(2.7*dt,diff));e.x+=Math.sin(e.a)*e.speed*dt;e.y-=Math.cos(e.a)*e.speed*dt;}else{if(e.target&&aliveActor(e.target)&&e.target.generation===e.targetLife&&e.age>.18){const desired=Math.atan2(e.target.x-e.x,-(e.target.y-e.y)),diff=Math.atan2(Math.sin(desired-e.a),Math.cos(desired-e.a)),speed=e.id==='hunter'?1.1:1.6;e.a+=Math.max(-dt*speed,Math.min(dt*speed,diff))}e.x+=Math.sin(e.a)*e.speed*dt;e.y-=Math.cos(e.a)*e.speed*dt;}e.travel+=e.speed*dt;e.trail-=dt;
 if(e.id==='swarm'&&e.age>.07)Sound.loop('swarm-scream',e.soundKey,e.x,e.y,.84,e.soundRate);if(e.trail<=0){if(g.kind==='rocket'){smokePuff(e.x,e.y,e.id==='hunter'?22:17,2.3);smokePuff(e.x+(Math.random()-.5)*14,e.y+(Math.random()-.5)*14,11,1.7);}if(g.kind==='plasma')emit({x:e.x,y:e.y,vx:0,vy:0,color:g.color,size:4,life:.15,max:.15,kind:'spark'});if(g.kind==='flame')emit({x:e.x+(Math.random()-.5)*e.age*50,y:e.y+(Math.random()-.5)*e.age*50,vx:0,vy:0,color:'#ff8b31',size:5+e.age*18,life:.25,max:.25,kind:'fire'});e.trail=g.kind==='rocket'?.035:.025}
 const hit=g.kind==='mortar'||g.kind==='smoke'?null:sweepHit(e.px,e.py,e.x,e.y,e.owner);const wall=e.x<15||e.x>ARENA.size-15||e.y<15||e.y>ARENA.size-15;
 if(hit||wall||e.life<=0){const x=hit?hit.x:Math.max(15,Math.min(ARENA.size-15,e.x)),y=hit?hit.y:Math.max(15,Math.min(ARENA.size-15,e.y));if(g.kind==='smoke'){addSmokeCloud(x,y)}else if(g.kind==='mortar'){for(let j=0;j<7;j++)impact(e.id,x+(Math.random()-.5)*110,y+(Math.random()-.5)*110,false,{...e.stats,damage:e.stats.damage/7},{owner:e.owner})}else if(hit||wall)impact(e.id,x,y,hit?shielded(hit.target):false,e.id==='flak'?{...e.stats,damage:e.stats.damage*Math.max(.35,1-e.travel/1200)}:e.stats,hit||{owner:e.owner});if(e.soundKey)Sound.stopLoop(e.soundKey);rounds.splice(i,1)}
 }
 for(let i=mines.length-1;i>=0;i--){const m=mines[i];m.life-=dt;m.age+=dt;if(m.armed>0){const u=Math.min(1,m.age/m.flight);const nx=m.startX+m.dx*u,ny=m.startY+m.dy*u,obstacle=urbanSweep(m.x,m.y,nx,ny);if(obstacle){m.dx=(obstacle.x-m.startX)/Math.max(u,.001);m.dy=(obstacle.y-m.startY)/Math.max(u,.001);m.flight=m.age;}m.x=obstacle?obstacle.x:nx;m.y=obstacle?obstacle.y:ny;m.angle=m.spin*u;Sound.loop('mine-flight',m.soundKey,m.x,m.y,.65,1);m.armed=Math.max(0,m.flight-m.age);if(m.armed===0){Sound.stopLoop(m.soundKey);Sound.play('mine-arm',m.x,m.y,.65,1+(i%5-2)*.035,true);m.armFlash=.14}}else{m.armFlash=Math.max(0,(m.armFlash||0)-dt)}const trigger=m.armed<=0&&[p,...enemies].some(t=>t!==m.owner&&aliveActor(t)&&Math.hypot(t.x-m.x,t.y-m.y)<110);if(m.life<=0||trigger){if(trigger)impact('mines',m.x,m.y,false,m.stats,{owner:m.owner});Sound.stopLoop(m.soundKey);mines.splice(i,1)}}

 for(const arr of [particles,flashes,lines,marks])for(let i=arr.length-1;i>=0;i--){const e=arr[i];e.life-=dt;if(e.vx!==undefined){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vx*=Math.exp(-3*dt);e.vy*=Math.exp(-3*dt)}if(e.life<=0)arr.splice(i,1)}
}
function texture(c,index,x,y,size,alpha=1){const im=images.fx;if(!im)return;c.save();c.globalAlpha=alpha;const w=im.width/4,h=im.height/2;c.drawImage(im,(index%4)*w,Math.floor(index/4)*h,w,h,x-size/2,y-size/2,size,size);c.restore()}
function glow(c,x,y,r,color,alpha=1){c.save();c.globalAlpha=alpha;const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(.3,color+'bb');g.addColorStop(1,color+'00');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2);c.restore()}
function drawWeapons(c){
 for(const t of targets){c.save();c.translate(t.x,t.y);c.fillStyle='#4c5849';c.strokeStyle='#a4a58c';c.lineWidth=3;c.fillRect(-43,-43,86,86);c.strokeRect(-43,-43,86,86);c.strokeStyle='#adb18c';for(const a of [-1,1])for(const b of [-1,1]){c.beginPath();c.arc(a*35,b*35,3,0,7);c.stroke()}c.strokeStyle='#a8a88b';c.beginPath();c.arc(0,0,23,0,7);c.moveTo(-30,0);c.lineTo(30,0);c.moveTo(0,-30);c.lineTo(0,30);c.stroke();c.fillStyle='#b7bdaa';c.font='10px system-ui';c.fillText(t.shield?'SHIELD TEST':'ARMOUR TEST',-34,64);if(t.shield){c.fillStyle='#479fff22';c.strokeStyle='#68cfff99';c.beginPath();c.arc(0,0,t.r+20,0,7);c.fill();c.stroke()}c.restore()}
 for(const m of marks){c.globalAlpha=Math.min(.65,m.life/3);c.fillStyle='#10140f';c.beginPath();c.ellipse(m.x,m.y,m.r,m.r*.7,0,0,Math.PI*2);c.fill();texture(c,4,m.x,m.y,m.r*3,Math.min(.6,m.life/3))}c.globalAlpha=1;
 for(const e of particles){const alpha=e.life/e.max;c.save();c.globalAlpha=alpha*(e.kind==='smoke'?.5:1);c.fillStyle=e.color;if(e.kind==='smoke'){softSmoke(c,e.x,e.y,e.size*3*(2-alpha),alpha*.65)}else if(e.kind==='case'){c.translate(e.x,e.y);c.rotate(e.life*12);c.fillRect(-2,-1,4,2)}else if(e.kind==='fire'){texture(c,1,e.x,e.y,e.size*3,alpha);c.fillStyle='#ffd88a';c.beginPath();c.arc(e.x,e.y,e.size*.2,0,7);c.fill()}else{c.beginPath();c.arc(e.x,e.y,e.kind==='smoke'?e.size*(2-alpha):e.size,0,7);c.fill()}c.restore()}
 for(const e of rounds){const g=GUNS[e.id];c.save();c.translate(e.x,e.y);c.rotate(e.a);if(g.kind==='rocket'){glow(c,0,9,12,'#ff9b35');c.fillStyle='#b6bab0';c.beginPath();c.moveTo(0,-9);c.lineTo(3,-3);c.lineTo(3,6);c.lineTo(-3,6);c.lineTo(-3,-3);c.closePath();c.fill();c.fillStyle='#675f42';c.fillRect(-4,5,8,3)}else if(g.kind==='plasma'){glow(c,0,0,12,g.color);c.fillStyle='#d5ffff';c.beginPath();c.ellipse(0,0,3,6,0,0,7);c.fill()}else if(g.kind==='emp'){c.strokeStyle=g.color;c.lineWidth=2;c.beginPath();c.ellipse(0,0,12,5,0,0,7);c.stroke();glow(c,0,0,12,g.color,.5)}else if(g.kind!=='flame'){c.strokeStyle=g.color;c.lineWidth=g.kind==='rail'?1:g.kind==='pulse'?2:1.4;c.beginPath();c.moveTo(0,0);c.lineTo(0,g.kind==='rail'?80:g.kind==='pulse'?35:g.kind==='bullet'?18:12);c.stroke();if(['shell','mortar','flak'].includes(g.kind)){c.fillStyle='#9ca598';c.fillRect(-2,-4,4,9)}}c.restore()}
 for(const l of lines){c.save();c.globalAlpha=l.life/l.total;c.strokeStyle=l.color;c.lineWidth=l.arc?1.5:3;c.beginPath();c.moveTo(l.x,l.y);if(l.arc){for(let j=1;j<12;j++)c.lineTo(l.x+(l.ex-l.x)*j/12+(Math.random()-.5)*15,l.y+(l.ey-l.y)*j/12+(Math.random()-.5)*15)}c.lineTo(l.ex,l.ey);c.stroke();c.strokeStyle='#fff9';c.lineWidth=.7;c.stroke();c.restore()}
 for(const m of mines)drawBatonMine(c,m);
 drawCombatFx(c);
 for(const f of flashes){const a=f.life/f.total;if(f.tex!==undefined)texture(c,f.tex,f.x,f.y,f.ring?f.max*(1-a)*2:f.r*2.8,a);if(f.ring){c.save();c.globalAlpha=a;c.strokeStyle=f.color;c.lineWidth=3;for(let j=0;j<3;j++){c.beginPath();c.arc(f.x,f.y,Math.max(1,f.max*(1-a)+j*8),0,7);c.stroke()}c.restore()}else glow(c,f.x,f.y,f.r,f.color,a)}
}
