'use strict';
// Quick Battle configuration is separate from Championship story progression.
const PILOTS=[
{id:'jim',name:'Rourke',title:'The Underdog',bio:'An unknown rookie with a scorched steel mech, an empty wallet, but plenty to prove. With Dave keeping his Mech together, Rourke enters the Iron Pit to see how far nerve and determination can take him.'},
{id:'dave',name:'Dave',title:'The Mechanic',bio:'Owner of Daves Fix n Spray, mechanic, pit crew and Rourke’s loudest supporter. Dave can weld almost anything back together—and usually has something sarcastic to say while doing it. He believes in Rourke, even when the repair bill suggests he shouldn’t.'},
{id:'rivet',name:'Rivet',title:'The Rival',bio:'Confident, sharp-tongued and backed by a sponsor, Rivet expects to win. Her Assault tank delivers punishing rocket barrages, but its reload gives a brave opponent an opening. She enjoys winding Rourke up; earning her respect takes more than one victory.'},
{id:'skitter',name:'Skitter',title:'The Speedster',bio:'The youngest pilot but the quickest hands, feet and an even quicker Mech. Sporting the red-and-white Racer livery, Skitter darts around opponents and leaves mines where they least expect them. Chase her and you’re playing her game.'},
{id:'bastion',name:'Bastion',title:'The Heavyweight',bio:'Bastion likes heavy armour, overwhelming firepower and short conversations. His battered black Mech show his love of anarchy, and he treats every challenger as just another target. He expects rookies to panic when the big guns turn towards them.'},
{id:'zane',name:'Zane',title:'The Assassin',bio:'A young pilot with a competitive streak and a knack for spotting an opening. His Shark livery makes his Mech easy to recognise—and he intends to make his name just as memorable. Defeat bruises his pride, but only makes him more determined to win the rematch.'},
{id:'hudson',name:'Dr Lilith Kane',title:'The Sponsor',bio:'An assured corporate power player who has taken a particular interest in Rourke’s rise through the arena. Her sponsorship opens doors to better equipment and bigger opportunities. She is generous with her attention, careful with her promises, but hasn’t yet explained everything she expects in return.'},
{id:'voss',name:'Silas Voss',title:'The Puppet Master',bio:'A former Mech pilot whose arena career ended in a devastating Mech malfunction, Voss now commands a powerful sponsorship empire. He buys talented pilots, supplies experimental weapons and demands absolute loyalty. Rourke’s rise threatens his control—and Voss intends to put him in his place.'},
{id:'quinn',name:'Professor Felix Quinn',title:'The Weapons Architect',bio:'A brilliant weapons developer with an unhealthy enthusiasm for experimental firepower. Quinn once designed prototypes for Dr Kane; now Voss funds his research. Dave has a black market contact that gets him Quinn’s latest designs. Quinn insists every malfunction is simply “valuable test data.”'},
{id:'unknown',name:'The Unknown',title:'The Mystery',bio:'No name. No history. No face behind the visor. The Unknown enters the arena without a word and leaves opponents with more questions than answers.'}
];
STORY_CAST.quinn={name:'Professor Felix Quinn',role:'THE WEAPONS ARCHITECT'};STORY_CAST.unknown={name:'The Unknown',role:'UNIDENTIFIED PILOT'};STORY_CAST.zane={name:'Zane',role:'THE ASSASSIN'};STORY_CAST.voss={name:'Silas Voss',role:'THE PUPPET MASTER'};
let quickPilots=['jim','rivet'],workshopTab='pilot';
try{const v=JSON.parse(localStorage.getItem('iron-pit-pilots'));if(Array.isArray(v))quickPilots=[0,1].map(i=>PILOTS.some(p=>p.id===v[i])?v[i]:quickPilots[i])}catch(e){}
const pilotId=()=>campaignActive?'jim':quickPilots[buildTurn===1?1:0];
function pilotPortrait(id,mood='focused'){if(id==='hudson')return 'assets/story-hudson'+(mood==='win'?'-win':mood==='loss'?'-loss':'')+'.png';if(id==='voss')return 'assets/story-voss.jpg';if(id==='quinn')return 'assets/story-quinn.jpg';if(id==='unknown')return 'assets/story-unknown.jpg';if(id==='dave')return 'assets/story-dave-'+(mood==='loss'?'loss':'win')+'-0.jpg';return 'assets/story-'+id+(mood==='focused'?'':'-'+mood)+'.jpg'}
function choosePilot(id){if(campaignActive)return;quickPilots[buildTurn===1?1:0]=id;const signature={jim:'starter',skitter:'racer',bastion:'anarchy',zane:'shark'}[id];if(signature){build.colour=signature;node('colour').value=signature;node('paintChoice').value=signature;saveWorkshopBuild();update();}try{localStorage.setItem('iron-pit-pilots',JSON.stringify(quickPilots))}catch(e){}renderPilot();}
function arrowButton(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;return b}
// Preserve the existing arena canvas rendering and all six actual playable maps.
const start=node('startScreen');start.classList.add('metal-menu');start.querySelector('h1').textContent='IRON PIT';
const sub=document.createElement('small');sub.className='menu-subtitle';sub.textContent='QUICK BATTLE — ARENA SELECTION';start.querySelector('header div')?.append(sub)||start.querySelector('header').prepend(sub);
const hazards=document.createElement('small');hazards.id='arenaHazards';node('arenaHero').querySelector('div').append(hazards);node('championshipStart').hidden=true;start.querySelector('.mode-carousel').hidden=true;
for(const h of start.querySelectorAll(':scope > h2'))h.hidden=true;
const count=document.createElement('section');count.id='enemyCountPanel';count.className='metal-panel';count.innerHTML='<strong>ENEMY MECHS</strong><div><button id="enemyMinus" aria-label="Fewer enemy Mechs">−</button><output id="enemyCount">1</output><button id="enemyPlus" aria-label="More enemy Mechs">+</button></div><small>Choose how many rivals enter the arena.</small>';
node('arenaCarousel').after(count);
function selectEnemyCount(n){selectedOpponents=Math.max(1,Math.min(BOT_ACTORS.length,n));selectedMode=String(selectedOpponents);node('enemyCount').value=selectedOpponents;node('enemyCount').textContent=selectedOpponents;node('enemyMinus').disabled=selectedOpponents<=1;node('enemyPlus').disabled=selectedOpponents>=BOT_ACTORS.length;refreshLevelChoice();}
node('enemyMinus').onclick=()=>selectEnemyCount(selectedOpponents-1);node('enemyPlus').onclick=()=>selectEnemyCount(selectedOpponents+1);
const oldRefreshChoice=refreshLevelChoice;
refreshLevelChoice=function(){oldRefreshChoice();const card=node('arenaCarousel').querySelector('[aria-pressed="true"]');if(card)node('arenaCarousel').scrollLeft=card.offsetLeft-node('arenaCarousel').offsetLeft-(node('arenaCarousel').clientWidth-card.clientWidth)/2;node('modeConfirm').textContent='CONTINUE TO WORKSHOP →';const extra=selectedMode==='duel'?'TWO PLAYERS':selectedMode==='test'?'WEAPON RANGE':selectedOpponents+' ENEMY MECH'+(selectedOpponents===1?'':'S');node('levelStatus').textContent=extra+' · '+ARENA_VARIANTS[selectedArena||'desert'].label;node('arenaHazards').textContent='HAZARDS: '+({desert:'SANDSTORMS',flooded:'FLOODED GROUND',night:'LOW VISIBILITY',rotating:'ROTATING PLATFORM',snow:'SNOW',conveyors:'CONVEYOR BELTS'}[selectedArena||'desert'])+' · SHIFTING FORCEFIELDS';count.hidden=['duel','test'].includes(selectedMode)};
const oldShowLevel=showLevelSelect;
showLevelSelect=function(){oldShowLevel();if(!selectedArena)selectedArena=arenaKind;if(!selectedMode||selectedMode==='story')selectedMode=String(selectedOpponents);selectEnemyCount(selectedOpponents);};
node('splashStart').onclick=showLevelSelect;
// The arena screen contains no Championship entry; campaign goes straight to story.
node('levelBack').onclick=()=>{start.hidden=true;node('splash').hidden=false;Sound.startMusic()};
const builder=node('builder');builder.classList.add('metal-menu');builder.querySelector('h1').textContent='Daves Fix n Spray';
const tag=document.createElement('small');tag.className='menu-subtitle';tag.textContent='Mech Workshop';builder.querySelector('header>div').append(tag);
const tabs=document.createElement('nav');tabs.id='workshopTabs';tabs.setAttribute('aria-label','Mech customisation');tabs.setAttribute('role','tablist');
const panel=document.createElement('section');panel.id='workshopChoices';
for(const [id,label]of [['pilot','PILOT'],['chassis','CHASSIS'],['weapons','WEAPONS'],['livery','LIVERY']]){const b=arrowButton(label,()=>showWorkshopTab(id));b.id='tab-'+id;b.dataset.tab=id;b.setAttribute('role','tab');b.setAttribute('aria-controls','choices-'+id);tabs.append(b);const box=document.createElement('div');box.id='choices-'+id;box.setAttribute('role','tabpanel');box.setAttribute('aria-labelledby',b.id);panel.append(box)}
builder.querySelector('.preview').after(tabs,panel);
node('choices-chassis').append(node('chassisCarousel'));
node('choices-weapons').innerHTML='<p class="choice-heading">CHOOSE A HARDPOINT</p><div id="weaponMountChoices"></div><small>Fitted weapons appear on your Mech above.</small>';
for(const [key,group]of Object.entries(workshopSlots)){const b=arrowButton(group.label,()=>openWorkshopWeapons(key));b.dataset.mountChoice=key;node('weaponMountChoices').append(b)}
node('choices-pilot').innerHTML='<div class="carousel-with-arrows"><button id="pilotPrevious" aria-label="Previous pilot">❮</button><div class="carousel" id="pilotCarousel"></div><button id="pilotNext" aria-label="Next pilot">❯</button></div><div id="pilotBio" class="metal-panel"><strong></strong><p></p></div>';
for(const pilot of PILOTS){const b=document.createElement('button');b.type='button';b.className='pilot-card';b.dataset.pilot=pilot.id;b.innerHTML='<img alt=""><span></span>';b.querySelector('img').src=pilotPortrait(pilot.id);b.querySelector('img').alt=pilot.name;b.querySelector('span').textContent=pilot.name.toUpperCase();b.onclick=()=>choosePilot(pilot.id);node('pilotCarousel').append(b)}
function cyclePilot(dir){const i=PILOTS.findIndex(p=>p.id===pilotId());choosePilot(PILOTS[(i+dir+PILOTS.length)%PILOTS.length].id)}
node('pilotPrevious').onclick=()=>cyclePilot(-1);node('pilotNext').onclick=()=>cyclePilot(1);
function renderPilot(){const id=pilotId(),pilot=PILOTS.find(p=>p.id===id);node('pilotBio').querySelector('strong').textContent=pilot.name.toUpperCase()+' — '+pilot.title.toUpperCase();node('pilotBio p').textContent=pilot.bio;for(const card of node('pilotCarousel').children){card.setAttribute('aria-pressed',String(card.dataset.pilot===id));card.disabled=campaignActive;}
const selected=node('pilotCarousel').querySelector('[aria-pressed="true"]');if(selected&&workshopTab==='pilot')node('pilotCarousel').scrollLeft=selected.offsetLeft-node('pilotCarousel').offsetLeft-(node('pilotCarousel').clientWidth-selected.clientWidth)/2;
node('pilotPrevious').disabled=campaignActive;node('pilotNext').disabled=campaignActive;}
const LIVERY_ORDER=['starter','green','red','inferno','bluefire','toxic','shark','hazard','desertcamo','urbancamo','snowcamo','racer','reactor','warworn','midnightgold','anarchy'];
function liveryAvailable(id){if(!campaignActive)return true;if(id==='starter')return true;if(!rookieProgress.sponsorSeen)return false;const tier=LIVERY_ORDER.indexOf(id);return tier<=5+Math.max(0,(rookieProgress.completed||0)-5)*3+(rookieProgress.liveryWins||0);}
function enforceCampaignLivery(){if(campaignActive&&!liveryAvailable(build.colour)){build.colour='starter';node('colour').value='starter';node('paintChoice').value='starter';}}
node('choices-livery').innerHTML='<div id="liveryCarousel" class="carousel" aria-label="Choose livery"></div><small id="liveryHint"></small>';
for(const select of [node('colour'),node('paintChoice')]){select.replaceChildren();for(const id of LIVERY_ORDER){const option=document.createElement('option');option.value=id;option.textContent=PALETTES[id].name;select.append(option)}select.value=build.colour;}
for(const id of LIVERY_ORDER){const b=document.createElement('button');b.type='button';b.className='livery-card';b.dataset.livery=id;b.innerHTML='<canvas width="150" height="150"></canvas><span></span><small></small>';b.querySelector('span').textContent=PALETTES[id].name;b.onclick=()=>{if(!liveryAvailable(id))return;build.colour=id;node('colour').value=id;node('paintChoice').value=id;saveWorkshopBuild();update()};node('liveryCarousel').append(b)}
function renderLiveries(){for(const card of node('liveryCarousel').children){const id=card.dataset.livery;card.disabled=!liveryAvailable(id);card.setAttribute('aria-pressed',String(id===build.colour));card.querySelector('small').textContent=card.disabled?'SPONSOR / PROGRESSION LOCKED':'CHASSIS + WEAPONS';if(ready){const cv=card.querySelector('canvas'),c=cv.getContext('2d');c.clearRect(0,0,150,150);mech(c,75,75,.43,0,0,{...build,colour:id})}}node('liveryHint').textContent=campaignActive&&!rookieProgress.sponsorSeen?'Rourke’s starting Mech. More liveries unlock after sponsorship.':'Livery applies to your chassis, turret and weapon housings.';}
function showWorkshopTab(id){workshopTab=id;closeWorkshopWeapons();for(const b of tabs.children){const active=b.dataset.tab===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;node('choices-'+b.dataset.tab).hidden=!active}builder.dataset.tab=id;renderPilot();if(id==='livery')renderLiveries();}
tabs.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const ids=['pilot','chassis','weapons','livery'],i=ids.indexOf(workshopTab),j=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;showWorkshopTab(ids[j]);node('tab-'+ids[j]).focus()};
const oldWorkshopRefresh=refreshWorkshop;
refreshWorkshop=function(){enforceCampaignLivery();oldWorkshopRefresh();renderPilot();for(const b of node('weaponMountChoices').children)b.textContent=workshopSlots[b.dataset.mountChoice].label+' · '+nameOf(build[b.dataset.mountChoice]);if(workshopTab==='livery')renderLiveries();if(!campaignActive)node('deploy').textContent=selectedMode==='duel'&&buildTurn===0?'CONFIRM · PLAYER TWO →':'START BATTLE →';node('workshopMode').textContent=campaignActive?'CHAMPIONSHIP · ROURKE':selectedMode==='duel'?'QUICK BATTLE · PLAYER '+(buildTurn+1):'QUICK BATTLE · '+ARENA_VARIANTS[arenaKind].label.toUpperCase()};
const oldUpdate52=update;update=function(){enforceCampaignLivery();oldUpdate52()};
const oldWorkshopEntry=enterSelectedWorkshop;enterSelectedWorkshop=function(){oldWorkshopEntry();showWorkshopTab('pilot');Sound.startMusic()};node('modeConfirm').onclick=enterSelectedWorkshop;
const oldPrepCampaign=prepareCampaignWorkshop;prepareCampaignWorkshop=function(){oldPrepCampaign();showWorkshopTab('chassis');Sound.startMusic()};
const oldBack52=node('buildBack').onclick;node('buildBack').onclick=()=>{oldBack52();if(!campaignActive)showLevelSelect()};
// Story opponents use their approved signature liveries.
for(const match of ROOKIE_MATCHES)for(const bot of match.bots){if(bot.name==='SKITTER')bot.loadout.colour='racer';if(bot.name==='BASTION')bot.loadout.colour='anarchy';}
const oldPlace52=placeUrbanEnemy;placeUrbanEnemy=function(){if(!campaignActive){const ids=['rivet','skitter','bastion'];for(const [i,bot]of BOT_ACTORS.entries()){bot.name=STORY_CAST[ids[i]].name.toUpperCase();bot.pilot=ids[i];bot.loadout={...BOT_BUILDS[i],colour:['red','racer','anarchy'][i]};} }oldPlace52();};
const oldDeploy52=node('deploy').onclick;node('deploy').onclick=()=>{enforceCampaignLivery();const chosen=pilotId();oldDeploy52();if(inArena&&!campaignActive){p.pilot=chosen;p.name=PILOTS.find(v=>v.id===chosen).name.toUpperCase();if(duelActive)for(const state of duelPlayers){state.actor.pilot=quickPilots[state.index];state.actor.name=PILOTS.find(v=>v.id===state.actor.pilot).name.toUpperCase();}}};
const oldFinish52=finishBattle;finishBattle=function(winner){const existed=!!battleResult;oldFinish52(winner);if(existed||campaignActive||weaponRange)return;const id=duelActive?(winner?.pilot||pilotId()):pilotId(),won=duelActive?!!winner:winner===p;showPilotResult(id,won);};
function showPilotResult(id,won){node('pilotResult')?.remove();const el=document.createElement('aside');el.id='pilotResult';el.setAttribute('role','status');const img=document.createElement('img');img.src=pilotPortrait(id,won?'win':'loss');img.alt=PILOTS.find(v=>v.id===id).name;const text=document.createElement('strong');text.textContent=won?'VICTORY':'MECH LOST';const close=arrowButton('×',()=>el.remove());close.setAttribute('aria-label','Dismiss pilot transmission');el.append(img,text,close);node('arena').append(el)}
const oldReturn52=node('return').onclick;node('return').onclick=()=>{node('pilotResult')?.remove();oldReturn52();};
const oldRematch52=node('rematch').onclick;node('rematch').onclick=()=>{node('pilotResult')?.remove();oldRematch52?.()};
// Replayed post-sponsor Championship victories unlock successive paint schemes.
const oldCampaignFinish52=finishBattle;finishBattle=function(winner){const existed=!!battleResult;oldCampaignFinish52(winner);if(!existed&&campaignActive&&rookieProgress.sponsorSeen&&winner===p){rookieProgress.liveryWins=(rookieProgress.liveryWins||0)+1;saveRookie()}};
node('paintCycle').parentElement.hidden=true;
if(build.colour==='green'&&pilotId()==='jim'&&!localStorage.getItem('iron-pit-build-v2'))build.colour='starter';showWorkshopTab('pilot');refreshWorkshop();

function vossReactionPortrait(rourkeWon){return 'assets/story-voss-rourke-'+(rourkeWon?'win':'loss')+'.jpg'}
const basePortrait53=portraitFor;portraitFor=function(who,mood='focused'){if(who==='voss'&&['rourke-win','rourke-loss'].includes(mood))return 'assets/story-voss-'+mood+'.jpg';if(who==='quinn')return pilotPortrait('quinn');return basePortrait53(who,mood)};

const kanePortrait54=portraitFor;portraitFor=function(who,mood='focused'){if(who==='hudson'&&mood==='league-win')return 'assets/story-kane-league-win.jpg';if(who==='hudson'&&mood==='championship-win')return 'assets/story-kane-championship-win.jpg';return kanePortrait54(who,mood)};
function showChampionshipVictory(done){showStoryDialogue([['hudson','Champion.']],done,{title:'Champion',round:'CHAMPIONSHIP WON',arena:'desert',brief:'Championship complete'},{hudson:'championship-win'});}
