'use strict';
let selectedOpponents=1,selectedMode=null,selectedArena=null,workshopMount='left';
const workshopSlots={left:{label:'WPN 1',ids:PRIMARY_IDS,slot:'primary'},right:{label:'WPN 2',ids:SECONDARY_IDS,slot:'secondary'},rear:{label:'WPN 3',ids:rear.map(w=>w[0]),slot:'support'}};
const nameOf=id=>[...side,...rear].find(w=>w[0]===id)?.[1]||'None';
const node=id=>document.getElementById(id);
const matchDeploy=node('deploy').onclick,matchReturn=node('return').onclick;
function showLevelSelect(){if(duelActive)leaveDuel();node('splash').hidden=true;node('builder').style.display='none';node('arena').style.display='none';node('startScreen').hidden=false;node('startScreen').classList.add('level-select');inArena=false;lockBattlePage(false);Sound.unlock();Sound.startMusic();refreshLevelChoice()}
function refreshLevelChoice(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===selectedMode)));document.querySelectorAll('[data-arena]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.arena===selectedArena)));const valid=!!selectedMode&&!!selectedArena;node('modeConfirm').disabled=!valid;node('modeConfirm').classList.toggle('ready-flash',valid);node('levelStatus').textContent=valid?'READY · CONFIRM TO ENTER WORKSHOP':'CHOOSE A MODE AND AN ARENA'}
function enterSelectedWorkshop(){if(!selectedMode||!selectedArena)return;arenaKind=selectedArena;node('arenaChoice').value=arenaKind;try{localStorage.setItem('iron-pit-arena',arenaKind)}catch(e){}node('startScreen').hidden=true;node('splash').hidden=true;if(selectedMode==='duel'){beginDuelBuild()}else{selectedOpponents=selectedMode==='test'?1:Number(selectedMode);setArenaMode('solo');node('onePlayer').onclick();}closeWorkshopWeapons();update();refreshWorkshop()}
function chassisCard(id){const card=document.createElement('button');card.type='button';card.dataset.chassis=id;card.className='chassis-card';card.setAttribute('aria-pressed','false');const canvas=document.createElement('canvas');canvas.width=140;canvas.height=130;card.appendChild(canvas);const name=document.createElement('span');name.textContent=CHASSIS_CLASSES[id].name;card.appendChild(name);const info=document.createElement('small');info.textContent=Math.round(CHASSIS_CLASSES[id].armour*100)+'% ARMOUR · '+CHASSIS_CLASSES[id].speed+' U/S';card.appendChild(info);card.onclick=()=>{build.chassis=id;build.turret='turret';node('chassis').value=id;node('turret').value='turret';saveWorkshopBuild();update();};return card}
function saveWorkshopBuild(){try{localStorage.setItem('iron-pit-build-v2',JSON.stringify(build));localStorage.setItem('iron-pit-modifications',JSON.stringify(modifications))}catch(e){}}
function closeWorkshopWeapons(){node('weaponCarouselPanel').hidden=true}
function openWorkshopWeapons(key){workshopMount=key;const group=workshopSlots[key],list=node('weaponCarousel');list.replaceChildren();node('weaponCarouselTitle').textContent=group.label+' · SELECT WEAPON';for(const id of ['',...group.ids.slice().sort((a,b)=>WEAPON_UNLOCK[a]-WEAPON_UNLOCK[b])]){const card=document.createElement('button');card.type='button';card.className='weapon-card';card.setAttribute('aria-pressed',String(build[key]===id));card.disabled=!weaponAvailable(id);if(id){const im=document.createElement('img');im.src='assets/'+id+'.png';im.alt='';card.appendChild(im)}else{const blank=document.createElement('span');blank.className='empty-weapon';blank.textContent='—';card.appendChild(blank)}const name=document.createElement('span');name.textContent=id?nameOf(id):'Empty hardpoint';card.appendChild(name);const weight=document.createElement('small');weight.textContent=id?(card.disabled?WEAPON_UNLOCK[id]+' WINS TO UNLOCK':WEAPON_WEIGHT[id]+' WT'):'NO SPEED PENALTY';card.appendChild(weight);card.onclick=()=>{build[key]=id;node(key).value=id;modifications[group.slot]='standard';saveWorkshopBuild();closeWorkshopWeapons();update();};list.appendChild(card)}node('weaponCarouselPanel').hidden=false;list.scrollLeft=0;const mod=node('workshopModifier');mod.innerHTML=node(group.slot+'Mod').innerHTML;mod.value=modifications[group.slot];mod.disabled=!build[key];const choices=node('modifierChoices');choices.replaceChildren();for(const option of Array.from(mod.options)){const b=document.createElement('button');b.textContent=option.textContent;b.disabled=mod.disabled||option.disabled;b.setAttribute('aria-pressed',String(option.value===mod.value));b.onclick=()=>{mod.value=option.value;mod.onchange();for(const button of choices.children)button.setAttribute('aria-pressed',String(button===b))};choices.appendChild(b)}mod.onchange=()=>{modifications[group.slot]=mod.value;node(group.slot+'Mod').value=mod.value;saveWorkshopBuild();refreshWorkshop()}}
// Approximate event simulation: three systems firing together at a 300-unit,
// stationary 700 HP assault target. Includes heat/reloads, armour and travel.
// This is an ideal firepower estimate; the actual Range measures game collisions.
const workshopTtkCache=new Map();
function estimateWorkshopTTK(){const key=JSON.stringify([build.left,build.right,build.rear,modifications]);if(workshopTtkCache.has(key))return workshopTtkCache.get(key);const systems=Object.entries(workshopSlots).filter(([k])=>build[k]).map(([k,g])=>({id:build[k],stats:weaponStats(build[k],modifications[g.slot]),heat:0,locked:false,next:0}));let hp=700,burn=0;const pending=[];const dt=1/60;let result=null;for(let t=0;t<180&&hp>0;t+=dt){if(burn>0){hp-=30*dt;burn-=dt}for(const s of systems){const gun=GUNS[s.id],cfg=HEAT_CONFIG[s.id];if(s.locked&&cfg){s.heat=Math.max(0,s.heat-dt*80/cfg.cool);if(s.heat<=20)s.locked=false}if(t+1e-6<s.next||s.locked)continue;s.next=t+s.stats.rate;if(cfg){s.heat=Math.min(100,s.heat+(cfg.seconds?80*s.stats.rate/cfg.seconds:80/(cfg.shots-.5)));if(s.heat>=100)s.locked=true}if(['smoke','mines'].includes(s.id))continue;const count=gun.cycle?1:s.id==='flak'?5:gun.ports.length;let damage=s.stats.damage*(s.stats.continuous?s.stats.rate:count)*(1-.25*(1-s.stats.penetration));if(s.id==='flak')damage*=.6;if(gun.range&&gun.range+190<300)continue;let travel=s.stats.continuous?0:Math.max(0,300-140)/(gun.speed||500);if(s.id==='plasma')travel+=.3;if(s.id==='smart')travel+=t===0?.1:0;if(s.id==='mortar')travel=2.2;if(s.id==='barrage')travel+=1;if(s.id==='swarm')travel+=.4;pending.push({at:t+travel,damage,burn:s.id==='flame'})}for(let i=pending.length-1;i>=0;i--)if(pending[i].at<=t){hp-=pending[i].damage;if(pending[i].burn)burn=1.3;pending.splice(i,1)}if(hp<=0)result=t+dt}workshopTtkCache.set(key,result);return result}
function refreshWorkshop(){const profile=chassisProfile(build);node('schematicTitle').textContent=profile.name.toUpperCase();node('workshopSpeed').textContent=Math.round(loadoutSpeed(build));node('workshopWeight').textContent=loadoutWeight(build);const ttk=estimateWorkshopTTK();node('workshopTTK').textContent=ttk===null?'—':ttk.toFixed(1)+'s';node('workshopTarget').textContent=ttk===null?'NO FORWARD KILL IN 180s':'700 HP · 300U · SHIELDS OFF';document.querySelectorAll('[data-chassis]').forEach(card=>card.setAttribute('aria-pressed',String(card.dataset.chassis===build.chassis)));for(const[k,g]of Object.entries(workshopSlots)){node('mount-'+k).querySelector('small').textContent=nameOf(build[k]);node('mount-'+k).setAttribute('aria-label',g.label+' '+nameOf(build[k])+'; choose weapon')}node('paintChoice').value=build.colour;node('paintCycle').textContent=PALETTES[build.colour].name;node('workshopMode').textContent=selectedMode==='duel'?'PLAYER '+(buildTurn+1):selectedMode==='test'?'WEAPON TEST':selectedOpponents+' ENEM'+(selectedOpponents===1?'Y':'IES');node('deploy').textContent=selectedMode==='duel'&&buildTurn===0?'CONFIRM · PLAYER TWO BUILDS NEXT':'DEPLOY';drawWorkshopCards()}
let workshopCardsReady=false;
function drawWorkshopCards(){if(!ready)return;if(workshopCardsReady===build.colour)return;workshopCardsReady=build.colour;document.querySelectorAll('[data-chassis]').forEach(card=>{const cv=card.querySelector('canvas'),c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);mech(c,cv.width/2,cv.height/2,.4,0,0,{chassis:card.dataset.chassis,turret:'turret',left:'',right:'',rear:'',colour:build.colour})});drawLevelCards()}
function drawLevelCards(){if(!ready)return;document.querySelectorAll('[data-arena]').forEach(card=>{const cv=card.querySelector('canvas'),c=cv.getContext('2d'),variant=ARENA_VARIANTS[card.dataset.arena];c.fillStyle='#071019';c.fillRect(0,0,cv.width,cv.height);const im=images[variant.ground];c.drawImage(im,25,24,cv.width-50,cv.height-48);c.fillStyle='rgba(0,8,22,'+variant.dark+')';c.fillRect(25,24,cv.width-50,cv.height-48);if(card.dataset.arena==='rotating')c.drawImage(images['arena-platform'],cv.width/2-36,cv.height/2-36,72,72);if(card.dataset.arena==='conveyors'){c.fillStyle='#66756d';for(let i=0;i<7;i++)c.fillRect(40+i*14,cv.height/2-6,8,12)}c.drawImage(images['stadium-frame'],0,0,cv.width,cv.height)});document.querySelectorAll('[data-mode-canvas]').forEach(cv=>{const c=cv.getContext('2d'),count=Number(cv.dataset.modeCanvas);c.fillStyle='#08141d';c.fillRect(0,0,cv.width,cv.height);mech(c,34,cv.height/2,.22,0,0,{chassis:'chassis',turret:'turret',left:'rotary',right:'siege',rear:'swarm',colour:'green'});for(let i=0;i<count;i++)mech(c,90+i*44,cv.height/2,.17,Math.PI,Math.PI,{chassis:i===1?'biped':'chassis',turret:'turret',left:'machine-gun',right:'plasma',rear:'hunter',colour:'red'})})}
const originalWorkshopUpdate=update;update=function(){originalWorkshopUpdate();if(node('chassisCarousel'))refreshWorkshop()};
node('splashStart').onclick=showLevelSelect;node('modeConfirm').onclick=enterSelectedWorkshop;node('levelBack').onclick=()=>{node('startScreen').hidden=true;node('splash').hidden=false;Sound.startMusic()};node('buildBack').onclick=()=>{closeWorkshopWeapons();showLevelSelect()};node('weaponCarouselClose').onclick=closeWorkshopWeapons;
for(const id of CHASSIS_IDS)node('chassisCarousel').appendChild(chassisCard(id));
for(const[k]of Object.entries(workshopSlots))node('mount-'+k).onclick=()=>openWorkshopWeapons(k);
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{selectedMode=b.dataset.mode;refreshLevelChoice()});
for(const[id,v]of Object.entries(ARENA_VARIANTS)){const b=document.createElement('button');b.type='button';b.className='arena-card';b.dataset.arena=id;b.innerHTML='<canvas width="180" height="170"></canvas><span></span>';b.querySelector('span').textContent=v.label;b.setAttribute('aria-label',v.label+'; '+v.description);b.onclick=()=>{selectedArena=id;refreshLevelChoice()};node('arenaCarousel').appendChild(b)}
node('paintChoice').onchange=()=>{build.colour=node('paintChoice').value;node('colour').value=build.colour;saveWorkshopBuild();update()};
node('deploy').onclick=()=>{if(selectedMode==='test'){openWeaponRange();node('builder').style.display='none';}else matchDeploy();closeWorkshopWeapons();refreshWorkshop()};
node('return').onclick=()=>{matchReturn();node('splash').hidden=true;node('startScreen').hidden=true;refreshWorkshop()};
node('builder').classList.add('tablet-workshop');node('builder').style.display='none';node('startScreen').hidden=true;node('splash').hidden=false;
if(!build.chassis)build.chassis='chassis';build.turret='turret';for(const key in build)if(node(key))node(key).value=build[key];
refreshLevelChoice();update();
// Art can still be loading when this script initialises.
const workshopReadyTimer=setInterval(()=>{if(ready){drawWorkshopCards();clearInterval(workshopReadyTimer)}},150);

function sizeControlPanels(){for(const id of ['p1-panel','p2-panel']){const panel=node(id);if(!panel||panel.hidden)continue;const outer=panel.querySelector('.movement');if(!outer)continue;const rect=panel.getBoundingClientRect(),styles=getComputedStyle(panel),button=parseFloat(styles.getPropertyValue('--control-w'))||48,gap=rect.width<440?3:6;const available=(rect.width-button*3-30)/2-button-gap;const usable=outer.getBoundingClientRect().height-20;panel.style.setProperty('--direction-size',Math.max(38,Math.min(usable,available))+'px')}}
if(typeof ResizeObserver!=='undefined'){const observer=new ResizeObserver(sizeControlPanels);for(const id of ['p1-panel','p2-panel'])observer.observe(node(id))}window.addEventListener('resize',sizeControlPanels);

node('paintCycle').onclick=()=>{node('paintChoice').value=build.colour==='red'?'green':'red';node('paintChoice').onchange()};
